// Black beans & pinto beans family — Mexican-leaning but versatile.

export const recipes = [
  {
    slug: 'black-bean-and-corn-quesadillas',
    title: 'Black Bean and Corn Quesadillas',
    summary: 'Crispy tortillas filled with black beans, corn, and melty cheese.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['lunch', 'dinner'],
    ingredients: [
      { slug: 'black_beans_canned', qty: 1, unit: 'can' },
      { slug: 'corn', qty: 1, unit: 'cup' },
      { slug: 'cheddar_cheese', qty: 1.5, unit: 'cup', prepNote: 'shredded' },
      { slug: 'tortilla_flour', qty: 8, unit: 'each' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'chili_powder', qty: 0.5, unit: 'tsp' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salsa', qty: 0.5, unit: 'cup', optional: true },
      { slug: 'sour_cream', qty: 0.25, unit: 'cup', optional: true },
    ],
    steps: [
      'Mash the black beans lightly with cumin and chili powder.',
      'Spread beans, corn, and cheese over half of each tortilla; fold over.',
      'Cook in a lightly oiled skillet, 2-3 minutes per side, until golden and the cheese melts.',
      'Cut into wedges and serve with salsa and sour cream.',
    ],
  },
  {
    slug: 'pinto-bean-and-rice-bowl',
    title: 'Pinto Bean and Rice Bowl',
    summary: 'A simple, filling bowl of seasoned pinto beans and rice.',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 20,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['lunch', 'dinner'],
    ingredients: [
      { slug: 'pinto_beans_canned', qty: 2, unit: 'can' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'chili_powder', qty: 0.5, unit: 'tsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'avocado', qty: 1, unit: 'each' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'cheddar_cheese', qty: 0.5, unit: 'cup', prepNote: 'shredded', optional: true },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Heat oil; soften onion and garlic, about 4 minutes.',
      'Add pinto beans, cumin, chili powder, and salt; simmer 10 minutes, mashing some of the beans for a creamier texture.',
      'Serve over rice topped with avocado, a squeeze of lime, and cheese if using.',
    ],
  },
  {
    slug: 'black-bean-burgers',
    title: 'Black Bean Burgers',
    summary: 'Hearty homemade black bean patties.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    cuisine: 'American',
    difficulty: 2,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'black_beans_canned', qty: 2, unit: 'can' },
      { slug: 'panko_breadcrumbs', qty: 0.5, unit: 'cup' },
      { slug: 'egg', qty: 1, unit: 'each' },
      { slug: 'garlic_powder', qty: 1, unit: 'tsp' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'onion', qty: 0.25, unit: 'each', prepNote: 'finely diced' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'bread_sandwich', qty: 4, unit: 'slice' },
      { slug: 'lettuce_romaine', qty: 4, unit: 'each' },
      { slug: 'tomato', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Mash the black beans, leaving some texture. Mix in breadcrumbs, egg, garlic powder, cumin, onion, and salt.',
      'Shape into 4 patties and chill 10 minutes if time allows.',
      'Pan-fry in oil, 4-5 minutes per side, until firm and browned.',
      'Serve on bread with lettuce and tomato.',
    ],
  },
  {
    slug: 'pinto-bean-chili',
    title: 'Vegetarian Pinto Bean Chili',
    summary: 'A hearty meatless chili loaded with pinto beans and vegetables.',
    servings: 6,
    prepMinutes: 10,
    cookMinutes: 35,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'pinto_beans_canned', qty: 2, unit: 'can' },
      { slug: 'black_beans_canned', qty: 1, unit: 'can' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'bell_pepper_green', qty: 1, unit: 'each' },
      { slug: 'chili_powder', qty: 2, unit: 'tbsp' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'smoked_paprika', qty: 1, unit: 'tsp' },
      { slug: 'tomato_canned_diced', qty: 2, unit: 'can' },
      { slug: 'corn', qty: 1, unit: 'cup' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1.5, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, and bell pepper, about 5 minutes.',
      'Stir in chili powder, cumin, and smoked paprika; cook 1 minute.',
      'Add diced tomatoes and all the beans. Simmer uncovered 25 minutes.',
      'Stir in corn, season with salt, and simmer 5 more minutes.',
    ],
  },
  {
    slug: 'cuban-black-beans-and-rice',
    title: 'Cuban Black Beans and Rice',
    summary: 'Classic Cuban-style black beans simmered with peppers over rice.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Cuban',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'black_beans_canned', qty: 2, unit: 'can' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'bell_pepper_green', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'oregano_dried', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1.5, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Heat oil; soften onion, bell pepper, and garlic, about 6 minutes.',
      'Add the black beans (with their liquid), cumin, and oregano. Simmer 15 minutes, mashing some beans for creaminess.',
      'Season with salt and lime juice, and serve over rice.',
    ],
  },
  {
    slug: 'loaded-nachos',
    title: 'Loaded Bean Nachos',
    summary: 'A sheet pan of tortilla chips loaded with beans, cheese, and toppings.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'black_beans_canned', qty: 1, unit: 'can' },
      { slug: 'pinto_beans_canned', qty: 1, unit: 'can' },
      { slug: 'tortilla_corn', qty: 12, unit: 'each', prepNote: 'cut into chips and baked, or use store-bought chips' },
      { slug: 'cheddar_cheese', qty: 1.5, unit: 'cup', prepNote: 'shredded' },
      { slug: 'jalapeno', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'tomato', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'sour_cream', qty: 0.25, unit: 'cup', optional: true },
      { slug: 'avocado', qty: 1, unit: 'each', optional: true },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 400°F (200°C). Warm the beans with cumin in a small pot.',
      'Spread tortilla chips on a sheet pan, top with beans, cheese, and jalapeño.',
      'Bake 8-10 minutes until the cheese melts.',
      'Top with tomato, green onion, sour cream, and avocado before serving.',
    ],
  },
  {
    slug: 'indian-rajma',
    title: 'Rajma (Kidney Bean Curry)',
    summary: 'North Indian spiced kidney beans, simmered until rich and thick.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    cuisine: 'Indian',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'pinto_beans_canned', qty: 2, unit: 'can', prepNote: 'or kidney beans if available' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'garam_masala', qty: 1, unit: 'tsp' },
      { slug: 'turmeric', qty: 0.5, unit: 'tsp' },
      { slug: 'tomato_paste', qty: 2, unit: 'tbsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, and ginger, about 6 minutes.',
      'Add cumin, garam masala, and turmeric; cook 1 minute.',
      'Stir in tomato paste and the beans (with some liquid). Simmer 20 minutes, mashing some beans for thickness.',
      'Cook rice, season the beans with salt, garnish with cilantro, and serve over rice.',
    ],
  },
  {
    slug: 'greek-gigantes-style-beans',
    title: 'Greek-Style Baked Beans',
    summary: 'Large beans baked in a rich tomato and herb sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 35,
    cuisine: 'Greek',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'pinto_beans_canned', qty: 2, unit: 'can' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'tomato_canned_diced', qty: 2, unit: 'can' },
      { slug: 'oregano_dried', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 3, unit: 'tbsp' },
      { slug: 'feta_cheese', qty: 0.33, unit: 'cup', optional: true },
      { slug: 'parsley', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 375°F (190°C). Heat 2 tbsp oil; soften onion, garlic, and carrot, about 6 minutes.',
      'Stir in diced tomatoes, oregano, and salt; simmer 5 minutes.',
      'Add beans, transfer to a baking dish, drizzle with remaining oil, and bake 25 minutes until bubbling.',
      'Top with feta and parsley before serving.',
    ],
  },
  {
    slug: 'caribbean-rice-and-peas',
    title: 'Caribbean Rice and Peas',
    summary: 'Coconut rice simmered with pinto beans and warm spice.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Caribbean',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'pinto_beans_canned', qty: 1, unit: 'can' },
      { slug: 'white_rice', qty: 1.5, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'coconut_milk', qty: 1, unit: 'can' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'thyme_dried', qty: 1, unit: 'tsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Combine rice, coconut milk, 1 cup water, onion, garlic, thyme, and salt in a pot.',
      'Bring to a boil, then reduce heat, cover, and simmer 15-18 minutes until the rice is tender.',
      'Stir in the beans and warm through. Top with green onion.',
    ],
  },
  {
    slug: 'white-bean-and-kale-soup',
    title: 'White Bean and Kale Soup',
    summary: 'A simple, hearty Tuscan-style bean and greens soup.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Italian',
    difficulty: 1,
    mealSlots: ['lunch', 'dinner'],
    ingredients: [
      { slug: 'pinto_beans_canned', qty: 2, unit: 'can', prepNote: 'or cannellini beans if available' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'kale', qty: 3, unit: 'cup', prepNote: 'chopped' },
      { slug: 'vegetable_broth', qty: 4, unit: 'cup' },
      { slug: 'italian_seasoning', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'parmesan_cheese', qty: 0.33, unit: 'cup', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, and carrot, about 6 minutes.',
      'Add broth, beans, and italian seasoning. Simmer 15 minutes, mashing some beans for body.',
      'Stir in kale and cook 3-4 minutes until wilted.',
      'Season with salt and top with parmesan.',
    ],
  },
  {
    slug: 'refried-bean-tostadas',
    title: 'Refried Bean Tostadas',
    summary: 'Crispy tostadas piled with refried-style beans and fresh toppings.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['lunch', 'dinner'],
    ingredients: [
      { slug: 'pinto_beans_canned', qty: 2, unit: 'can' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'tortilla_corn', qty: 8, unit: 'each' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'lettuce_romaine', qty: 1, unit: 'cup', prepNote: 'shredded' },
      { slug: 'tomato', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'cheddar_cheese', qty: 0.5, unit: 'cup', prepNote: 'shredded' },
      { slug: 'sour_cream', qty: 0.25, unit: 'cup', optional: true },
      { slug: 'salt', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Crisp the tortillas in a dry pan or oven until golden and crunchy.',
      'Heat 1 tbsp oil; sauté garlic, then add beans, cumin, and salt. Mash to a chunky paste, adding a splash of water if needed.',
      'Spread beans on the tostadas and top with lettuce, tomato, cheese, and sour cream.',
    ],
  },
]
