// Beef steak / roast cuts family — sirloin and flank steak.

export const recipes = [
  {
    slug: 'garlic-butter-sirloin-steak',
    title: 'Garlic Butter Sirloin Steak',
    summary: 'Pan-seared sirloin basted in garlic butter, with roasted potatoes.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'American',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'beef_sirloin', qty: 700, unit: 'g' },
      { slug: 'butter', qty: 2, unit: 'tbsp' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'rosemary_dried', qty: 1, unit: 'tsp' },
      { slug: 'potato', qty: 4, unit: 'each' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'salt', qty: 1.5, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 425°F (220°C). Cut potatoes into wedges, toss with olive oil and half the salt, and roast 25-30 minutes, turning once.',
      'Season steak generously with remaining salt and pepper. Let it come to room temperature.',
      'Sear the steak in a hot pan, 3-4 minutes per side for medium-rare.',
      'Add butter, garlic, and rosemary to the pan; tilt and spoon the melted butter over the steak for 1 minute.',
      'Rest the steak 5 minutes, slice against the grain, and serve with the potatoes.',
    ],
  },
  {
    slug: 'beef-fajitas',
    title: 'Steak Fajitas',
    summary: 'Sizzling flank steak and peppers with warm tortillas.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    cuisine: 'Mexican',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'beef_flank_steak', qty: 600, unit: 'g' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each' },
      { slug: 'bell_pepper_green', qty: 1, unit: 'each' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'chili_powder', qty: 1.5, unit: 'tsp' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'garlic_powder', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'tortilla_flour', qty: 8, unit: 'each' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Slice the flank steak thinly against the grain. Toss with chili powder, cumin, garlic powder, salt, and lime juice.',
      'Heat oil in a large skillet over high heat. Sear the steak 2-3 minutes until browned; remove.',
      'Add the peppers and onion to the pan; cook 5-6 minutes until charred at the edges.',
      'Return the steak to the pan, toss together, and warm through.',
      'Serve with warm tortillas.',
    ],
  },
  {
    slug: 'korean-beef-bowl',
    title: 'Korean-Style Beef Bowl',
    summary: 'Thin-sliced beef in a sweet-savory glaze over rice.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 12,
    cuisine: 'Korean',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'beef_sirloin', qty: 600, unit: 'g', prepNote: 'thinly sliced' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 0.25, unit: 'cup' },
      { slug: 'brown_sugar', qty: 2, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tbsp' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'sesame_seeds', qty: 1, unit: 'tsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'julienned' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Whisk garlic, ginger, soy sauce, brown sugar, and sesame oil for the marinade; toss with the sliced beef.',
      'Heat vegetable oil in a hot skillet or wok. Stir-fry the beef in batches, 2-3 minutes each, until browned.',
      'Serve over rice with carrot, sliced green onion, and a sprinkle of sesame seeds.',
    ],
  },
  {
    slug: 'beef-and-vegetable-skewers',
    title: 'Mediterranean Beef Skewers',
    summary: 'Grilled marinated sirloin skewers with lemon and herbs.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 10,
    cuisine: 'Mediterranean',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'beef_sirloin', qty: 600, unit: 'g', prepNote: 'cubed' },
      { slug: 'zucchini', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each', prepNote: 'cubed' },
      { slug: 'red_onion', qty: 1, unit: 'each', prepNote: 'cubed' },
      { slug: 'olive_oil', qty: 3, unit: 'tbsp' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'oregano_dried', qty: 1, unit: 'tsp' },
      { slug: 'couscous', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Whisk olive oil, lemon juice, minced garlic, oregano, and salt. Toss with the beef cubes and marinate 10 minutes.',
      'Thread beef and vegetables onto skewers, alternating.',
      'Cook couscous according to package directions.',
      'Grill or broil the skewers, turning occasionally, about 10 minutes until the beef is cooked to preference.',
      'Serve over couscous.',
    ],
  },
  {
    slug: 'philly-style-beef-skillet',
    title: 'Philly-Style Beef and Pepper Skillet',
    summary: 'Sliced steak with peppers, onions, and melted cheese.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'beef_sirloin', qty: 600, unit: 'g', prepNote: 'thinly sliced' },
      { slug: 'bell_pepper_green', qty: 1, unit: 'each' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'mushroom', qty: 150, unit: 'g' },
      { slug: 'mozzarella_cheese', qty: 0.5, unit: 'cup', prepNote: 'shredded' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'bread_sandwich', qty: 4, unit: 'slice', prepNote: 'or hoagie rolls' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Heat oil in a large skillet over high heat. Sear the steak slices quickly, about 2 minutes; remove.',
      'Add peppers, onion, and mushroom to the pan; cook 6-7 minutes until softened.',
      'Return the beef to the pan, season with salt and pepper, and top with mozzarella until melted.',
      'Serve piled on bread or a toasted roll.',
    ],
  },
]
