// Chicken thigh & breast family. See docs/mealgen.md §5 and the
// calisthenics-recipe-corpus memory: cuisine variety lives in the
// spice/sauce layer (all pantry staples), the shared anchor is the
// perishable protein — so this one family spans Indian, Mexican,
// Chinese, American, and Mediterranean without hurting grocery overlap.

export const recipes = [
  {
    slug: 'chicken-tikka-masala',
    title: 'Chicken Tikka Masala',
    summary: 'Seared chicken thighs simmered in a creamy, spiced tomato sauce.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 30,
    cuisine: 'Indian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'chicken_thigh', qty: 700, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'garam_masala', qty: 2, unit: 'tsp' },
      { slug: 'turmeric', qty: 1, unit: 'tsp' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'tomato_paste', qty: 3, unit: 'tbsp' },
      { slug: 'coconut_milk', qty: 1, unit: 'cup' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked, to serve' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', prepNote: 'chopped, for garnish', optional: true },
    ],
    steps: [
      'Cut chicken thighs into bite-sized pieces and season with salt.',
      'Heat oil in a large pan over medium-high heat. Brown the chicken, about 5 minutes, then set aside.',
      'In the same pan, soften the onion for 4-5 minutes, then add garlic, ginger, garam masala, turmeric, and cumin. Cook 1 minute until fragrant.',
      'Stir in tomato paste, then the coconut milk. Return the chicken to the pan and simmer 15 minutes until cooked through and the sauce thickens.',
      'Meanwhile, cook the rice according to package directions.',
      'Serve the chicken over rice, garnished with cilantro.',
    ],
  },
  {
    slug: 'chicken-fajita-bowl',
    title: 'Chicken Fajita Bowl',
    summary: 'Sizzled chicken and peppers over rice with lime and avocado.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 20,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'chicken_breast', qty: 600, unit: 'g' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each' },
      { slug: 'bell_pepper_green', qty: 1, unit: 'each' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'chili_powder', qty: 1.5, unit: 'tsp' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'garlic_powder', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'avocado', qty: 1, unit: 'each' },
    ],
    steps: [
      'Slice chicken breast and bell peppers into strips.',
      'Toss chicken and peppers with chili powder, cumin, garlic powder, and salt.',
      'Cook rice according to package directions.',
      'Heat oil in a large skillet over high heat. Sauté the onion 2 minutes, add chicken and peppers, and cook 8-10 minutes until the chicken is cooked through and peppers are charred at the edges.',
      'Squeeze lime juice over the pan and serve over rice with sliced avocado.',
    ],
  },
  {
    slug: 'kung-pao-chicken',
    title: 'Kung Pao Chicken',
    summary: 'Stir-fried chicken with peanuts and a sweet-spicy soy glaze.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    cuisine: 'Chinese',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'chicken_thigh', qty: 600, unit: 'g' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'rice_vinegar', qty: 1, unit: 'tbsp' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'cornstarch', qty: 1, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 2, unit: 'tbsp' },
      { slug: 'red_pepper_flakes', qty: 0.5, unit: 'tsp' },
      { slug: 'peanuts_roasted', qty: 0.33, unit: 'cup' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
    ],
    steps: [
      'Cut chicken into bite-sized pieces. Whisk soy sauce, rice vinegar, honey, and cornstarch in a small bowl.',
      'Cook rice according to package directions.',
      'Heat vegetable oil in a wok or large skillet over high heat. Stir-fry the chicken until browned, about 5 minutes, then remove.',
      'Add garlic, ginger, bell pepper, and red pepper flakes; stir-fry 2 minutes.',
      'Return the chicken, pour in the sauce, and toss until it thickens and coats everything, about 2 minutes.',
      'Stir in peanuts and sesame oil, top with sliced green onion, and serve over rice.',
    ],
  },
  {
    slug: 'sheet-pan-bbq-chicken-thighs',
    title: 'Sheet-Pan BBQ Chicken Thighs',
    summary: 'Roasted chicken thighs glazed with BBQ sauce alongside sweet potato.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 35,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'chicken_thigh', qty: 800, unit: 'g', prepNote: 'bone-in or boneless' },
      { slug: 'sweet_potato', qty: 2, unit: 'each' },
      { slug: 'bbq_sauce', qty: 0.33, unit: 'cup' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'smoked_paprika', qty: 1, unit: 'tsp' },
      { slug: 'garlic_powder', qty: 1, unit: 'tsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 425°F (220°C).',
      'Cut sweet potatoes into 1-inch chunks and toss with olive oil, salt, and pepper on a sheet pan.',
      'Season chicken thighs with smoked paprika, garlic powder, salt, and pepper, and place on the same pan.',
      'Roast 20 minutes, then brush the chicken generously with BBQ sauce.',
      'Return to the oven for 10-15 minutes until the chicken reaches 165°F (74°C) internally and the sweet potato is tender.',
    ],
  },
  {
    slug: 'greek-lemon-chicken-with-orzo',
    title: 'Greek Lemon Chicken with Orzo',
    summary: 'Lemon-garlic chicken breast with feta, olives, and orzo.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Mediterranean',
    difficulty: 2,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'chicken_breast', qty: 600, unit: 'g' },
      { slug: 'lemon', qty: 2, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'oregano_dried', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'couscous', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'feta_cheese', qty: 0.5, unit: 'cup', prepNote: 'crumbled' },
      { slug: 'kalamata_olives', qty: 0.33, unit: 'cup' },
      { slug: 'cherry_tomatoes', qty: 1, unit: 'cup', prepNote: 'halved' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Juice one lemon and slice the other. Whisk lemon juice, olive oil, garlic, oregano, salt, and pepper.',
      'Pound chicken breasts to an even thickness and marinate in the lemon mixture for at least 10 minutes.',
      'Cook couscous according to package directions.',
      'Sear the chicken in a hot pan, 5-6 minutes per side, until cooked through. Add lemon slices to the pan for the last 2 minutes.',
      'Toss the couscous with feta, olives, and cherry tomatoes. Slice the chicken and serve on top.',
    ],
  },
  {
    slug: 'chicken-caesar-salad',
    title: 'Chicken Caesar Salad',
    summary: 'Grilled chicken breast over romaine with parmesan and a light dressing.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['lunch'],
    ingredients: [
      { slug: 'chicken_breast', qty: 300, unit: 'g' },
      { slug: 'lettuce_romaine', qty: 4, unit: 'cup', prepNote: 'chopped' },
      { slug: 'parmesan_cheese', qty: 0.25, unit: 'cup', prepNote: 'shaved' },
      { slug: 'panko_breadcrumbs', qty: 0.25, unit: 'cup', prepNote: 'toasted, for croutons' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'lemon', qty: 0.5, unit: 'each' },
      { slug: 'dijon_mustard', qty: 1, unit: 'tsp' },
      { slug: 'mayonnaise', qty: 2, unit: 'tbsp' },
      { slug: 'garlic', qty: 1, unit: 'clove' },
      { slug: 'salt', qty: 0.5, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.25, unit: 'tsp' },
    ],
    steps: [
      'Season chicken breast with salt and pepper; sear in olive oil over medium-high heat, 5-6 minutes per side, until cooked through. Rest, then slice.',
      'Whisk mayonnaise, dijon, lemon juice, and minced garlic for the dressing.',
      'Toss romaine with the dressing, then top with sliced chicken, parmesan, and toasted breadcrumbs.',
    ],
  },
  {
    slug: 'moroccan-spiced-chicken-thighs',
    title: 'Moroccan-Spiced Chicken Thighs',
    summary: 'Warm-spiced chicken thighs braised with chickpeas and tomato.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 35,
    cuisine: 'Moroccan',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'chicken_thigh', qty: 700, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'cinnamon', qty: 0.5, unit: 'tsp' },
      { slug: 'coriander_ground', qty: 1, unit: 'tsp' },
      { slug: 'cayenne_pepper', qty: 0.25, unit: 'tsp' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'chickpeas_canned', qty: 1, unit: 'can' },
      { slug: 'chicken_broth', qty: 0.5, unit: 'cup' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', prepNote: 'chopped, for garnish', optional: true },
    ],
    steps: [
      'Season chicken with salt. Heat oil in a large pot and brown the chicken, about 5 minutes; set aside.',
      'Soften the onion in the same pot, then add garlic, cumin, cinnamon, coriander, and cayenne; cook 1 minute.',
      'Add diced tomatoes, chickpeas, and chicken broth. Return the chicken to the pot.',
      'Cover and simmer 25 minutes until the chicken is cooked through and the sauce has thickened.',
      'Garnish with cilantro and serve.',
    ],
  },
  {
    slug: 'chicken-tortilla-soup',
    title: 'Chicken Tortilla Soup',
    summary: 'Brothy, smoky tomato soup with shredded chicken and crispy tortilla strips.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    cuisine: 'Mexican',
    difficulty: 2,
    mealSlots: ['lunch', 'dinner'],
    ingredients: [
      { slug: 'chicken_breast', qty: 500, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'green_chiles_canned', qty: 1, unit: 'can' },
      { slug: 'chicken_broth', qty: 1, unit: 'can' },
      { slug: 'chili_powder', qty: 1, unit: 'tsp' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'corn', qty: 1, unit: 'cup' },
      { slug: 'black_beans_canned', qty: 1, unit: 'can' },
      { slug: 'tortilla_corn', qty: 2, unit: 'each', prepNote: 'sliced into strips and crisped' },
      { slug: 'avocado', qty: 1, unit: 'each', optional: true },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil in a large pot; soften onion and garlic, about 4 minutes.',
      'Add chicken broth, diced tomatoes, green chiles, chili powder, and cumin. Add the whole chicken breasts.',
      'Simmer 20 minutes until the chicken is cooked through, then shred it with two forks and return to the pot.',
      'Stir in corn and black beans; simmer 5 more minutes. Season with salt and lime juice.',
      'Serve topped with crispy tortilla strips and avocado.',
    ],
  },
  {
    slug: 'chicken-shawarma-bowl',
    title: 'Chicken Shawarma Bowl',
    summary: 'Spiced chicken thighs over rice with a cool yogurt sauce.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 20,
    cuisine: 'Middle Eastern',
    difficulty: 2,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'chicken_thigh', qty: 700, unit: 'g' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'coriander_ground', qty: 1, unit: 'tsp' },
      { slug: 'turmeric', qty: 0.5, unit: 'tsp' },
      { slug: 'cinnamon', qty: 0.25, unit: 'tsp' },
      { slug: 'garlic_powder', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'greek_yogurt', qty: 0.5, unit: 'cup' },
      { slug: 'garlic', qty: 1, unit: 'clove' },
      { slug: 'cucumber', qty: 0.5, unit: 'each', prepNote: 'diced' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Toss chicken thighs with cumin, coriander, turmeric, cinnamon, garlic powder, olive oil, and half the lemon juice. Marinate 10 minutes if time allows.',
      'Cook rice according to package directions.',
      'Whisk yogurt, remaining lemon juice, minced garlic, and diced cucumber for the sauce; season with salt.',
      'Sear the chicken in a hot pan, 6-7 minutes per side, until cooked through and charred at the edges.',
      'Slice the chicken and serve over rice with the yogurt sauce.',
    ],
  },
  {
    slug: 'thai-basil-chicken',
    title: 'Thai Basil Chicken',
    summary: 'Spicy ground-style chicken stir-fry with garlic and basil.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 12,
    cuisine: 'Thai',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'chicken_thigh', qty: 600, unit: 'g', prepNote: 'finely chopped' },
      { slug: 'garlic', qty: 4, unit: 'clove' },
      { slug: 'red_pepper_flakes', qty: 0.5, unit: 'tsp' },
      { slug: 'fish_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 1, unit: 'tbsp' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'basil_fresh', qty: 1, unit: 'cup' },
      { slug: 'vegetable_oil', qty: 2, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'egg', qty: 4, unit: 'each', optional: true, prepNote: 'fried, to top' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Heat oil in a wok; fry garlic and red pepper flakes 30 seconds.',
      'Add chicken and stir-fry until cooked through, about 6-7 minutes.',
      'Stir in fish sauce, soy sauce, and honey; cook 1 minute.',
      'Remove from heat and stir in basil until wilted. Serve over rice, topped with a fried egg if desired.',
    ],
  },
  {
    slug: 'jerk-chicken',
    title: 'Jerk-Spiced Chicken Thighs',
    summary: 'Warm-spiced Caribbean chicken thighs with a sweet heat.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 30,
    cuisine: 'Caribbean',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'chicken_thigh', qty: 700, unit: 'g' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'cinnamon', qty: 0.5, unit: 'tsp' },
      { slug: 'cayenne_pepper', qty: 0.5, unit: 'tsp' },
      { slug: 'thyme_dried', qty: 1, unit: 'tsp' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Whisk lime juice, garlic, ginger, cinnamon, cayenne, thyme, honey, oil, and salt into a marinade. Coat the chicken and marinate at least 15 minutes.',
      'Preheat oven to 400°F (200°C). Roast the chicken 25-30 minutes until cooked through (165°F / 74°C).',
      'Cook rice according to package directions and serve alongside.',
    ],
  },
  {
    slug: 'chicken-provencal',
    title: 'Chicken Provençal',
    summary: 'French-style braised chicken with tomatoes, olives, and herbs.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 35,
    cuisine: 'French',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'chicken_thigh', qty: 700, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'kalamata_olives', qty: 0.33, unit: 'cup' },
      { slug: 'italian_seasoning', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'potato', qty: 3, unit: 'each' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Season chicken with salt. Sear in oil, about 5 minutes, then set aside.',
      'Soften onion and garlic in the same pan, about 5 minutes.',
      'Add diced tomatoes, olives, and italian seasoning. Return the chicken to the pan.',
      'Cover and simmer 25 minutes until the chicken is cooked through.',
      'Boil the potatoes until tender and serve alongside.',
    ],
  },
  {
    slug: 'teriyaki-chicken',
    title: 'Teriyaki Chicken',
    summary: 'Pan-glazed chicken thighs in a simple homemade teriyaki sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'Japanese',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'chicken_thigh', qty: 700, unit: 'g' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'honey', qty: 2, unit: 'tbsp' },
      { slug: 'rice_vinegar', qty: 1, unit: 'tbsp' },
      { slug: 'garlic', qty: 1, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tsp' },
      { slug: 'cornstarch', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'sesame_seeds', qty: 1, unit: 'tsp', optional: true },
    ],
    steps: [
      'Whisk soy sauce, honey, rice vinegar, garlic, ginger, and cornstarch for the sauce.',
      'Cook rice according to package directions.',
      'Sear the chicken in oil, 5-6 minutes per side, until cooked through.',
      'Pour the sauce into the pan and simmer 2 minutes until it thickens and coats the chicken.',
      'Slice and serve over rice, topped with green onion and sesame seeds.',
    ],
  },
]
