// Eggs family — breakfast-heavy, with a few dinner uses too.

export const recipes = [
  {
    slug: 'veggie-omelet',
    title: 'Loaded Veggie Omelet',
    summary: 'A fluffy omelet packed with peppers, spinach, and cheese.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 8,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'egg', qty: 3, unit: 'each' },
      { slug: 'bell_pepper_red', qty: 0.25, unit: 'each', prepNote: 'diced' },
      { slug: 'spinach', qty: 0.5, unit: 'cup' },
      { slug: 'cheddar_cheese', qty: 0.25, unit: 'cup', prepNote: 'shredded' },
      { slug: 'butter', qty: 1, unit: 'tsp' },
      { slug: 'salt', qty: 0.25, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.125, unit: 'tsp' },
    ],
    steps: [
      'Whisk the eggs with salt and pepper.',
      'Melt butter in a nonstick pan over medium heat; sauté bell pepper and spinach 2 minutes until softened.',
      'Pour in the eggs, let set slightly, then sprinkle cheese over half.',
      'Fold the omelet over the cheese and cook 1-2 more minutes until set.',
    ],
  },
  {
    slug: 'shakshuka',
    title: 'Shakshuka',
    summary: 'Eggs poached in a spiced tomato and pepper sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Middle Eastern',
    difficulty: 2,
    mealSlots: ['breakfast', 'dinner'],
    ingredients: [
      { slug: 'egg', qty: 6, unit: 'each' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'smoked_paprika', qty: 1, unit: 'tsp' },
      { slug: 'tomato_canned_diced', qty: 2, unit: 'can' },
      { slug: 'feta_cheese', qty: 0.33, unit: 'cup', optional: true },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'pita_bread', qty: 4, unit: 'each' },
      { slug: 'parsley', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil in a large skillet; soften onion and bell pepper, about 6 minutes.',
      'Add garlic, cumin, and smoked paprika; cook 1 minute.',
      'Add diced tomatoes and salt; simmer uncovered 10 minutes until slightly thickened.',
      'Make wells in the sauce and crack in the eggs. Cover and cook 6-8 minutes until the whites are set but yolks still soft.',
      'Top with feta and parsley, and serve with warm pita.',
    ],
  },
  {
    slug: 'breakfast-burritos',
    title: 'Breakfast Burritos',
    summary: 'Scrambled eggs, cheese, and potatoes wrapped in a warm tortilla.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'egg', qty: 8, unit: 'each' },
      { slug: 'potato', qty: 2, unit: 'each', prepNote: 'diced small' },
      { slug: 'cheddar_cheese', qty: 1, unit: 'cup', prepNote: 'shredded' },
      { slug: 'bell_pepper_green', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'tortilla_flour', qty: 4, unit: 'each' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'salsa', qty: 0.5, unit: 'cup', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil in a skillet; cook diced potato 10-12 minutes until browned and tender.',
      'Add bell pepper and onion; cook 4 more minutes.',
      'Whisk the eggs with salt, pour into the pan, and scramble until just set.',
      'Warm the tortillas, fill with the egg mixture and cheese, and roll up. Serve with salsa.',
    ],
  },
  {
    slug: 'egg-fried-rice',
    title: 'Egg Fried Rice',
    summary: 'Simple, fast fried rice built around scrambled egg.',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 12,
    cuisine: 'Chinese',
    difficulty: 1,
    mealSlots: ['lunch', 'dinner'],
    ingredients: [
      { slug: 'egg', qty: 4, unit: 'each' },
      { slug: 'white_rice', qty: 3, unit: 'cup', prepNote: 'cooked and cooled' },
      { slug: 'peas', qty: 0.5, unit: 'cup' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 2, unit: 'tbsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
    ],
    steps: [
      'Heat 1 tbsp oil; scramble the eggs softly and set aside.',
      'Add remaining oil, sauté garlic, carrot, and peas 2-3 minutes.',
      'Add the rice, breaking up clumps, and stir-fry 4-5 minutes.',
      'Stir in soy sauce, sesame oil, and the scrambled egg. Top with green onion and serve.',
    ],
  },
  {
    slug: 'huevos-rancheros',
    title: 'Huevos Rancheros',
    summary: 'Fried eggs over crispy tortillas with a spiced tomato sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'Mexican',
    difficulty: 2,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'egg', qty: 4, unit: 'each' },
      { slug: 'tortilla_corn', qty: 4, unit: 'each' },
      { slug: 'black_beans_canned', qty: 1, unit: 'can' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'jalapeno', qty: 1, unit: 'each' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'avocado', qty: 1, unit: 'each' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat 1 tbsp oil; soften onion and jalapeño, about 4 minutes. Add diced tomatoes and cumin; simmer 10 minutes.',
      'Warm the black beans in a separate pot.',
      'Lightly crisp the tortillas in a dry pan.',
      'Fry the eggs in remaining oil to your liking.',
      'Layer tortillas, beans, sauce, and a fried egg; top with avocado and cilantro.',
    ],
  },
  {
    slug: 'egg-salad-sandwich',
    title: 'Classic Egg Salad Sandwich',
    summary: 'Creamy egg salad on toasted bread with lettuce.',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 10,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['lunch'],
    ingredients: [
      { slug: 'egg', qty: 5, unit: 'each' },
      { slug: 'mayonnaise', qty: 3, unit: 'tbsp' },
      { slug: 'dijon_mustard', qty: 1, unit: 'tsp' },
      { slug: 'celery', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'bread_sandwich', qty: 4, unit: 'slice' },
      { slug: 'lettuce_romaine', qty: 2, unit: 'each' },
      { slug: 'salt', qty: 0.5, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.25, unit: 'tsp' },
    ],
    steps: [
      'Boil the eggs 10 minutes, cool, peel, and chop.',
      'Mix with mayonnaise, dijon, celery, salt, and pepper.',
      'Toast the bread and build sandwiches with lettuce.',
    ],
  },
  {
    slug: 'spanish-tortilla',
    title: 'Spanish Tortilla',
    summary: 'A thick potato and egg omelet, sliced into wedges.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 25,
    cuisine: 'Spanish',
    difficulty: 2,
    mealSlots: ['breakfast', 'lunch'],
    ingredients: [
      { slug: 'egg', qty: 6, unit: 'each' },
      { slug: 'potato', qty: 3, unit: 'each', prepNote: 'thinly sliced' },
      { slug: 'onion', qty: 1, unit: 'each', prepNote: 'thinly sliced' },
      { slug: 'olive_oil', qty: 4, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil in a nonstick pan; cook potato and onion slices over low-medium heat, 15-18 minutes, until tender but not browned.',
      'Whisk the eggs with salt in a large bowl; drain the potatoes and onions and fold into the eggs.',
      'Pour the mixture back into the pan and cook over low heat 6-8 minutes until mostly set.',
      'Carefully flip (using a plate) and cook 4-5 more minutes. Slice into wedges to serve.',
    ],
  },
  {
    slug: 'egg-and-avocado-toast',
    title: 'Egg and Avocado Toast',
    summary: 'A quick, protein-packed breakfast toast.',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 8,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'egg', qty: 2, unit: 'each' },
      { slug: 'bread_sandwich', qty: 2, unit: 'slice' },
      { slug: 'avocado', qty: 1, unit: 'each' },
      { slug: 'lemon', qty: 0.5, unit: 'each' },
      { slug: 'red_pepper_flakes', qty: 0.125, unit: 'tsp', optional: true },
      { slug: 'salt', qty: 0.5, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.25, unit: 'tsp' },
    ],
    steps: [
      'Toast the bread. Mash the avocado with lemon juice, salt, and pepper; spread on the toast.',
      'Fry or poach the eggs to your liking.',
      'Top the toast with the eggs and a pinch of red pepper flakes.',
    ],
  },
  {
    slug: 'japanese-tamagoyaki',
    title: 'Tamagoyaki (Japanese Rolled Omelet)',
    summary: 'A sweet-savory layered rolled omelet, sliced into pieces.',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 10,
    cuisine: 'Japanese',
    difficulty: 2,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'egg', qty: 4, unit: 'each' },
      { slug: 'soy_sauce', qty: 1, unit: 'tbsp' },
      { slug: 'honey', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
      { slug: 'green_onion', qty: 1, unit: 'each', optional: true },
    ],
    steps: [
      'Whisk eggs, soy sauce, and honey together.',
      'Heat a lightly oiled nonstick pan over medium-low heat. Pour in a thin layer of egg and let set.',
      'Roll the set egg to one side, then pour in more egg, letting it flow under the roll, and roll again.',
      'Repeat until all the egg is used, forming layers. Slice into pieces and garnish with green onion.',
    ],
  },
  {
    slug: 'turkish-menemen',
    title: 'Menemen (Turkish Scrambled Eggs)',
    summary: 'Soft scrambled eggs cooked into a spiced tomato and pepper base.',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 15,
    cuisine: 'Turkish',
    difficulty: 1,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'egg', qty: 4, unit: 'each' },
      { slug: 'tomato', qty: 2, unit: 'each', prepNote: 'diced' },
      { slug: 'bell_pepper_green', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'red_pepper_flakes', qty: 0.25, unit: 'tsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'feta_cheese', qty: 0.25, unit: 'cup', optional: true },
      { slug: 'bread_sandwich', qty: 4, unit: 'slice', optional: true },
      { slug: 'salt', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion and bell pepper, about 5 minutes.',
      'Add tomato and red pepper flakes; cook 8-10 minutes until the tomato breaks down.',
      'Whisk the eggs with salt and pour into the pan; stir gently until softly scrambled into the vegetables.',
      'Top with feta and serve with bread.',
    ],
  },
  {
    slug: 'italian-frittata',
    title: 'Italian Vegetable Frittata',
    summary: 'A baked egg dish loaded with vegetables and parmesan.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'Italian',
    difficulty: 2,
    mealSlots: ['breakfast', 'lunch'],
    ingredients: [
      { slug: 'egg', qty: 8, unit: 'each' },
      { slug: 'zucchini', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'cherry_tomatoes', qty: 1, unit: 'cup' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'parmesan_cheese', qty: 0.33, unit: 'cup', prepNote: 'grated' },
      { slug: 'basil_fresh', qty: 0.25, unit: 'cup' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 375°F (190°C). Heat oil in an oven-safe skillet; soften onion and zucchini, about 6 minutes.',
      'Whisk eggs with salt and parmesan; pour into the pan over the vegetables. Scatter cherry tomatoes on top.',
      'Cook on the stovetop 2-3 minutes until the edges set, then transfer to the oven and bake 12-15 minutes until fully set.',
      'Top with fresh basil and slice into wedges.',
    ],
  },
  {
    slug: 'korean-gyeranmari',
    title: 'Gyeranmari (Korean Rolled Omelet)',
    summary: 'A savory Korean rolled omelet with finely diced vegetables.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 10,
    cuisine: 'Korean',
    difficulty: 2,
    mealSlots: ['breakfast', 'lunch'],
    ingredients: [
      { slug: 'egg', qty: 4, unit: 'each' },
      { slug: 'carrot', qty: 0.5, unit: 'each', prepNote: 'finely diced' },
      { slug: 'green_onion', qty: 2, unit: 'each', prepNote: 'finely sliced' },
      { slug: 'salt', qty: 0.25, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked', optional: true },
    ],
    steps: [
      'Whisk eggs with salt, carrot, and green onion.',
      'Heat a lightly oiled nonstick pan over medium-low heat. Pour in a thin layer and let set.',
      'Roll to one side, add more egg mixture, and roll again, building layers.',
      'Slice into rounds and serve, with rice on the side if desired.',
    ],
  },
  {
    slug: 'chilaquiles',
    title: 'Chilaquiles',
    summary: 'Crisp tortilla chips simmered in salsa and topped with fried eggs.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'egg', qty: 4, unit: 'each' },
      { slug: 'tortilla_corn', qty: 10, unit: 'each', prepNote: 'cut into wedges and crisped, or use chips' },
      { slug: 'salsa', qty: 1.5, unit: 'cup' },
      { slug: 'cheddar_cheese', qty: 0.5, unit: 'cup', prepNote: 'shredded' },
      { slug: 'onion', qty: 0.25, unit: 'each' },
      { slug: 'sour_cream', qty: 0.25, unit: 'cup', optional: true },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
    ],
    steps: [
      'Warm the salsa in a large skillet. Add the crisped tortilla chips and toss gently to coat, cooking 2-3 minutes.',
      'Top with cheese and cover briefly until melted.',
      'Fry the eggs in oil in a separate pan.',
      'Top the chilaquiles with fried eggs, onion, sour cream, and cilantro.',
    ],
  },
  {
    slug: 'egg-drop-soup',
    title: 'Egg Drop Soup',
    summary: 'A simple, silky Chinese soup of ribboned egg in savory broth.',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 10,
    cuisine: 'Chinese',
    difficulty: 1,
    mealSlots: ['lunch'],
    ingredients: [
      { slug: 'egg', qty: 3, unit: 'each' },
      { slug: 'chicken_broth', qty: 2, unit: 'can' },
      { slug: 'cornstarch', qty: 2, unit: 'tbsp' },
      { slug: 'ginger', qty: 1, unit: 'tsp' },
      { slug: 'soy_sauce', qty: 1, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
    ],
    steps: [
      'Bring broth to a simmer with ginger and soy sauce.',
      'Mix cornstarch with a little water and stir into the broth to thicken slightly.',
      'Whisk the eggs, then slowly drizzle into the simmering broth while stirring gently to form ribbons.',
      'Finish with sesame oil and green onion.',
    ],
  },
  {
    slug: 'deviled-eggs',
    title: 'Classic Deviled Eggs',
    summary: 'Creamy, tangy deviled eggs — a great high-protein snack.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 10,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['snack', 'lunch'],
    ingredients: [
      { slug: 'egg', qty: 6, unit: 'each' },
      { slug: 'mayonnaise', qty: 3, unit: 'tbsp' },
      { slug: 'dijon_mustard', qty: 1, unit: 'tsp' },
      { slug: 'paprika', qty: 0.25, unit: 'tsp' },
      { slug: 'salt', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Boil the eggs 10 minutes, cool, and peel. Halve lengthwise and remove yolks.',
      'Mash the yolks with mayonnaise, dijon, and salt.',
      'Pipe or spoon the filling back into the egg whites, and dust with paprika.',
    ],
  },
]
