// Salmon & white fish family.

export const recipes = [
  {
    slug: 'miso-glazed-salmon',
    title: 'Miso-Glazed Salmon',
    summary: 'Broiled salmon with a sweet-savory miso glaze.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Japanese',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'salmon_fillet', qty: 680, unit: 'g' },
      { slug: 'soy_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'honey', qty: 2, unit: 'tbsp' },
      { slug: 'rice_vinegar', qty: 1, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'ginger', qty: 1, unit: 'tsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'broccoli', qty: 300, unit: 'g' },
      { slug: 'sesame_seeds', qty: 1, unit: 'tsp', optional: true },
    ],
    steps: [
      'Whisk soy sauce, honey, rice vinegar, sesame oil, and ginger. Marinate the salmon 10 minutes.',
      'Cook rice according to package directions; steam the broccoli.',
      'Broil the salmon 8-10 minutes until it flakes easily, brushing with extra glaze halfway.',
      'Serve over rice with broccoli, sprinkled with sesame seeds.',
    ],
  },
  {
    slug: 'blackened-fish-tacos',
    title: 'Blackened Fish Tacos',
    summary: 'Spiced pan-seared cod in warm tortillas with lime slaw.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 10,
    cuisine: 'Mexican',
    difficulty: 2,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'cod_fillet', qty: 600, unit: 'g' },
      { slug: 'chili_powder', qty: 1, unit: 'tsp' },
      { slug: 'smoked_paprika', qty: 1, unit: 'tsp' },
      { slug: 'cumin', qty: 0.5, unit: 'tsp' },
      { slug: 'cabbage', qty: 0.25, unit: 'each', prepNote: 'shredded' },
      { slug: 'lime', qty: 2, unit: 'each' },
      { slug: 'mayonnaise', qty: 2, unit: 'tbsp' },
      { slug: 'tortilla_corn', qty: 8, unit: 'each' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Toss shredded cabbage with mayonnaise and half the lime juice for the slaw.',
      'Season the cod with chili powder, smoked paprika, cumin, and salt.',
      'Sear in oil over medium-high heat, 3-4 minutes per side, until it flakes easily. Break into large pieces.',
      'Warm the tortillas and fill with fish and slaw. Top with cilantro and remaining lime.',
    ],
  },
  {
    slug: 'lemon-butter-tilapia',
    title: 'Lemon Butter Tilapia',
    summary: 'Pan-seared tilapia in a bright lemon-butter sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'tilapia_fillet', qty: 560, unit: 'g' },
      { slug: 'butter', qty: 2, unit: 'tbsp' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'parsley', qty: 2, unit: 'tbsp' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'asparagus', qty: 12, unit: 'each' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Season tilapia with salt and pepper. Sear in oil, 3 minutes per side, until it flakes easily; remove.',
      'Add butter and garlic to the pan; once foaming, add lemon juice and parsley.',
      'Steam or roast the asparagus until tender, about 6-8 minutes.',
      'Spoon the lemon-butter sauce over the fish and serve with asparagus.',
    ],
  },
  {
    slug: 'salmon-poke-bowl',
    title: 'Salmon Poke Bowl',
    summary: 'Marinated raw-style salmon over rice with fresh vegetables (or seared, if preferred).',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 0,
    cuisine: 'Hawaiian',
    difficulty: 2,
    mealSlots: ['lunch', 'dinner'],
    ingredients: [
      { slug: 'salmon_fillet', qty: 600, unit: 'g', prepNote: 'sushi-grade, cubed, or seared and cubed' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'sesame_seeds', qty: 1, unit: 'tsp' },
      { slug: 'white_rice', qty: 1.5, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'cucumber', qty: 0.5, unit: 'each', prepNote: 'diced' },
      { slug: 'avocado', qty: 1, unit: 'each' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'julienned' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Toss the cubed salmon with soy sauce, sesame oil, and half the green onion; marinate 10 minutes.',
      'Divide rice into bowls and top with the salmon, cucumber, avocado, and carrot.',
      'Garnish with remaining green onion and sesame seeds.',
    ],
  },
  {
    slug: 'mediterranean-baked-cod',
    title: 'Mediterranean Baked Cod',
    summary: 'Cod baked with tomatoes, olives, and feta.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'Mediterranean',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'cod_fillet', qty: 600, unit: 'g' },
      { slug: 'cherry_tomatoes', qty: 2, unit: 'cup' },
      { slug: 'kalamata_olives', qty: 0.33, unit: 'cup' },
      { slug: 'feta_cheese', qty: 0.5, unit: 'cup', prepNote: 'crumbled' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'oregano_dried', qty: 1, unit: 'tsp' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'couscous', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 400°F (200°C). Place cod in a baking dish and surround with cherry tomatoes, olives, and garlic.',
      'Drizzle with olive oil, oregano, salt, and lemon juice.',
      'Bake 18-20 minutes until the fish flakes easily. Top with feta in the last 3 minutes.',
      'Cook couscous according to package directions and serve alongside.',
    ],
  },
  {
    slug: 'salmon-teriyaki',
    title: 'Salmon Teriyaki',
    summary: 'Pan-glazed salmon in a homemade teriyaki sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Japanese',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'salmon_fillet', qty: 680, unit: 'g' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'honey', qty: 2, unit: 'tbsp' },
      { slug: 'rice_vinegar', qty: 1, unit: 'tbsp' },
      { slug: 'garlic', qty: 1, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tsp' },
      { slug: 'cornstarch', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'green_beans', qty: 250, unit: 'g' },
    ],
    steps: [
      'Whisk soy sauce, honey, rice vinegar, garlic, ginger, and cornstarch for the sauce.',
      'Cook rice and steam the green beans.',
      'Sear the salmon skin-side down in oil, 4 minutes, then flip and cook 3 more minutes.',
      'Pour the sauce into the pan and simmer 1-2 minutes until it thickens and coats the salmon.',
      'Serve over rice with green beans.',
    ],
  },
  {
    slug: 'fish-curry',
    title: 'Coconut Fish Curry',
    summary: 'Flaky white fish simmered in a fragrant coconut curry sauce.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 20,
    cuisine: 'Indian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'tilapia_fillet', qty: 600, unit: 'g', prepNote: 'cut into chunks' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'curry_powder', qty: 2, unit: 'tsp' },
      { slug: 'turmeric', qty: 0.5, unit: 'tsp' },
      { slug: 'coconut_milk', qty: 1, unit: 'can' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, and ginger, about 5 minutes.',
      'Stir in curry powder and turmeric; cook 1 minute.',
      'Add coconut milk and diced tomatoes; simmer 10 minutes.',
      'Add the fish and simmer gently 8-10 minutes until cooked through and flaking.',
      'Cook rice according to package directions. Season the curry with salt, garnish with cilantro, and serve over rice.',
    ],
  },
  {
    slug: 'salmon-and-avocado-salad',
    title: 'Seared Salmon and Avocado Salad',
    summary: 'A light, high-protein lunch salad with citrus dressing.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 10,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['lunch'],
    ingredients: [
      { slug: 'salmon_fillet', qty: 340, unit: 'g' },
      { slug: 'lettuce_romaine', qty: 4, unit: 'cup', prepNote: 'chopped' },
      { slug: 'avocado', qty: 1, unit: 'each' },
      { slug: 'cherry_tomatoes', qty: 1, unit: 'cup' },
      { slug: 'cucumber', qty: 0.5, unit: 'each' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'salt', qty: 0.5, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.25, unit: 'tsp' },
    ],
    steps: [
      'Season salmon with salt and pepper; sear in a little oil, 4 minutes per side, until it flakes easily.',
      'Whisk remaining olive oil with lemon juice for the dressing.',
      'Toss the romaine, avocado, tomatoes, and cucumber with the dressing.',
      'Top with the flaked or whole seared salmon.',
    ],
  },
]
