// Salmon & white fish family.

export const recipes = [
  {
    slug: 'miso-glazed-salmon',
    title: 'Miso-Glazed Salmon',
    summary: 'Broiled salmon with a sweet-savory miso glaze.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Japanese',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'salmon_fillet', qty: 680, unit: 'g' },
      { slug: 'soy_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'honey', qty: 2, unit: 'tbsp' },
      { slug: 'rice_vinegar', qty: 1, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'ginger', qty: 1, unit: 'tsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'broccoli', qty: 300, unit: 'g' },
      { slug: 'sesame_seeds', qty: 1, unit: 'tsp', optional: true },
    ],
    steps: [
      'Whisk soy sauce, honey, rice vinegar, sesame oil, and ginger. Marinate the salmon 10 minutes.',
      'Cook rice according to package directions; steam the broccoli.',
      'Broil the salmon 8-10 minutes until it flakes easily, brushing with extra glaze halfway.',
      'Serve over rice with broccoli, sprinkled with sesame seeds.',
    ],
  },
  {
    slug: 'blackened-fish-tacos',
    title: 'Blackened Fish Tacos',
    summary: 'Spiced pan-seared cod in warm tortillas with lime slaw.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 10,
    cuisine: 'Mexican',
    difficulty: 2,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'cod_fillet', qty: 600, unit: 'g' },
      { slug: 'chili_powder', qty: 1, unit: 'tsp' },
      { slug: 'smoked_paprika', qty: 1, unit: 'tsp' },
      { slug: 'cumin', qty: 0.5, unit: 'tsp' },
      { slug: 'cabbage', qty: 0.25, unit: 'each', prepNote: 'shredded' },
      { slug: 'lime', qty: 2, unit: 'each' },
      { slug: 'mayonnaise', qty: 2, unit: 'tbsp' },
      { slug: 'tortilla_corn', qty: 8, unit: 'each' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Toss shredded cabbage with mayonnaise and half the lime juice for the slaw.',
      'Season the cod with chili powder, smoked paprika, cumin, and salt.',
      'Sear in oil over medium-high heat, 3-4 minutes per side, until it flakes easily. Break into large pieces.',
      'Warm the tortillas and fill with fish and slaw. Top with cilantro and remaining lime.',
    ],
  },
  {
    slug: 'lemon-butter-tilapia',
    title: 'Lemon Butter Tilapia',
    summary: 'Pan-seared tilapia in a bright lemon-butter sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'tilapia_fillet', qty: 560, unit: 'g' },
      { slug: 'butter', qty: 2, unit: 'tbsp' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'parsley', qty: 2, unit: 'tbsp' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'asparagus', qty: 12, unit: 'each' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Season tilapia with salt and pepper. Sear in oil, 3 minutes per side, until it flakes easily; remove.',
      'Add butter and garlic to the pan; once foaming, add lemon juice and parsley.',
      'Steam or roast the asparagus until tender, about 6-8 minutes.',
      'Spoon the lemon-butter sauce over the fish and serve with asparagus.',
    ],
  },
  {
    slug: 'salmon-poke-bowl',
    title: 'Salmon Poke Bowl',
    summary: 'Marinated raw-style salmon over rice with fresh vegetables (or seared, if preferred).',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 0,
    cuisine: 'Hawaiian',
    difficulty: 2,
    mealSlots: ['lunch', 'dinner'],
    ingredients: [
      { slug: 'salmon_fillet', qty: 600, unit: 'g', prepNote: 'sushi-grade, cubed, or seared and cubed' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'sesame_seeds', qty: 1, unit: 'tsp' },
      { slug: 'white_rice', qty: 1.5, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'cucumber', qty: 0.5, unit: 'each', prepNote: 'diced' },
      { slug: 'avocado', qty: 1, unit: 'each' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'julienned' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Toss the cubed salmon with soy sauce, sesame oil, and half the green onion; marinate 10 minutes.',
      'Divide rice into bowls and top with the salmon, cucumber, avocado, and carrot.',
      'Garnish with remaining green onion and sesame seeds.',
    ],
  },
  {
    slug: 'mediterranean-baked-cod',
    title: 'Mediterranean Baked Cod',
    summary: 'Cod baked with tomatoes, olives, and feta.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'Mediterranean',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'cod_fillet', qty: 600, unit: 'g' },
      { slug: 'cherry_tomatoes', qty: 2, unit: 'cup' },
      { slug: 'kalamata_olives', qty: 0.33, unit: 'cup' },
      { slug: 'feta_cheese', qty: 0.5, unit: 'cup', prepNote: 'crumbled' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'oregano_dried', qty: 1, unit: 'tsp' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'couscous', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 400°F (200°C). Place cod in a baking dish and surround with cherry tomatoes, olives, and garlic.',
      'Drizzle with olive oil, oregano, salt, and lemon juice.',
      'Bake 18-20 minutes until the fish flakes easily. Top with feta in the last 3 minutes.',
      'Cook couscous according to package directions and serve alongside.',
    ],
  },
  {
    slug: 'salmon-teriyaki',
    title: 'Salmon Teriyaki',
    summary: 'Pan-glazed salmon in a homemade teriyaki sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Japanese',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'salmon_fillet', qty: 680, unit: 'g' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'honey', qty: 2, unit: 'tbsp' },
      { slug: 'rice_vinegar', qty: 1, unit: 'tbsp' },
      { slug: 'garlic', qty: 1, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tsp' },
      { slug: 'cornstarch', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'green_beans', qty: 250, unit: 'g' },
    ],
    steps: [
      'Whisk soy sauce, honey, rice vinegar, garlic, ginger, and cornstarch for the sauce.',
      'Cook rice and steam the green beans.',
      'Sear the salmon skin-side down in oil, 4 minutes, then flip and cook 3 more minutes.',
      'Pour the sauce into the pan and simmer 1-2 minutes until it thickens and coats the salmon.',
      'Serve over rice with green beans.',
    ],
  },
  {
    slug: 'fish-curry',
    title: 'Coconut Fish Curry',
    summary: 'Flaky white fish simmered in a fragrant coconut curry sauce.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 20,
    cuisine: 'Indian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'tilapia_fillet', qty: 600, unit: 'g', prepNote: 'cut into chunks' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'curry_powder', qty: 2, unit: 'tsp' },
      { slug: 'turmeric', qty: 0.5, unit: 'tsp' },
      { slug: 'coconut_milk', qty: 1, unit: 'can' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, and ginger, about 5 minutes.',
      'Stir in curry powder and turmeric; cook 1 minute.',
      'Add coconut milk and diced tomatoes; simmer 10 minutes.',
      'Add the fish and simmer gently 8-10 minutes until cooked through and flaking.',
      'Cook rice according to package directions. Season the curry with salt, garnish with cilantro, and serve over rice.',
    ],
  },
  {
    slug: 'salmon-and-avocado-salad',
    title: 'Seared Salmon and Avocado Salad',
    summary: 'A light, high-protein lunch salad with citrus dressing.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 10,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['lunch'],
    ingredients: [
      { slug: 'salmon_fillet', qty: 340, unit: 'g' },
      { slug: 'lettuce_romaine', qty: 4, unit: 'cup', prepNote: 'chopped' },
      { slug: 'avocado', qty: 1, unit: 'each' },
      { slug: 'cherry_tomatoes', qty: 1, unit: 'cup' },
      { slug: 'cucumber', qty: 0.5, unit: 'each' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'salt', qty: 0.5, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.25, unit: 'tsp' },
    ],
    steps: [
      'Season salmon with salt and pepper; sear in a little oil, 4 minutes per side, until it flakes easily.',
      'Whisk remaining olive oil with lemon juice for the dressing.',
      'Toss the romaine, avocado, tomatoes, and cucumber with the dressing.',
      'Top with the flaked or whole seared salmon.',
    ],
  },
  {
    slug: 'peruvian-ceviche',
    title: 'Peruvian-Style Ceviche',
    summary: 'Citrus-cured white fish with red onion and cilantro.',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 0,
    cuisine: 'Peruvian',
    difficulty: 2,
    mealSlots: ['lunch'],
    ingredients: [
      { slug: 'cod_fillet', qty: 500, unit: 'g', prepNote: 'very fresh, cubed small' },
      { slug: 'lime', qty: 5, unit: 'each' },
      { slug: 'red_onion', qty: 0.5, unit: 'each', prepNote: 'thinly sliced' },
      { slug: 'jalapeno', qty: 1, unit: 'each', prepNote: 'thinly sliced' },
      { slug: 'cilantro', qty: 0.25, unit: 'cup' },
      { slug: 'sweet_potato', qty: 1, unit: 'each', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Combine the cubed fish with lime juice, ensuring it is fully submerged. Refrigerate 15-20 minutes until opaque throughout ("cooked" by the acid).',
      'Stir in red onion, jalapeño, cilantro, and salt.',
      'If using, boil the sweet potato until tender and serve alongside.',
    ],
  },
  {
    slug: 'chinese-steamed-fish',
    title: 'Chinese-Style Steamed Fish',
    summary: 'Delicate steamed fish with ginger, scallion, and hot soy-sesame oil.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'Chinese',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'tilapia_fillet', qty: 600, unit: 'g' },
      { slug: 'ginger', qty: 2, unit: 'tbsp', prepNote: 'julienned' },
      { slug: 'green_onion', qty: 3, unit: 'each', prepNote: 'julienned' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tbsp' },
      { slug: 'vegetable_oil', qty: 2, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Place the fish on a heatproof plate and scatter half the ginger over it. Steam 10-12 minutes until it flakes easily.',
      'Top the cooked fish with remaining ginger and green onion; drizzle with soy sauce.',
      'Heat vegetable oil and sesame oil until just smoking, then carefully pour over the fish (it will sizzle). Serve over rice.',
    ],
  },
  {
    slug: 'portuguese-fish-stew',
    title: 'Portuguese-Style Fish Stew',
    summary: 'A brothy tomato stew with cod, peppers, and paprika.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Portuguese',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'cod_fillet', qty: 600, unit: 'g', prepNote: 'cut into chunks' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each' },
      { slug: 'smoked_paprika', qty: 1, unit: 'tsp' },
      { slug: 'tomato_canned_diced', qty: 2, unit: 'can' },
      { slug: 'potato', qty: 2, unit: 'each', prepNote: 'cubed' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'parsley', qty: 2, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, and bell pepper, about 6 minutes.',
      'Add smoked paprika, diced tomatoes, potato, and 1 cup water. Simmer 15 minutes until the potato is nearly tender.',
      'Add the fish and simmer gently 8-10 minutes until it flakes easily.',
      'Season with salt, top with parsley, and serve.',
    ],
  },
  {
    slug: 'thai-fish-cakes',
    title: 'Thai Fish Cakes',
    summary: 'Pan-fried patties of minced fish with red curry and lime.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 12,
    cuisine: 'Thai',
    difficulty: 2,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'tilapia_fillet', qty: 500, unit: 'g', prepNote: 'finely chopped or minced' },
      { slug: 'curry_paste', qty: 2, unit: 'tbsp' },
      { slug: 'egg', qty: 1, unit: 'each' },
      { slug: 'fish_sauce', qty: 1, unit: 'tbsp' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'green_beans', qty: 100, unit: 'g', prepNote: 'finely sliced' },
      { slug: 'vegetable_oil', qty: 3, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
    ],
    steps: [
      'Mix the minced fish with curry paste, egg, and fish sauce until sticky. Fold in green beans.',
      'Shape into small patties.',
      'Pan-fry in oil, 3-4 minutes per side, until cooked through and golden.',
      'Cook rice and serve the fish cakes with lime wedges.',
    ],
  },
  {
    slug: 'salmon-burgers',
    title: 'Salmon Burgers',
    summary: 'Pan-seared homemade salmon patties with a lemon-dill flavor.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 10,
    cuisine: 'American',
    difficulty: 2,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'salmon_fillet', qty: 500, unit: 'g', prepNote: 'finely chopped' },
      { slug: 'panko_breadcrumbs', qty: 0.33, unit: 'cup' },
      { slug: 'egg', qty: 1, unit: 'each' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'dijon_mustard', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'bread_sandwich', qty: 4, unit: 'slice' },
      { slug: 'lettuce_romaine', qty: 4, unit: 'each' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Mix chopped salmon with breadcrumbs, egg, lemon juice, dijon, and salt; form into 4 patties.',
      'Sear in oil, 4 minutes per side, until golden and cooked through.',
      'Toast the bread and build burgers with lettuce.',
    ],
  },
  {
    slug: 'baked-salmon-with-asparagus',
    title: 'Sheet-Pan Baked Salmon with Asparagus',
    summary: 'An easy one-pan dinner of roasted salmon and asparagus.',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 15,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'salmon_fillet', qty: 680, unit: 'g' },
      { slug: 'asparagus', qty: 16, unit: 'each' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'garlic_powder', qty: 1, unit: 'tsp' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 400°F (200°C). Arrange salmon and asparagus on a sheet pan.',
      'Drizzle with oil, season with garlic powder, salt, and pepper.',
      'Roast 12-15 minutes until the salmon flakes easily and asparagus is tender.',
      'Finish with a squeeze of lemon.',
    ],
  },
  {
    slug: 'fish-and-chips',
    title: 'Baked Fish and Chips',
    summary: 'Crispy oven-baked breaded cod with seasoned potato wedges.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 30,
    cuisine: 'British',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'cod_fillet', qty: 600, unit: 'g' },
      { slug: 'all_purpose_flour', qty: 0.5, unit: 'cup' },
      { slug: 'egg', qty: 2, unit: 'each' },
      { slug: 'panko_breadcrumbs', qty: 1, unit: 'cup' },
      { slug: 'potato', qty: 4, unit: 'each', prepNote: 'cut into wedges' },
      { slug: 'olive_oil', qty: 3, unit: 'tbsp' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 425°F (220°C). Toss potato wedges with 2 tbsp oil and half the salt; roast 20 minutes.',
      'Dredge the cod in flour, then egg, then breadcrumbs.',
      'Place the fish on a lined tray, drizzle with remaining oil, and bake 15 minutes alongside the potatoes until golden and flaking.',
      'Serve with lemon wedges.',
    ],
  },
  {
    slug: 'tilapia-veracruz',
    title: 'Tilapia Veracruz-Style',
    summary: 'Fish simmered in a tomato, olive, and jalapeño sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'Mexican',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'tilapia_fillet', qty: 600, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'tomato_canned_diced', qty: 2, unit: 'can' },
      { slug: 'kalamata_olives', qty: 0.33, unit: 'cup' },
      { slug: 'jalapeno', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion and garlic, about 5 minutes.',
      'Add diced tomatoes, olives, and jalapeño; simmer 10 minutes.',
      'Add the fish and simmer gently 8-10 minutes until it flakes easily.',
      'Season with salt. Cook rice and serve the fish and sauce over it.',
    ],
  },
]
