// Ground turkey family — leaner alternative to beef, spans similar cuisines.

export const recipes = [
  {
    slug: 'turkey-taco-lettuce-cups',
    title: 'Turkey Taco Lettuce Cups',
    summary: 'Lean seasoned turkey in crisp lettuce cups with pico toppings.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'ground_turkey', qty: 500, unit: 'g' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'taco_seasoning', qty: 2, unit: 'tbsp' },
      { slug: 'lettuce_romaine', qty: 8, unit: 'each' },
      { slug: 'tomato', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'avocado', qty: 1, unit: 'each' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'cheddar_cheese', qty: 0.33, unit: 'cup', prepNote: 'shredded', optional: true },
    ],
    steps: [
      'Cook ground turkey and onion in a skillet over medium-high heat until browned, about 8 minutes.',
      'Add taco seasoning and a splash of water; simmer 2 minutes.',
      'Spoon into lettuce cups and top with tomato, avocado, cheddar, and a squeeze of lime.',
    ],
  },
  {
    slug: 'turkey-bolognese',
    title: 'Turkey Bolognese',
    summary: 'A lighter take on bolognese using ground turkey.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    cuisine: 'Italian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_turkey', qty: 500, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'tomato_canned_diced', qty: 2, unit: 'can' },
      { slug: 'tomato_paste', qty: 2, unit: 'tbsp' },
      { slug: 'italian_seasoning', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'pasta_penne', qty: 340, unit: 'g' },
      { slug: 'parmesan_cheese', qty: 0.5, unit: 'cup', prepNote: 'grated' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, and carrot, about 5 minutes.',
      'Add ground turkey, cook until no longer pink, breaking it up as it cooks.',
      'Stir in tomato paste, diced tomatoes, italian seasoning, and salt. Simmer 20 minutes.',
      'Cook pasta according to package directions and toss with the sauce.',
      'Serve topped with parmesan.',
    ],
  },
  {
    slug: 'turkey-meatballs-with-marinara',
    title: 'Turkey Meatballs with Marinara',
    summary: 'Baked turkey meatballs simmered in tomato sauce.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 25,
    cuisine: 'Italian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_turkey', qty: 500, unit: 'g' },
      { slug: 'panko_breadcrumbs', qty: 0.33, unit: 'cup' },
      { slug: 'egg', qty: 1, unit: 'each' },
      { slug: 'parmesan_cheese', qty: 0.25, unit: 'cup', prepNote: 'grated' },
      { slug: 'garlic_powder', qty: 1, unit: 'tsp' },
      { slug: 'italian_seasoning', qty: 1, unit: 'tsp' },
      { slug: 'tomato_canned_diced', qty: 2, unit: 'can' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'spaghetti', qty: 300, unit: 'g' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 400°F (200°C). Mix turkey, breadcrumbs, egg, parmesan, garlic powder, and half the italian seasoning; form into 16 meatballs.',
      'Bake meatballs 18-20 minutes until cooked through.',
      'Meanwhile, heat oil, sauté garlic, then add diced tomatoes, remaining italian seasoning, and salt; simmer 15 minutes.',
      'Cook spaghetti according to package directions.',
      'Add the meatballs to the sauce and serve over spaghetti.',
    ],
  },
  {
    slug: 'turkey-and-veggie-stir-fry',
    title: 'Turkey and Vegetable Stir-Fry',
    summary: 'Quick weeknight stir-fry with ground turkey and crisp vegetables.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Chinese',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_turkey', qty: 500, unit: 'g' },
      { slug: 'broccoli', qty: 300, unit: 'g' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Heat vegetable oil in a large skillet or wok. Brown the turkey, about 6 minutes.',
      'Add broccoli, carrot, garlic, and ginger; stir-fry 4-5 minutes until vegetables are crisp-tender.',
      'Stir in soy sauce and sesame oil, and serve over rice.',
    ],
  },
  {
    slug: 'turkey-chili-verde',
    title: 'Turkey Chili Verde',
    summary: 'Ground turkey chili with green chiles and white beans.',
    servings: 6,
    prepMinutes: 10,
    cookMinutes: 35,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'ground_turkey', qty: 700, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'green_chiles_canned', qty: 2, unit: 'can' },
      { slug: 'chicken_broth', qty: 1, unit: 'can' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'oregano_dried', qty: 1, unit: 'tsp' },
      { slug: 'pinto_beans_canned', qty: 2, unit: 'can' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'salt', qty: 1.5, unit: 'tsp' },
    ],
    steps: [
      'Heat oil in a large pot; soften onion and garlic, about 5 minutes.',
      'Add ground turkey and cook until no longer pink.',
      'Stir in green chiles, broth, cumin, and oregano. Simmer uncovered 25 minutes.',
      'Add pinto beans, simmer 5 more minutes, then finish with lime juice and salt.',
    ],
  },
  {
    slug: 'turkey-burgers-with-avocado',
    title: 'Turkey Burgers with Avocado',
    summary: 'Juicy turkey burgers topped with avocado and a light spread.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'ground_turkey', qty: 600, unit: 'g' },
      { slug: 'garlic_powder', qty: 1, unit: 'tsp' },
      { slug: 'onion_powder', qty: 1, unit: 'tsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
      { slug: 'bread_sandwich', qty: 4, unit: 'slice' },
      { slug: 'avocado', qty: 1, unit: 'each' },
      { slug: 'lettuce_romaine', qty: 4, unit: 'each' },
      { slug: 'tomato', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
    ],
    steps: [
      'Mix ground turkey with garlic powder, onion powder, salt, and pepper; shape into 4 patties.',
      'Heat oil in a skillet; cook patties 5-6 minutes per side until cooked through (165°F / 74°C).',
      'Toast the bread lightly.',
      'Build the burgers with mashed avocado, lettuce, and tomato.',
    ],
  },
  {
    slug: 'turkey-stuffed-sweet-potatoes',
    title: 'Turkey-Stuffed Sweet Potatoes',
    summary: 'Baked sweet potatoes topped with spiced turkey and black beans.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 45,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'sweet_potato', qty: 4, unit: 'each' },
      { slug: 'ground_turkey', qty: 500, unit: 'g' },
      { slug: 'black_beans_canned', qty: 1, unit: 'can' },
      { slug: 'chili_powder', qty: 1, unit: 'tsp' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'greek_yogurt', qty: 0.5, unit: 'cup', prepNote: 'to top' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 400°F (200°C). Pierce sweet potatoes and bake 40-45 minutes until tender.',
      'Meanwhile, brown the turkey in oil, about 7 minutes, then stir in chili powder, cumin, salt, and black beans; simmer 5 minutes.',
      'Split the sweet potatoes open and top with the turkey mixture, yogurt, and green onion.',
    ],
  },
  {
    slug: 'turkey-and-rice-stuffed-cabbage',
    title: 'Turkey and Rice Stuffed Cabbage Rolls',
    summary: 'Cabbage leaves rolled around seasoned turkey and rice, baked in tomato sauce.',
    servings: 4,
    prepMinutes: 25,
    cookMinutes: 45,
    cuisine: 'Eastern European',
    difficulty: 3,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'cabbage', qty: 1, unit: 'each' },
      { slug: 'ground_turkey', qty: 500, unit: 'g' },
      { slug: 'white_rice', qty: 0.5, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'egg', qty: 1, unit: 'each' },
      { slug: 'tomato_canned_diced', qty: 2, unit: 'can' },
      { slug: 'paprika', qty: 1, unit: 'tsp' },
      { slug: 'salt', qty: 1.5, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Core the cabbage and boil whole for a few minutes to soften the leaves; peel off 8-10 large leaves.',
      'Mix turkey, uncooked rice, diced onion, egg, paprika, salt, and pepper.',
      'Spoon filling onto each cabbage leaf and roll up, tucking in the sides.',
      'Arrange rolls seam-side down in a baking dish, cover with diced tomatoes, and cover with foil.',
      'Bake at 350°F (175°C) for 45 minutes until the rice is tender.',
    ],
  },
  {
    slug: 'turkey-larb',
    title: 'Turkey Larb',
    summary: 'A zesty Thai/Laotian minced turkey salad with lime and herbs.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 10,
    cuisine: 'Thai',
    difficulty: 2,
    mealSlots: ['lunch', 'dinner'],
    ingredients: [
      { slug: 'ground_turkey', qty: 500, unit: 'g' },
      { slug: 'lime', qty: 2, unit: 'each' },
      { slug: 'fish_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'red_pepper_flakes', qty: 0.5, unit: 'tsp' },
      { slug: 'red_onion', qty: 0.5, unit: 'each', prepNote: 'thinly sliced' },
      { slug: 'cilantro', qty: 0.25, unit: 'cup' },
      { slug: 'lettuce_romaine', qty: 8, unit: 'each', prepNote: 'whole leaves, for wrapping' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Heat oil; cook the ground turkey through, breaking it up, about 7-8 minutes.',
      'Remove from heat and toss with lime juice, fish sauce, and red pepper flakes.',
      'Stir in red onion and cilantro.',
      'Serve in lettuce leaves alongside rice.',
    ],
  },
  {
    slug: 'greek-turkey-meatball-bowls',
    title: 'Greek Turkey Meatball Bowls',
    summary: 'Baked oregano turkey meatballs over rice with tzatziki.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 20,
    cuisine: 'Greek',
    difficulty: 2,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'ground_turkey', qty: 500, unit: 'g' },
      { slug: 'panko_breadcrumbs', qty: 0.33, unit: 'cup' },
      { slug: 'egg', qty: 1, unit: 'each' },
      { slug: 'oregano_dried', qty: 1, unit: 'tsp' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'greek_yogurt', qty: 0.5, unit: 'cup' },
      { slug: 'cucumber', qty: 0.5, unit: 'each', prepNote: 'diced' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'cherry_tomatoes', qty: 1, unit: 'cup' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 400°F (200°C). Mix turkey, breadcrumbs, egg, oregano, minced garlic, and half the salt; form into 16 meatballs.',
      'Bake 18-20 minutes until cooked through.',
      'Mix yogurt, cucumber, lemon juice, and remaining salt for the sauce.',
      'Cook rice and serve with the meatballs, cherry tomatoes, and yogurt sauce.',
    ],
  },
  {
    slug: 'moroccan-turkey-stuffed-peppers',
    title: 'Moroccan-Spiced Turkey Stuffed Peppers',
    summary: 'Bell peppers stuffed with warm-spiced turkey and rice.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 40,
    cuisine: 'Moroccan',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_turkey', qty: 500, unit: 'g' },
      { slug: 'bell_pepper_red', qty: 4, unit: 'each' },
      { slug: 'white_rice', qty: 0.5, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'cinnamon', qty: 0.25, unit: 'tsp' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 375°F (190°C). Cook rice according to package directions.',
      'Halve the peppers lengthwise and remove seeds; arrange in a baking dish.',
      'Cook turkey and onion in oil until browned; stir in rice, cumin, cinnamon, half the tomatoes, and salt.',
      'Fill the peppers, top with remaining tomatoes, cover with foil, and bake 30 minutes until tender.',
    ],
  },
  {
    slug: 'turkey-and-black-bean-chili',
    title: 'Turkey and Black Bean Chili',
    summary: 'A lighter chili built on ground turkey and black beans.',
    servings: 6,
    prepMinutes: 10,
    cookMinutes: 35,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'ground_turkey', qty: 700, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'chili_powder', qty: 2, unit: 'tbsp' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'tomato_canned_diced', qty: 2, unit: 'can' },
      { slug: 'black_beans_canned', qty: 2, unit: 'can' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'cheddar_cheese', qty: 0.5, unit: 'cup', optional: true },
      { slug: 'salt', qty: 1.5, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion and garlic, about 5 minutes.',
      'Add ground turkey and cook until no longer pink.',
      'Stir in chili powder and cumin, then diced tomatoes and black beans. Simmer uncovered 25 minutes.',
      'Season with salt and top with cheddar if using.',
    ],
  },
  {
    slug: 'turkey-katsu',
    title: 'Turkey Katsu',
    summary: 'Crispy breaded turkey cutlets, Japanese katsu-style.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    cuisine: 'Japanese',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'turkey_breast', qty: 600, unit: 'g', prepNote: 'pounded thin' },
      { slug: 'all_purpose_flour', qty: 0.5, unit: 'cup' },
      { slug: 'egg', qty: 2, unit: 'each' },
      { slug: 'panko_breadcrumbs', qty: 1, unit: 'cup' },
      { slug: 'vegetable_oil', qty: 4, unit: 'tbsp' },
      { slug: 'cabbage', qty: 0.25, unit: 'each', prepNote: 'shredded' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'bbq_sauce', qty: 0.25, unit: 'cup', prepNote: 'or tonkatsu sauce if available' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Season turkey with salt. Dredge in flour, then egg, then breadcrumbs.',
      'Pan-fry in oil, 3-4 minutes per side, until golden and cooked through.',
      'Cook rice according to package directions.',
      'Slice the cutlets and serve over rice with shredded cabbage and sauce.',
    ],
  },
  {
    slug: 'turkey-shepherds-pie',
    title: 'Turkey Shepherd\'s Pie',
    summary: 'A comforting baked dish of turkey and vegetables under mashed potato.',
    servings: 6,
    prepMinutes: 20,
    cookMinutes: 35,
    cuisine: 'British',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_turkey', qty: 700, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'carrot', qty: 2, unit: 'each', prepNote: 'diced' },
      { slug: 'peas', qty: 1, unit: 'cup' },
      { slug: 'tomato_paste', qty: 2, unit: 'tbsp' },
      { slug: 'chicken_broth', qty: 1, unit: 'cup' },
      { slug: 'potato', qty: 5, unit: 'each' },
      { slug: 'butter', qty: 3, unit: 'tbsp' },
      { slug: 'milk', qty: 0.33, unit: 'cup' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1.5, unit: 'tsp' },
    ],
    steps: [
      'Boil the potatoes until tender, then mash with butter, milk, and half the salt.',
      'Preheat oven to 400°F (200°C). Heat oil; brown turkey with onion and carrot, about 8 minutes.',
      'Stir in tomato paste, broth, peas, and remaining salt; simmer 10 minutes.',
      'Transfer to a baking dish, top with mashed potato, and bake 20 minutes until golden.',
    ],
  },
  {
    slug: 'turkey-and-quinoa-stuffed-zucchini',
    title: 'Turkey and Quinoa Stuffed Zucchini',
    summary: 'Zucchini boats filled with seasoned turkey and quinoa.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 30,
    cuisine: 'Mediterranean',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'zucchini', qty: 4, unit: 'each' },
      { slug: 'ground_turkey', qty: 400, unit: 'g' },
      { slug: 'quinoa', qty: 0.5, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'feta_cheese', qty: 0.33, unit: 'cup', optional: true },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'oregano_dried', qty: 1, unit: 'tsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 375°F (190°C). Halve zucchini lengthwise and scoop out the centers, leaving a shell.',
      'Cook quinoa according to package directions.',
      'Heat oil; brown turkey with onion and garlic. Stir in quinoa, half the tomatoes, oregano, and salt.',
      'Fill the zucchini shells, top with remaining tomatoes and feta, and bake 20-25 minutes until tender.',
    ],
  },
  {
    slug: 'turkey-club-sandwich',
    title: 'Turkey Club Sandwich',
    summary: 'A classic stacked sandwich with turkey, lettuce, and tomato.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 5,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['lunch'],
    ingredients: [
      { slug: 'turkey_breast', qty: 300, unit: 'g', prepNote: 'cooked and sliced' },
      { slug: 'bread_sandwich', qty: 6, unit: 'slice' },
      { slug: 'lettuce_romaine', qty: 2, unit: 'each' },
      { slug: 'tomato', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'mayonnaise', qty: 2, unit: 'tbsp' },
      { slug: 'cheddar_cheese', qty: 2, unit: 'slice', optional: true },
    ],
    steps: [
      'Toast the bread slices.',
      'Spread mayonnaise on the bread, then layer turkey, lettuce, tomato, and cheese between the slices.',
      'Cut into halves or quarters and serve.',
    ],
  },
]
