// Ground beef family — American, Mexican, Italian, Middle Eastern.

export const recipes = [
  {
    slug: 'classic-beef-tacos',
    title: 'Classic Beef Tacos',
    summary: 'Seasoned ground beef in warm tortillas with fresh toppings.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'ground_beef', qty: 500, unit: 'g' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'taco_seasoning', qty: 2, unit: 'tbsp' },
      { slug: 'tortilla_corn', qty: 8, unit: 'each' },
      { slug: 'lettuce_romaine', qty: 1, unit: 'cup', prepNote: 'shredded' },
      { slug: 'tomato', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'cheddar_cheese', qty: 0.5, unit: 'cup', prepNote: 'shredded' },
      { slug: 'sour_cream', qty: 0.25, unit: 'cup', optional: true },
      { slug: 'lime', qty: 1, unit: 'each' },
    ],
    steps: [
      'Cook ground beef and diced onion in a skillet over medium-high heat until browned, about 7 minutes.',
      'Drain excess fat, add taco seasoning and a splash of water, and simmer 2 minutes.',
      'Warm the tortillas in a dry pan or microwave.',
      'Fill tortillas with beef, lettuce, tomato, and cheddar. Serve with sour cream and lime.',
    ],
  },
  {
    slug: 'spaghetti-bolognese',
    title: 'Spaghetti Bolognese',
    summary: 'Rich tomato and ground beef sauce over spaghetti.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 35,
    cuisine: 'Italian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_beef', qty: 500, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'celery', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'tomato_canned_diced', qty: 2, unit: 'can' },
      { slug: 'tomato_paste', qty: 2, unit: 'tbsp' },
      { slug: 'italian_seasoning', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'spaghetti', qty: 340, unit: 'g' },
      { slug: 'parmesan_cheese', qty: 0.5, unit: 'cup', prepNote: 'grated' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil in a large pot; soften onion, garlic, carrot, and celery, about 6 minutes.',
      'Add ground beef and cook until browned, breaking it up as it cooks.',
      'Stir in tomato paste, diced tomatoes, italian seasoning, and salt. Simmer uncovered 20-25 minutes, stirring occasionally.',
      'Cook spaghetti according to package directions.',
      'Toss the pasta with the sauce and serve topped with parmesan.',
    ],
  },
  {
    slug: 'beef-and-broccoli-stir-fry',
    title: 'Beef and Broccoli Stir-Fry',
    summary: 'Quick stir-fried beef and broccoli in a savory garlic sauce.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 12,
    cuisine: 'Chinese',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_beef', qty: 500, unit: 'g' },
      { slug: 'broccoli', qty: 400, unit: 'g', prepNote: 'cut into florets' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'oyster_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'cornstarch', qty: 1, unit: 'tsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Steam or blanch the broccoli 3 minutes until bright green and just tender; set aside.',
      'Whisk soy sauce, oyster sauce, and cornstarch in a small bowl.',
      'Heat oil in a wok over high heat. Brown the ground beef with garlic and ginger, about 5 minutes.',
      'Add the broccoli and sauce; toss until the sauce thickens and coats everything, about 2 minutes. Finish with sesame oil and serve over rice.',
    ],
  },
  {
    slug: 'stuffed-bell-peppers',
    title: 'Stuffed Bell Peppers',
    summary: 'Bell peppers filled with seasoned beef, rice, and tomato.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 40,
    cuisine: 'American',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_beef', qty: 500, unit: 'g' },
      { slug: 'bell_pepper_red', qty: 2, unit: 'each' },
      { slug: 'bell_pepper_green', qty: 2, unit: 'each' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'white_rice', qty: 0.5, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'cheddar_cheese', qty: 0.5, unit: 'cup', prepNote: 'shredded' },
      { slug: 'garlic_powder', qty: 1, unit: 'tsp' },
      { slug: 'oregano_dried', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 375°F (190°C). Cook rice according to package directions.',
      'Halve the bell peppers lengthwise and remove seeds. Arrange in a baking dish.',
      'Cook ground beef and onion in a skillet until browned. Stir in cooked rice, half the tomatoes, garlic powder, oregano, and salt.',
      'Fill each pepper half with the beef mixture, top with remaining tomatoes, and cover with foil.',
      'Bake 25 minutes, uncover, top with cheddar, and bake 10 more minutes until the cheese melts and peppers are tender.',
    ],
  },
  {
    slug: 'beef-chili',
    title: 'Beef Chili',
    summary: 'Hearty chili with ground beef, beans, and warm spices.',
    servings: 6,
    prepMinutes: 10,
    cookMinutes: 40,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'ground_beef', qty: 700, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'bell_pepper_green', qty: 1, unit: 'each' },
      { slug: 'chili_powder', qty: 2, unit: 'tbsp' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'smoked_paprika', qty: 1, unit: 'tsp' },
      { slug: 'tomato_canned_diced', qty: 2, unit: 'can' },
      { slug: 'tomato_paste', qty: 2, unit: 'tbsp' },
      { slug: 'black_beans_canned', qty: 1, unit: 'can' },
      { slug: 'pinto_beans_canned', qty: 1, unit: 'can' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1.5, unit: 'tsp' },
    ],
    steps: [
      'Heat oil in a large pot; soften onion, garlic, and bell pepper, about 5 minutes.',
      'Add ground beef and cook until browned.',
      'Stir in chili powder, cumin, and smoked paprika; cook 1 minute.',
      'Add diced tomatoes, tomato paste, black beans, and pinto beans. Simmer uncovered 30 minutes, stirring occasionally.',
      'Season with salt and serve.',
    ],
  },
  {
    slug: 'beef-koftas-with-yogurt-sauce',
    title: 'Beef Koftas with Yogurt Sauce',
    summary: 'Spiced grilled beef kofta skewers with a cool yogurt dip.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 12,
    cuisine: 'Middle Eastern',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_beef', qty: 500, unit: 'g' },
      { slug: 'onion', qty: 0.25, unit: 'each', prepNote: 'grated' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'coriander_ground', qty: 1, unit: 'tsp' },
      { slug: 'cinnamon', qty: 0.25, unit: 'tsp' },
      { slug: 'parsley', qty: 2, unit: 'tbsp', prepNote: 'chopped' },
      { slug: 'greek_yogurt', qty: 0.5, unit: 'cup' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'pita_bread', qty: 4, unit: 'each' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Mix ground beef with grated onion, garlic, cumin, coriander, cinnamon, parsley, and salt. Shape into small logs on skewers.',
      'Whisk yogurt with lemon juice and a pinch of salt for the sauce.',
      'Grill or pan-sear the koftas 10-12 minutes, turning occasionally, until cooked through.',
      'Warm the pita and serve with the koftas and yogurt sauce.',
    ],
  },
  {
    slug: 'beef-empanadas-skillet',
    title: 'Beef and Rice Skillet',
    summary: 'One-pan spiced beef and rice with peppers and corn.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_beef', qty: 500, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'chicken_broth', qty: 1, unit: 'can' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'corn', qty: 1, unit: 'cup' },
      { slug: 'chili_powder', qty: 1, unit: 'tsp' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'cheddar_cheese', qty: 0.5, unit: 'cup', prepNote: 'shredded', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Brown ground beef with onion and bell pepper in a large skillet, about 6 minutes.',
      'Stir in rice, broth, diced tomatoes, chili powder, and cumin.',
      'Bring to a simmer, cover, and cook 18-20 minutes until the rice is tender.',
      'Stir in corn, season with salt, top with cheddar if using, and let it melt before serving.',
    ],
  },
  {
    slug: 'juicy-beef-burgers',
    title: 'Juicy Beef Burgers',
    summary: 'Classic grilled beef burgers with all the fixings.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 10,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'ground_beef', qty: 600, unit: 'g' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
      { slug: 'garlic_powder', qty: 1, unit: 'tsp' },
      { slug: 'bread_sandwich', qty: 4, unit: 'slice', prepNote: 'or 4 burger buns' },
      { slug: 'cheddar_cheese', qty: 4, unit: 'slice' },
      { slug: 'lettuce_romaine', qty: 1, unit: 'cup', prepNote: 'shredded' },
      { slug: 'tomato', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'mayonnaise', qty: 2, unit: 'tbsp', optional: true },
    ],
    steps: [
      'Mix ground beef with salt, pepper, and garlic powder; shape into 4 patties.',
      'Grill or pan-sear over medium-high heat, about 4 minutes per side, adding cheese in the last minute to melt.',
      'Toast the bread or buns lightly.',
      'Build the burgers with lettuce, tomato, and mayonnaise.',
    ],
  },
  {
    slug: 'beef-lettuce-wraps',
    title: 'Asian Beef Lettuce Wraps',
    summary: 'Savory ground beef with a sweet-salty glaze, served in lettuce cups.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Chinese',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'ground_beef', qty: 500, unit: 'g' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'hoisin_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'rice_vinegar', qty: 1, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'shredded' },
      { slug: 'green_onion', qty: 2, unit: 'each', prepNote: 'sliced' },
      { slug: 'lettuce_romaine', qty: 8, unit: 'each', prepNote: 'whole leaves, for wrapping' },
    ],
    steps: [
      'Brown ground beef with garlic and ginger in a skillet, about 6 minutes.',
      'Stir in soy sauce, hoisin, and rice vinegar; simmer 3 minutes until slightly thickened.',
      'Finish with sesame oil and stir in shredded carrot.',
      'Spoon the beef into lettuce leaves, top with green onion, and serve.',
    ],
  },
  {
    slug: 'beef-and-potato-hash',
    title: 'Beef and Potato Hash',
    summary: 'A hearty skillet of ground beef, potatoes, and peppers.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['breakfast', 'dinner'],
    ingredients: [
      { slug: 'ground_beef', qty: 450, unit: 'g' },
      { slug: 'potato', qty: 3, unit: 'each', prepNote: 'diced' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'bell_pepper_green', qty: 1, unit: 'each' },
      { slug: 'smoked_paprika', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'egg', qty: 4, unit: 'each', optional: true, prepNote: 'fried, to top' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Heat oil in a large skillet. Cook diced potato 10-12 minutes, stirring occasionally, until browned and nearly tender.',
      'Push potatoes aside, add ground beef, and brown, breaking it up as it cooks.',
      'Add onion, bell pepper, smoked paprika, salt, and pepper; cook 5 more minutes until vegetables soften.',
      'Top with a fried egg per serving if desired.',
    ],
  },
  {
    slug: 'greek-beef-and-orzo',
    title: 'Greek-Style Beef and Orzo Skillet',
    summary: 'One-pan spiced beef simmered with orzo, tomato, and feta.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Greek',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_beef', qty: 500, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'couscous', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'vegetable_broth', qty: 1.5, unit: 'cup' },
      { slug: 'oregano_dried', qty: 1, unit: 'tsp' },
      { slug: 'feta_cheese', qty: 0.5, unit: 'cup', prepNote: 'crumbled' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; brown the ground beef with onion and garlic, about 7 minutes.',
      'Stir in couscous, diced tomatoes, broth, oregano, and salt.',
      'Bring to a simmer, cover, and cook 10 minutes until the couscous absorbs the liquid.',
      'Top with feta before serving.',
    ],
  },
  {
    slug: 'vietnamese-beef-noodle-bowl',
    title: 'Vietnamese-Style Ground Beef Noodle Bowl',
    summary: 'Savory beef over rice noodles with fresh herbs and lime.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 12,
    cuisine: 'Vietnamese',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_beef', qty: 500, unit: 'g' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'fish_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 1, unit: 'tbsp' },
      { slug: 'lime', qty: 2, unit: 'each' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'rice_noodles', qty: 300, unit: 'g' },
      { slug: 'cucumber', qty: 0.5, unit: 'each', prepNote: 'julienned' },
      { slug: 'cilantro', qty: 0.25, unit: 'cup' },
      { slug: 'bean_sprouts', qty: 1, unit: 'cup', optional: true },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
    ],
    steps: [
      'Cook rice noodles according to package directions; rinse and drain.',
      'Heat oil; brown the ground beef with garlic, about 6-7 minutes.',
      'Whisk fish sauce, soy sauce, lime juice, and honey for the dressing.',
      'Divide noodles into bowls, top with beef, cucumber, bean sprouts, and cilantro, and drizzle with dressing.',
    ],
  },
  {
    slug: 'brazilian-beef-and-rice',
    title: 'Brazilian-Style Beef and Rice',
    summary: 'Garlicky seasoned ground beef over rice with black beans.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Brazilian',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_beef', qty: 500, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 4, unit: 'clove' },
      { slug: 'bell_pepper_green', qty: 1, unit: 'each' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'black_beans_canned', qty: 1, unit: 'can' },
      { slug: 'white_rice', qty: 1.5, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Heat oil; brown the beef with onion, garlic, and bell pepper, about 8 minutes.',
      'Stir in diced tomatoes and simmer 10 minutes.',
      'Warm the black beans separately and serve alongside the beef and rice with a squeeze of lime.',
    ],
  },
  {
    slug: 'indian-beef-keema',
    title: 'Beef Keema',
    summary: 'Spiced ground beef simmered with peas, Indian-style.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Indian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_beef', qty: 500, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'garam_masala', qty: 1.5, unit: 'tsp' },
      { slug: 'turmeric', qty: 0.5, unit: 'tsp' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'tomato_paste', qty: 2, unit: 'tbsp' },
      { slug: 'peas', qty: 1, unit: 'cup' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'naan', qty: 4, unit: 'each' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, and ginger, about 5 minutes.',
      'Add garam masala, turmeric, and cumin; cook 1 minute.',
      'Add ground beef and cook until browned, breaking it up as it cooks.',
      'Stir in tomato paste and peas; simmer 10 minutes. Season with salt.',
      'Garnish with cilantro and serve with warm naan.',
    ],
  },
  {
    slug: 'korean-beef-bulgogi-bowl',
    title: 'Korean Ground Beef Bowl',
    summary: 'Sweet-savory ground beef over rice, bulgogi-style.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Korean',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_beef', qty: 500, unit: 'g' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tsp' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'brown_sugar', qty: 2, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'sesame_seeds', qty: 1, unit: 'tsp', optional: true },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Brown the ground beef with garlic and ginger, about 7 minutes.',
      'Stir in soy sauce and brown sugar; simmer 2-3 minutes until glazed.',
      'Finish with sesame oil, serve over rice, and top with green onion and sesame seeds.',
    ],
  },
  {
    slug: 'beef-picadillo',
    title: 'Beef Picadillo',
    summary: 'A savory-sweet Latin American ground beef hash with olives and raisins.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Cuban',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_beef', qty: 500, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'bell_pepper_green', qty: 1, unit: 'each' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'kalamata_olives', qty: 0.25, unit: 'cup' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, and bell pepper, about 6 minutes.',
      'Add ground beef and brown, breaking it up as it cooks.',
      'Stir in diced tomatoes, olives, and cumin; simmer 12-15 minutes.',
      'Season with salt. Cook rice and serve the picadillo over it.',
    ],
  },
]
