// Chickpeas & lentils family — vegetarian/vegan anchor.

export const recipes = [
  {
    slug: 'red-lentil-dal',
    title: 'Red Lentil Dal',
    summary: 'Comforting spiced lentils simmered until creamy.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    cuisine: 'Indian',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'lentils_dry', qty: 1.5, unit: 'cup' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'turmeric', qty: 1, unit: 'tsp' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'garam_masala', qty: 0.5, unit: 'tsp' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'vegetable_broth', qty: 3, unit: 'cup' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Rinse the lentils. Heat oil; soften onion, garlic, and ginger, about 5 minutes.',
      'Add turmeric, cumin, and garam masala; cook 1 minute.',
      'Add lentils, diced tomatoes, and broth. Simmer 20-25 minutes, stirring occasionally, until the lentils break down and thicken.',
      'Season with salt. Cook rice and serve the dal over it, garnished with cilantro.',
    ],
  },
  {
    slug: 'chickpea-shawarma-bowl',
    title: 'Chickpea Shawarma Bowl',
    summary: 'Spiced roasted chickpeas over rice with a cool yogurt sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Middle Eastern',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'chickpeas_canned', qty: 2, unit: 'can' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'coriander_ground', qty: 1, unit: 'tsp' },
      { slug: 'turmeric', qty: 0.5, unit: 'tsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'greek_yogurt', qty: 0.5, unit: 'cup' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 1, unit: 'clove' },
      { slug: 'cucumber', qty: 0.5, unit: 'each', prepNote: 'diced' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 425°F (220°C). Toss drained chickpeas with cumin, coriander, turmeric, oil, and salt.',
      'Roast 20-25 minutes, shaking the pan halfway, until crisped.',
      'Whisk yogurt, lemon juice, minced garlic, and cucumber for the sauce.',
      'Cook rice and serve topped with the roasted chickpeas and yogurt sauce.',
    ],
  },
  {
    slug: 'chickpea-tikka-masala',
    title: 'Chickpea Tikka Masala',
    summary: 'The creamy tomato curry classic, built on chickpeas.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Indian',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'chickpeas_canned', qty: 2, unit: 'can' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'garam_masala', qty: 2, unit: 'tsp' },
      { slug: 'turmeric', qty: 1, unit: 'tsp' },
      { slug: 'tomato_paste', qty: 3, unit: 'tbsp' },
      { slug: 'coconut_milk', qty: 1, unit: 'cup' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, then add garlic, ginger, garam masala, and turmeric. Cook 1 minute.',
      'Stir in tomato paste and coconut milk; simmer 5 minutes.',
      'Add the chickpeas and simmer 12-15 minutes until the sauce thickens.',
      'Season with salt, garnish with cilantro, and serve over rice.',
    ],
  },
  {
    slug: 'lentil-bolognese',
    title: 'Lentil Bolognese',
    summary: 'A hearty vegetarian pasta sauce built on lentils.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    cuisine: 'Italian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'lentils_dry', qty: 1, unit: 'cup' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'celery', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'tomato_canned_diced', qty: 2, unit: 'can' },
      { slug: 'tomato_paste', qty: 2, unit: 'tbsp' },
      { slug: 'italian_seasoning', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_broth', qty: 1, unit: 'cup' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'pasta_penne', qty: 340, unit: 'g' },
      { slug: 'parmesan_cheese', qty: 0.5, unit: 'cup', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, carrot, and celery, about 6 minutes.',
      'Add lentils, diced tomatoes, tomato paste, italian seasoning, broth, and salt.',
      'Simmer uncovered 25 minutes, stirring occasionally, until the lentils are tender and the sauce thickens.',
      'Cook pasta according to package directions and toss with the sauce. Top with parmesan if using.',
    ],
  },
  {
    slug: 'chickpea-salad-sandwich',
    title: 'Smashed Chickpea Salad Sandwich',
    summary: 'A quick no-cook lunch: smashed chickpeas with a light dressing.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 0,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['lunch'],
    ingredients: [
      { slug: 'chickpeas_canned', qty: 1, unit: 'can' },
      { slug: 'mayonnaise', qty: 2, unit: 'tbsp' },
      { slug: 'dijon_mustard', qty: 1, unit: 'tsp' },
      { slug: 'celery', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'lemon', qty: 0.5, unit: 'each' },
      { slug: 'bread_sandwich', qty: 4, unit: 'slice' },
      { slug: 'lettuce_romaine', qty: 2, unit: 'each' },
      { slug: 'salt', qty: 0.5, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.25, unit: 'tsp' },
    ],
    steps: [
      'Drain the chickpeas and mash roughly with a fork, leaving some texture.',
      'Mix in mayonnaise, dijon, celery, lemon juice, salt, and pepper.',
      'Spread onto bread with lettuce and serve as a sandwich.',
    ],
  },
  {
    slug: 'moroccan-chickpea-stew',
    title: 'Moroccan Chickpea Stew',
    summary: 'Warm-spiced chickpea and vegetable stew.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    cuisine: 'Moroccan',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'chickpeas_canned', qty: 2, unit: 'can' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'carrot', qty: 2, unit: 'each', prepNote: 'sliced' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'cinnamon', qty: 0.5, unit: 'tsp' },
      { slug: 'coriander_ground', qty: 1, unit: 'tsp' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'vegetable_broth', qty: 2, unit: 'cup' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'couscous', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, and carrot, about 6 minutes.',
      'Add cumin, cinnamon, and coriander; cook 1 minute.',
      'Add chickpeas, diced tomatoes, and broth. Simmer 20 minutes until the carrots are tender.',
      'Season with salt. Cook couscous according to package directions and serve the stew over it.',
    ],
  },
  {
    slug: 'lentil-and-spinach-soup',
    title: 'Lentil and Spinach Soup',
    summary: 'A simple, nourishing soup of lentils, spinach, and cumin.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    cuisine: 'Mediterranean',
    difficulty: 1,
    mealSlots: ['lunch', 'dinner'],
    ingredients: [
      { slug: 'lentils_dry', qty: 1, unit: 'cup' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_broth', qty: 4, unit: 'cup' },
      { slug: 'spinach', qty: 100, unit: 'g' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, and carrot, about 5 minutes.',
      'Add cumin, lentils, and broth. Simmer 25 minutes until the lentils are tender.',
      'Stir in spinach until wilted, about 2 minutes.',
      'Season with salt and a squeeze of lemon before serving.',
    ],
  },
  {
    slug: 'chickpea-coconut-curry',
    title: 'Chickpea Coconut Curry',
    summary: 'Creamy coconut curry loaded with chickpeas and spinach.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'Indian',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'chickpeas_canned', qty: 2, unit: 'can' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'curry_powder', qty: 2, unit: 'tsp' },
      { slug: 'coconut_milk', qty: 1, unit: 'can' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'spinach', qty: 150, unit: 'g' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion and garlic, about 4 minutes.',
      'Add curry powder, cook 1 minute, then add coconut milk and diced tomatoes.',
      'Add chickpeas and simmer 12 minutes.',
      'Stir in spinach until wilted. Season with salt. Cook rice and serve the curry over it.',
    ],
  },
  {
    slug: 'ethiopian-misir-wot',
    title: 'Misir Wot (Ethiopian Spiced Lentils)',
    summary: 'Deeply spiced red lentil stew, Ethiopian-style.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    cuisine: 'Ethiopian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'lentils_dry', qty: 1.5, unit: 'cup' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'cayenne_pepper', qty: 1, unit: 'tsp' },
      { slug: 'paprika', qty: 1, unit: 'tbsp' },
      { slug: 'cardamom', qty: 0.25, unit: 'tsp' },
      { slug: 'tomato_paste', qty: 2, unit: 'tbsp' },
      { slug: 'vegetable_broth', qty: 3, unit: 'cup' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'pita_bread', qty: 4, unit: 'each', prepNote: 'or injera if available' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, and ginger, about 6 minutes.',
      'Add cayenne, paprika, and cardamom; cook 1 minute.',
      'Stir in tomato paste, lentils, and broth. Simmer 20-25 minutes until the lentils are tender.',
      'Season with salt and serve with warm flatbread.',
    ],
  },
  {
    slug: 'spanish-lentil-stew',
    title: 'Spanish-Style Lentil Stew',
    summary: 'Smoky paprika-spiced lentils with vegetables.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    cuisine: 'Spanish',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'lentils_dry', qty: 1.5, unit: 'cup' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'carrot', qty: 2, unit: 'each', prepNote: 'diced' },
      { slug: 'smoked_paprika', qty: 1.5, unit: 'tsp' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'vegetable_broth', qty: 3, unit: 'cup' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, and carrot, about 6 minutes.',
      'Stir in smoked paprika, cook 1 minute, then add diced tomatoes, lentils, and broth.',
      'Simmer 25 minutes until the lentils are tender.',
      'Season with salt and serve.',
    ],
  },
  {
    slug: 'chickpea-and-spinach-curry-bowl',
    title: 'Chana Saag (Chickpea and Spinach Curry)',
    summary: 'Chickpeas simmered into a garlicky spinach curry.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'Indian',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'chickpeas_canned', qty: 2, unit: 'can' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'coriander_ground', qty: 1, unit: 'tsp' },
      { slug: 'spinach', qty: 300, unit: 'g' },
      { slug: 'coconut_milk', qty: 0.5, unit: 'cup' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'naan', qty: 4, unit: 'each' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, and ginger, about 5 minutes.',
      'Add cumin and coriander; cook 1 minute.',
      'Add chickpeas and spinach; cook until the spinach wilts, about 4 minutes.',
      'Stir in coconut milk and simmer 5 minutes. Season with salt and serve with naan.',
    ],
  },
  {
    slug: 'french-lentil-salad',
    title: 'French Lentil Salad',
    summary: 'A cold lentil salad with dijon vinaigrette and fresh herbs.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 20,
    cuisine: 'French',
    difficulty: 1,
    mealSlots: ['lunch'],
    ingredients: [
      { slug: 'lentils_dry', qty: 1.5, unit: 'cup' },
      { slug: 'dijon_mustard', qty: 1, unit: 'tbsp' },
      { slug: 'balsamic_vinegar', qty: 2, unit: 'tbsp' },
      { slug: 'olive_oil', qty: 3, unit: 'tbsp' },
      { slug: 'celery', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'red_onion', qty: 0.25, unit: 'each', prepNote: 'finely diced' },
      { slug: 'parsley', qty: 2, unit: 'tbsp' },
      { slug: 'feta_cheese', qty: 0.33, unit: 'cup', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook lentils in water until tender but not mushy, about 18-20 minutes; drain and cool slightly.',
      'Whisk dijon, balsamic vinegar, olive oil, and salt for the dressing.',
      'Toss the lentils with celery, carrot, red onion, and parsley.',
      'Add the dressing and toss to coat. Top with feta if using.',
    ],
  },
  {
    slug: 'chickpea-and-spinach-pasta',
    title: 'Chickpea and Spinach Pasta',
    summary: 'A quick pantry pasta with chickpeas, garlic, and spinach.',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 20,
    cuisine: 'Italian',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'chickpeas_canned', qty: 1, unit: 'can' },
      { slug: 'pasta_penne', qty: 340, unit: 'g' },
      { slug: 'garlic', qty: 4, unit: 'clove' },
      { slug: 'spinach', qty: 150, unit: 'g' },
      { slug: 'red_pepper_flakes', qty: 0.25, unit: 'tsp' },
      { slug: 'olive_oil', qty: 3, unit: 'tbsp' },
      { slug: 'parmesan_cheese', qty: 0.5, unit: 'cup', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook pasta according to package directions, reserving 0.5 cup pasta water.',
      'Heat oil; sauté garlic and red pepper flakes 30 seconds.',
      'Add chickpeas and cook 3-4 minutes, lightly mashing some.',
      'Add spinach and cook until wilted; toss with the pasta, a splash of pasta water, and salt. Top with parmesan.',
    ],
  },
  {
    slug: 'mexican-lentil-tacos',
    title: 'Mexican-Spiced Lentil Tacos',
    summary: 'Seasoned lentils standing in for meat in a taco.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'lentils_dry', qty: 1, unit: 'cup' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'taco_seasoning', qty: 2, unit: 'tbsp' },
      { slug: 'vegetable_broth', qty: 2, unit: 'cup' },
      { slug: 'tortilla_corn', qty: 8, unit: 'each' },
      { slug: 'lettuce_romaine', qty: 1, unit: 'cup', prepNote: 'shredded' },
      { slug: 'tomato', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'avocado', qty: 1, unit: 'each' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
    ],
    steps: [
      'Heat oil; soften onion and garlic, about 4 minutes.',
      'Add lentils, taco seasoning, and broth. Simmer 20 minutes until the lentils are tender and most liquid is absorbed.',
      'Warm the tortillas and fill with the lentil mixture, lettuce, tomato, and avocado.',
    ],
  },
]
