// Oats family — breakfast anchor.

export const recipes = [
  {
    slug: 'classic-oatmeal-with-banana',
    title: 'Classic Oatmeal with Banana and Walnuts',
    summary: 'Warm stovetop oatmeal with banana, walnuts, and cinnamon.',
    servings: 1,
    prepMinutes: 2,
    cookMinutes: 8,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'rolled_oats', qty: 0.5, unit: 'cup' },
      { slug: 'milk', qty: 1, unit: 'cup' },
      { slug: 'cinnamon', qty: 0.25, unit: 'tsp' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'walnuts', qty: 2, unit: 'tbsp' },
      { slug: 'banana', qty: 1, unit: 'each', prepNote: 'sliced' },
    ],
    steps: [
      'Bring milk to a simmer in a small pot.',
      'Stir in oats and cinnamon; cook 5-6 minutes, stirring occasionally, until thickened.',
      'Top with sliced banana, walnuts, and a drizzle of honey.',
    ],
  },
  {
    slug: 'peanut-butter-banana-overnight-oats',
    title: 'Peanut Butter Banana Overnight Oats',
    summary: 'No-cook oats soaked overnight with peanut butter and banana.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 0,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'rolled_oats', qty: 0.5, unit: 'cup' },
      { slug: 'milk', qty: 0.5, unit: 'cup' },
      { slug: 'greek_yogurt', qty: 0.25, unit: 'cup' },
      { slug: 'peanut_butter', qty: 1, unit: 'tbsp' },
      { slug: 'honey', qty: 1, unit: 'tsp' },
      { slug: 'chia_seeds', qty: 1, unit: 'tsp', optional: true },
      { slug: 'banana', qty: 1, unit: 'each', prepNote: 'sliced' },
    ],
    steps: [
      'Combine oats, milk, yogurt, peanut butter, honey, and chia seeds in a jar.',
      'Stir well, cover, and refrigerate overnight.',
      'Top with sliced banana before eating.',
    ],
  },
  {
    slug: 'savory-oatmeal-with-egg',
    title: 'Savory Oatmeal with Fried Egg',
    summary: 'A savory twist on oatmeal, topped with a fried egg and greens.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 10,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'rolled_oats', qty: 0.5, unit: 'cup' },
      { slug: 'vegetable_broth', qty: 1, unit: 'cup' },
      { slug: 'egg', qty: 1, unit: 'each' },
      { slug: 'spinach', qty: 0.5, unit: 'cup' },
      { slug: 'parmesan_cheese', qty: 2, unit: 'tbsp', prepNote: 'grated' },
      { slug: 'olive_oil', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.25, unit: 'tsp' },
      { slug: 'salt', qty: 0.25, unit: 'tsp' },
    ],
    steps: [
      'Simmer oats in vegetable broth 5-6 minutes until thickened; stir in spinach until wilted.',
      'Fry the egg in olive oil to your liking.',
      'Top the oatmeal with parmesan, the fried egg, salt, and pepper.',
    ],
  },
  {
    slug: 'baked-oatmeal-cups',
    title: 'Baked Oatmeal Cups',
    summary: 'Make-ahead oatmeal muffin cups with banana and cinnamon.',
    servings: 6,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'American',
    difficulty: 2,
    mealSlots: ['breakfast', 'snack'],
    ingredients: [
      { slug: 'rolled_oats', qty: 2, unit: 'cup' },
      { slug: 'egg', qty: 2, unit: 'each' },
      { slug: 'milk', qty: 1, unit: 'cup' },
      { slug: 'honey', qty: 3, unit: 'tbsp' },
      { slug: 'baking_powder', qty: 1, unit: 'tsp' },
      { slug: 'cinnamon', qty: 1, unit: 'tsp' },
      { slug: 'vanilla_extract', qty: 1, unit: 'tsp' },
      { slug: 'walnuts', qty: 0.33, unit: 'cup', optional: true },
    ],
    steps: [
      'Preheat oven to 375°F (190°C) and grease a muffin tin.',
      'Mix all ingredients together in a bowl.',
      'Divide among muffin cups and bake 18-20 minutes until set and golden.',
      'Cool slightly before removing; store extras in the fridge.',
    ],
  },
  {
    slug: 'apple-cinnamon-oatmeal',
    title: 'Apple Cinnamon Oatmeal',
    summary: 'Warm oatmeal simmered with diced apple and cinnamon.',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 10,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'rolled_oats', qty: 1, unit: 'cup' },
      { slug: 'milk', qty: 1.5, unit: 'cup' },
      { slug: 'apple', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'cinnamon', qty: 0.5, unit: 'tsp' },
      { slug: 'brown_sugar', qty: 2, unit: 'tbsp' },
      { slug: 'walnuts', qty: 0.25, unit: 'cup', optional: true },
    ],
    steps: [
      'Combine oats, milk, and cinnamon in a pot; bring to a simmer.',
      'Add diced apple and cook 6-8 minutes, stirring occasionally, until the oats are creamy and the apple softens.',
      'Stir in brown sugar and top with walnuts.',
    ],
  },
]
