// Pasta & noodle family — a rotating-protein base, spanning Italian and
// Asian noodle dishes.

export const recipes = [
  {
    slug: 'pasta-primavera',
    title: 'Pasta Primavera',
    summary: 'Penne tossed with a rainbow of sautéed spring vegetables.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    cuisine: 'Italian',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pasta_penne', qty: 340, unit: 'g' },
      { slug: 'zucchini', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each' },
      { slug: 'cherry_tomatoes', qty: 1.5, unit: 'cup' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'olive_oil', qty: 3, unit: 'tbsp' },
      { slug: 'parmesan_cheese', qty: 0.5, unit: 'cup', prepNote: 'grated' },
      { slug: 'basil_fresh', qty: 0.25, unit: 'cup' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook pasta according to package directions, reserving 0.5 cup pasta water.',
      'Heat oil in a large skillet; sauté garlic, zucchini, and bell pepper 5 minutes.',
      'Add cherry tomatoes and cook 3-4 minutes until they soften.',
      'Toss with the pasta, a splash of pasta water, parmesan, basil, and salt.',
    ],
  },
  {
    slug: 'pad-thai-style-noodles',
    title: 'Pad Thai-Style Noodles',
    summary: 'Stir-fried rice noodles with egg and peanuts in a tangy sauce.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 12,
    cuisine: 'Thai',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'rice_noodles', qty: 300, unit: 'g' },
      { slug: 'egg', qty: 2, unit: 'each' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'fish_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 1, unit: 'tbsp' },
      { slug: 'honey', qty: 2, unit: 'tbsp' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'peanuts_roasted', qty: 0.33, unit: 'cup' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'vegetable_oil', qty: 2, unit: 'tbsp' },
      { slug: 'bean_sprouts', qty: 1, unit: 'cup', optional: true },
    ],
    steps: [
      'Soak rice noodles in hot water according to package directions until pliable; drain.',
      'Whisk fish sauce, soy sauce, honey, and lime juice for the sauce.',
      'Heat oil in a wok; scramble the eggs softly and push to one side. Add garlic and noodles.',
      'Pour in the sauce and toss everything together over high heat for 2-3 minutes.',
      'Top with peanuts and green onion before serving.',
    ],
  },
  {
    slug: 'creamy-tomato-pasta',
    title: 'Creamy Tomato Pasta',
    summary: 'A quick, creamy tomato pasta with parmesan and basil.',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 20,
    cuisine: 'Italian',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pasta_penne', qty: 340, unit: 'g' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'tomato_canned_diced', qty: 2, unit: 'can' },
      { slug: 'heavy_cream', qty: 0.5, unit: 'cup' },
      { slug: 'parmesan_cheese', qty: 0.5, unit: 'cup', prepNote: 'grated' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'basil_dried', qty: 1, unit: 'tsp' },
      { slug: 'red_pepper_flakes', qty: 0.25, unit: 'tsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook pasta according to package directions.',
      'Heat oil; sauté garlic 30 seconds, then add diced tomatoes and basil. Simmer 10 minutes.',
      'Stir in cream and simmer 3-4 minutes until slightly thickened.',
      'Toss with the pasta and parmesan; season with salt and red pepper flakes.',
    ],
  },
  {
    slug: 'sesame-garlic-noodles',
    title: 'Sesame Garlic Noodles',
    summary: 'Fast, savory noodles in a garlicky sesame-soy sauce.',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 12,
    cuisine: 'Chinese',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'spaghetti', qty: 340, unit: 'g' },
      { slug: 'garlic', qty: 4, unit: 'clove' },
      { slug: 'soy_sauce', qty: 4, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 2, unit: 'tbsp' },
      { slug: 'rice_vinegar', qty: 1, unit: 'tbsp' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'red_pepper_flakes', qty: 0.25, unit: 'tsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'sesame_seeds', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook the spaghetti according to package directions.',
      'Whisk garlic, soy sauce, sesame oil, rice vinegar, honey, and red pepper flakes.',
      'Toss the hot pasta with the sauce until coated.',
      'Top with green onion and sesame seeds.',
    ],
  },
  {
    slug: 'pasta-e-fagioli',
    title: 'Pasta e Fagioli',
    summary: 'A rustic Italian pasta and bean soup.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    cuisine: 'Italian',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'pasta_penne', qty: 150, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'celery', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'pinto_beans_canned', qty: 2, unit: 'can' },
      { slug: 'vegetable_broth', qty: 3, unit: 'cup' },
      { slug: 'italian_seasoning', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'parmesan_cheese', qty: 0.33, unit: 'cup', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, carrot, and celery, about 6 minutes.',
      'Add diced tomatoes, one can of beans, and broth. Mash the second can of beans and stir in for creaminess.',
      'Add italian seasoning and simmer 15 minutes.',
      'Add the pasta and cook until al dente, about 10 minutes. Season with salt and top with parmesan.',
    ],
  },
  {
    slug: 'beef-and-noodle-soup',
    title: 'Beef and Noodle Soup',
    summary: 'A comforting brothy soup with thin noodles and vegetables.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Vietnamese',
    difficulty: 2,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'beef_sirloin', qty: 400, unit: 'g', prepNote: 'thinly sliced' },
      { slug: 'rice_noodles', qty: 250, unit: 'g' },
      { slug: 'chicken_broth', qty: 2, unit: 'can' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'soy_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'five_spice', qty: 0.5, unit: 'tsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'lime', qty: 1, unit: 'each' },
    ],
    steps: [
      'Simmer broth with ginger, garlic, soy sauce, and five spice for 15 minutes.',
      'Cook the rice noodles separately according to package directions; divide among bowls.',
      'Strain the broth if desired, then ladle over the noodles.',
      'Top with the thinly sliced raw beef (it will cook in the hot broth), green onion, and cilantro. Serve with lime.',
    ],
  },
  {
    slug: 'mac-and-cheese',
    title: 'Stovetop Mac and Cheese',
    summary: 'Creamy, comforting homemade macaroni and cheese.',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 20,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'pasta_penne', qty: 340, unit: 'g' },
      { slug: 'butter', qty: 3, unit: 'tbsp' },
      { slug: 'all_purpose_flour', qty: 3, unit: 'tbsp' },
      { slug: 'milk', qty: 2, unit: 'cup' },
      { slug: 'cheddar_cheese', qty: 2, unit: 'cup', prepNote: 'shredded' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.25, unit: 'tsp' },
    ],
    steps: [
      'Cook the pasta according to package directions.',
      'Melt butter in a saucepan, whisk in flour, and cook 1 minute.',
      'Gradually whisk in milk and simmer until thickened, about 4-5 minutes.',
      'Remove from heat, stir in cheddar until melted, and season with salt and pepper.',
      'Toss with the cooked pasta.',
    ],
  },
  {
    slug: 'peanut-noodles-with-vegetables',
    title: 'Peanut Noodles with Vegetables',
    summary: 'Cold or warm noodles tossed in a creamy peanut sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 10,
    cuisine: 'Thai',
    difficulty: 1,
    mealSlots: ['lunch', 'dinner'],
    ingredients: [
      { slug: 'spaghetti', qty: 300, unit: 'g' },
      { slug: 'peanut_butter', qty: 3, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'rice_vinegar', qty: 1, unit: 'tbsp' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'julienned' },
      { slug: 'cucumber', qty: 0.5, unit: 'each', prepNote: 'julienned' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'peanuts_roasted', qty: 0.25, unit: 'cup', optional: true },
    ],
    steps: [
      'Cook the pasta according to package directions; rinse under cold water if serving cold.',
      'Whisk peanut butter, soy sauce, honey, rice vinegar, and garlic with a splash of warm water until smooth.',
      'Toss the noodles with the sauce, carrot, and cucumber.',
      'Top with green onion and peanuts.',
    ],
  },
]
