// Pasta & noodle family — a rotating-protein base, spanning Italian and
// Asian noodle dishes.

export const recipes = [
  {
    slug: 'pasta-primavera',
    title: 'Pasta Primavera',
    summary: 'Penne tossed with a rainbow of sautéed spring vegetables.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    cuisine: 'Italian',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pasta_penne', qty: 340, unit: 'g' },
      { slug: 'zucchini', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each' },
      { slug: 'cherry_tomatoes', qty: 1.5, unit: 'cup' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'olive_oil', qty: 3, unit: 'tbsp' },
      { slug: 'parmesan_cheese', qty: 0.5, unit: 'cup', prepNote: 'grated' },
      { slug: 'basil_fresh', qty: 0.25, unit: 'cup' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook pasta according to package directions, reserving 0.5 cup pasta water.',
      'Heat oil in a large skillet; sauté garlic, zucchini, and bell pepper 5 minutes.',
      'Add cherry tomatoes and cook 3-4 minutes until they soften.',
      'Toss with the pasta, a splash of pasta water, parmesan, basil, and salt.',
    ],
  },
  {
    slug: 'pad-thai-style-noodles',
    title: 'Pad Thai-Style Noodles',
    summary: 'Stir-fried rice noodles with egg and peanuts in a tangy sauce.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 12,
    cuisine: 'Thai',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'rice_noodles', qty: 300, unit: 'g' },
      { slug: 'egg', qty: 2, unit: 'each' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'fish_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 1, unit: 'tbsp' },
      { slug: 'honey', qty: 2, unit: 'tbsp' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'peanuts_roasted', qty: 0.33, unit: 'cup' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'vegetable_oil', qty: 2, unit: 'tbsp' },
      { slug: 'bean_sprouts', qty: 1, unit: 'cup', optional: true },
    ],
    steps: [
      'Soak rice noodles in hot water according to package directions until pliable; drain.',
      'Whisk fish sauce, soy sauce, honey, and lime juice for the sauce.',
      'Heat oil in a wok; scramble the eggs softly and push to one side. Add garlic and noodles.',
      'Pour in the sauce and toss everything together over high heat for 2-3 minutes.',
      'Top with peanuts and green onion before serving.',
    ],
  },
  {
    slug: 'creamy-tomato-pasta',
    title: 'Creamy Tomato Pasta',
    summary: 'A quick, creamy tomato pasta with parmesan and basil.',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 20,
    cuisine: 'Italian',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pasta_penne', qty: 340, unit: 'g' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'tomato_canned_diced', qty: 2, unit: 'can' },
      { slug: 'heavy_cream', qty: 0.5, unit: 'cup' },
      { slug: 'parmesan_cheese', qty: 0.5, unit: 'cup', prepNote: 'grated' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'basil_dried', qty: 1, unit: 'tsp' },
      { slug: 'red_pepper_flakes', qty: 0.25, unit: 'tsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook pasta according to package directions.',
      'Heat oil; sauté garlic 30 seconds, then add diced tomatoes and basil. Simmer 10 minutes.',
      'Stir in cream and simmer 3-4 minutes until slightly thickened.',
      'Toss with the pasta and parmesan; season with salt and red pepper flakes.',
    ],
  },
  {
    slug: 'sesame-garlic-noodles',
    title: 'Sesame Garlic Noodles',
    summary: 'Fast, savory noodles in a garlicky sesame-soy sauce.',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 12,
    cuisine: 'Chinese',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'spaghetti', qty: 340, unit: 'g' },
      { slug: 'garlic', qty: 4, unit: 'clove' },
      { slug: 'soy_sauce', qty: 4, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 2, unit: 'tbsp' },
      { slug: 'rice_vinegar', qty: 1, unit: 'tbsp' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'red_pepper_flakes', qty: 0.25, unit: 'tsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'sesame_seeds', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook the spaghetti according to package directions.',
      'Whisk garlic, soy sauce, sesame oil, rice vinegar, honey, and red pepper flakes.',
      'Toss the hot pasta with the sauce until coated.',
      'Top with green onion and sesame seeds.',
    ],
  },
  {
    slug: 'pasta-e-fagioli',
    title: 'Pasta e Fagioli',
    summary: 'A rustic Italian pasta and bean soup.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    cuisine: 'Italian',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'pasta_penne', qty: 150, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'celery', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'pinto_beans_canned', qty: 2, unit: 'can' },
      { slug: 'vegetable_broth', qty: 3, unit: 'cup' },
      { slug: 'italian_seasoning', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'parmesan_cheese', qty: 0.33, unit: 'cup', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; soften onion, garlic, carrot, and celery, about 6 minutes.',
      'Add diced tomatoes, one can of beans, and broth. Mash the second can of beans and stir in for creaminess.',
      'Add italian seasoning and simmer 15 minutes.',
      'Add the pasta and cook until al dente, about 10 minutes. Season with salt and top with parmesan.',
    ],
  },
  {
    slug: 'beef-and-noodle-soup',
    title: 'Beef and Noodle Soup',
    summary: 'A comforting brothy soup with thin noodles and vegetables.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Vietnamese',
    difficulty: 2,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'beef_sirloin', qty: 400, unit: 'g', prepNote: 'thinly sliced' },
      { slug: 'rice_noodles', qty: 250, unit: 'g' },
      { slug: 'chicken_broth', qty: 2, unit: 'can' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'soy_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'five_spice', qty: 0.5, unit: 'tsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'lime', qty: 1, unit: 'each' },
    ],
    steps: [
      'Simmer broth with ginger, garlic, soy sauce, and five spice for 15 minutes.',
      'Cook the rice noodles separately according to package directions; divide among bowls.',
      'Strain the broth if desired, then ladle over the noodles.',
      'Top with the thinly sliced raw beef (it will cook in the hot broth), green onion, and cilantro. Serve with lime.',
    ],
  },
  {
    slug: 'mac-and-cheese',
    title: 'Stovetop Mac and Cheese',
    summary: 'Creamy, comforting homemade macaroni and cheese.',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 20,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'pasta_penne', qty: 340, unit: 'g' },
      { slug: 'butter', qty: 3, unit: 'tbsp' },
      { slug: 'all_purpose_flour', qty: 3, unit: 'tbsp' },
      { slug: 'milk', qty: 2, unit: 'cup' },
      { slug: 'cheddar_cheese', qty: 2, unit: 'cup', prepNote: 'shredded' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.25, unit: 'tsp' },
    ],
    steps: [
      'Cook the pasta according to package directions.',
      'Melt butter in a saucepan, whisk in flour, and cook 1 minute.',
      'Gradually whisk in milk and simmer until thickened, about 4-5 minutes.',
      'Remove from heat, stir in cheddar until melted, and season with salt and pepper.',
      'Toss with the cooked pasta.',
    ],
  },
  {
    slug: 'peanut-noodles-with-vegetables',
    title: 'Peanut Noodles with Vegetables',
    summary: 'Cold or warm noodles tossed in a creamy peanut sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 10,
    cuisine: 'Thai',
    difficulty: 1,
    mealSlots: ['lunch', 'dinner'],
    ingredients: [
      { slug: 'spaghetti', qty: 300, unit: 'g' },
      { slug: 'peanut_butter', qty: 3, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'rice_vinegar', qty: 1, unit: 'tbsp' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'julienned' },
      { slug: 'cucumber', qty: 0.5, unit: 'each', prepNote: 'julienned' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'peanuts_roasted', qty: 0.25, unit: 'cup', optional: true },
    ],
    steps: [
      'Cook the pasta according to package directions; rinse under cold water if serving cold.',
      'Whisk peanut butter, soy sauce, honey, rice vinegar, and garlic with a splash of warm water until smooth.',
      'Toss the noodles with the sauce, carrot, and cucumber.',
      'Top with green onion and peanuts.',
    ],
  },
  {
    slug: 'cajun-pasta',
    title: 'Cajun-Spiced Pasta',
    summary: 'Creamy penne with a smoky, spiced Cajun-style sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'Cajun',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pasta_penne', qty: 340, unit: 'g' },
      { slug: 'chicken_breast', qty: 400, unit: 'g', prepNote: 'sliced' },
      { slug: 'smoked_paprika', qty: 1.5, unit: 'tsp' },
      { slug: 'cayenne_pepper', qty: 0.5, unit: 'tsp' },
      { slug: 'garlic_powder', qty: 1, unit: 'tsp' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each' },
      { slug: 'heavy_cream', qty: 0.75, unit: 'cup' },
      { slug: 'parmesan_cheese', qty: 0.5, unit: 'cup', prepNote: 'grated' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook pasta according to package directions.',
      'Toss chicken with smoked paprika, cayenne, garlic powder, and salt. Sear in oil until cooked through, about 7 minutes; remove.',
      'Add bell pepper to the pan and cook 4 minutes, then stir in cream and simmer 2-3 minutes.',
      'Return the chicken to the pan, toss with pasta and parmesan, and serve.',
    ],
  },
  {
    slug: 'greek-pastitsio-style-bake',
    title: 'Greek-Style Pasta Bake',
    summary: 'Baked pasta with spiced beef and a creamy cheese topping.',
    servings: 6,
    prepMinutes: 15,
    cookMinutes: 35,
    cuisine: 'Greek',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pasta_penne', qty: 400, unit: 'g' },
      { slug: 'ground_beef', qty: 500, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'cinnamon', qty: 0.5, unit: 'tsp' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'milk', qty: 1, unit: 'cup' },
      { slug: 'all_purpose_flour', qty: 2, unit: 'tbsp' },
      { slug: 'butter', qty: 2, unit: 'tbsp' },
      { slug: 'parmesan_cheese', qty: 0.5, unit: 'cup', prepNote: 'grated' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 375°F (190°C). Cook pasta according to package directions.',
      'Heat oil; brown beef and onion, about 7 minutes. Stir in cinnamon and diced tomatoes; simmer 10 minutes.',
      'Melt butter, whisk in flour, then gradually add milk; simmer until thickened, about 4 minutes. Stir in parmesan.',
      'Layer pasta and meat sauce in a baking dish, top with the cheese sauce, and bake 20-25 minutes until golden.',
    ],
  },
  {
    slug: 'japanese-yaki-udon-style',
    title: 'Yaki Udon-Style Noodles',
    summary: 'Stir-fried noodles with vegetables in a savory soy-based sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Japanese',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'spaghetti', qty: 340, unit: 'g', prepNote: 'or udon noodles if available' },
      { slug: 'cabbage', qty: 0.25, unit: 'each', prepNote: 'shredded' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'oyster_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 2, unit: 'tbsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
    ],
    steps: [
      'Cook the noodles according to package directions.',
      'Heat oil in a wok; stir-fry cabbage, carrot, and garlic 4-5 minutes.',
      'Add the noodles, soy sauce, and oyster sauce; toss over high heat 2-3 minutes.',
      'Finish with sesame oil and green onion.',
    ],
  },
  {
    slug: 'korean-japchae',
    title: 'Japchae-Style Glass Noodles',
    summary: 'Sweet-savory stir-fried noodles with vegetables, Korean-style.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    cuisine: 'Korean',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'rice_noodles', qty: 300, unit: 'g' },
      { slug: 'spinach', qty: 100, unit: 'g' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'julienned' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'soy_sauce', qty: 4, unit: 'tbsp' },
      { slug: 'brown_sugar', qty: 1, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 2, unit: 'tbsp' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
      { slug: 'sesame_seeds', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook the noodles according to package directions; toss with 1 tbsp sesame oil.',
      'Heat vegetable oil; stir-fry carrot and bell pepper 3-4 minutes, then add spinach and garlic until wilted.',
      'Whisk soy sauce, brown sugar, and remaining sesame oil.',
      'Toss the noodles and vegetables with the sauce. Top with sesame seeds.',
    ],
  },
  {
    slug: 'french-garlic-butter-pasta',
    title: 'French Herb and Garlic Butter Pasta',
    summary: 'Simple pasta tossed in herbed garlic butter and parmesan.',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 15,
    cuisine: 'French',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'spaghetti', qty: 340, unit: 'g' },
      { slug: 'butter', qty: 4, unit: 'tbsp' },
      { slug: 'garlic', qty: 4, unit: 'clove' },
      { slug: 'parsley', qty: 3, unit: 'tbsp' },
      { slug: 'thyme_dried', qty: 0.5, unit: 'tsp' },
      { slug: 'parmesan_cheese', qty: 0.5, unit: 'cup', prepNote: 'grated' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Cook pasta according to package directions, reserving 0.5 cup pasta water.',
      'Melt butter in a large pan; sauté garlic and thyme 1 minute.',
      'Toss the pasta with the garlic butter, a splash of pasta water, parmesan, salt, and pepper.',
      'Finish with fresh parsley.',
    ],
  },
  {
    slug: 'chicken-alfredo',
    title: 'Chicken Alfredo',
    summary: 'Creamy parmesan sauce with tender chicken over fettuccine-style pasta.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'Italian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'spaghetti', qty: 340, unit: 'g' },
      { slug: 'chicken_breast', qty: 500, unit: 'g' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'heavy_cream', qty: 1, unit: 'cup' },
      { slug: 'parmesan_cheese', qty: 0.75, unit: 'cup', prepNote: 'grated' },
      { slug: 'butter', qty: 2, unit: 'tbsp' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Cook pasta according to package directions.',
      'Season chicken with salt and pepper; sear in oil, 5-6 minutes per side, until cooked through. Slice.',
      'Melt butter in the same pan; sauté garlic 30 seconds, then add cream and simmer 3-4 minutes.',
      'Stir in parmesan until melted and smooth. Toss with pasta and sliced chicken.',
    ],
  },
  {
    slug: 'shrimp-linguine',
    title: 'Shrimp Linguine in White Sauce',
    summary: 'Shrimp and garlic in a light cream sauce over pasta.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'Italian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'spaghetti', qty: 340, unit: 'g' },
      { slug: 'shrimp', qty: 500, unit: 'g' },
      { slug: 'garlic', qty: 4, unit: 'clove' },
      { slug: 'heavy_cream', qty: 0.75, unit: 'cup' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'parmesan_cheese', qty: 0.5, unit: 'cup', prepNote: 'grated' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'parsley', qty: 2, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook pasta according to package directions.',
      'Heat oil; sauté garlic 30 seconds, add shrimp, and cook 2-3 minutes per side until pink.',
      'Add cream and lemon juice; simmer 2-3 minutes.',
      'Toss with pasta and parmesan; season with salt and top with parsley.',
    ],
  },
]
