// Pork family — chops, tenderloin, ground pork.

export const recipes = [
  {
    slug: 'cuban-style-pork-tenderloin',
    title: 'Cuban-Style Pork Tenderloin',
    summary: 'Citrus-garlic marinated pork tenderloin, roasted until juicy.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 25,
    cuisine: 'Cuban',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pork_tenderloin', qty: 700, unit: 'g' },
      { slug: 'lime', qty: 2, unit: 'each' },
      { slug: 'garlic', qty: 4, unit: 'clove' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'oregano_dried', qty: 1, unit: 'tsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'black_beans_canned', qty: 1, unit: 'can' },
      { slug: 'salt', qty: 1.5, unit: 'tsp' },
    ],
    steps: [
      'Whisk lime juice, minced garlic, cumin, oregano, olive oil, and salt. Marinate the pork at least 15 minutes.',
      'Preheat oven to 400°F (200°C). Sear the pork in an oven-safe pan on all sides, about 5 minutes total.',
      'Transfer to the oven and roast 15-18 minutes until internal temperature reaches 145°F (63°C). Rest 5 minutes before slicing.',
      'Cook rice according to package directions and warm the black beans.',
      'Serve sliced pork over rice and beans.',
    ],
  },
  {
    slug: 'pork-chops-with-apple',
    title: 'Skillet Pork Chops with Apple',
    summary: 'Seared pork chops with a quick apple and onion pan sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'American',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pork_chop', qty: 700, unit: 'g' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'butter', qty: 2, unit: 'tbsp' },
      { slug: 'thyme_dried', qty: 1, unit: 'tsp' },
      { slug: 'chicken_broth', qty: 0.5, unit: 'cup' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Season pork chops with salt and pepper. Sear in olive oil over medium-high heat, 4-5 minutes per side; remove.',
      'Add butter, onion, and thyme to the pan; cook 5 minutes until softened.',
      'Pour in broth, scraping up browned bits, and simmer 3 minutes.',
      'Return the chops to the pan, spoon the sauce over, and warm through.',
    ],
  },
  {
    slug: 'char-siu-style-pork',
    title: 'Char Siu-Style Pork Tenderloin',
    summary: 'Sweet and savory glazed roasted pork, Chinese barbecue style.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Chinese',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pork_tenderloin', qty: 700, unit: 'g' },
      { slug: 'hoisin_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'honey', qty: 2, unit: 'tbsp' },
      { slug: 'five_spice', qty: 0.5, unit: 'tsp' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
    ],
    steps: [
      'Whisk hoisin, soy sauce, honey, five spice, and minced garlic. Marinate the pork at least 15 minutes.',
      'Preheat oven to 400°F (200°C). Roast the pork on a lined tray for 20-25 minutes, basting with marinade twice, until internal temp reaches 145°F (63°C).',
      'Rest 5 minutes, then slice.',
      'Cook rice according to package directions and serve the pork over rice, topped with green onion.',
    ],
  },
  {
    slug: 'pork-carnitas-bowl',
    title: 'Pork Carnitas Bowl',
    summary: 'Slow-braised, crisped pork with rice, beans, and lime.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 90,
    cuisine: 'Mexican',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pork_tenderloin', qty: 800, unit: 'g' },
      { slug: 'lime', qty: 2, unit: 'each' },
      { slug: 'garlic', qty: 4, unit: 'clove' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'oregano_dried', qty: 1, unit: 'tsp' },
      { slug: 'chicken_broth', qty: 1, unit: 'cup' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'black_beans_canned', qty: 1, unit: 'can' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1.5, unit: 'tsp' },
    ],
    steps: [
      'Season the pork with cumin, oregano, and salt. Sear in oil on all sides, about 6 minutes.',
      'Add garlic, lime juice, and broth. Cover and simmer on low 75-90 minutes until the pork shreds easily.',
      'Shred the pork and crisp it under a broiler for 3-4 minutes, or in a hot pan.',
      'Cook rice according to package directions and warm the beans.',
      'Serve the pork over rice and beans with extra lime.',
    ],
  },
  {
    slug: 'pork-and-vegetable-dumplings-skillet',
    title: 'Pork and Cabbage Stir-Fry',
    summary: 'Ground pork stir-fried with cabbage in a garlicky soy sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'Chinese',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_pork', qty: 500, unit: 'g' },
      { slug: 'cabbage', qty: 0.5, unit: 'each', prepNote: 'shredded' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'rice_vinegar', qty: 1, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Heat oil in a wok; brown the ground pork with garlic and ginger, about 6 minutes.',
      'Add shredded cabbage and stir-fry 4-5 minutes until wilted but still with some crunch.',
      'Stir in soy sauce, rice vinegar, and sesame oil. Serve over rice.',
    ],
  },
  {
    slug: 'italian-sausage-and-peppers-skillet',
    title: 'Italian-Style Pork and Peppers Skillet',
    summary: 'Ground pork seasoned Italian-style with peppers and onions.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'Italian',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_pork', qty: 500, unit: 'g' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each' },
      { slug: 'bell_pepper_green', qty: 1, unit: 'each' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'italian_seasoning', qty: 1.5, unit: 'tsp' },
      { slug: 'red_pepper_flakes', qty: 0.25, unit: 'tsp' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'pasta_penne', qty: 300, unit: 'g' },
      { slug: 'parmesan_cheese', qty: 0.33, unit: 'cup', prepNote: 'grated' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook pasta according to package directions.',
      'Heat oil in a large skillet; brown the ground pork with italian seasoning and red pepper flakes, about 7 minutes.',
      'Add peppers, onion, and garlic; cook 6-7 minutes until softened.',
      'Toss with the cooked pasta, season with salt, and top with parmesan.',
    ],
  },
  {
    slug: 'honey-garlic-pork-chops',
    title: 'Honey Garlic Pork Chops',
    summary: 'Pan-seared pork chops glazed with a sticky honey-garlic sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pork_chop', qty: 700, unit: 'g' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'honey', qty: 3, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'green_beans', qty: 300, unit: 'g' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Season pork chops with salt and pepper. Sear in oil over medium-high heat, 4-5 minutes per side; remove.',
      'Add garlic to the pan, then honey and soy sauce; simmer 1-2 minutes until slightly thickened.',
      'Return the chops to the pan and coat in the glaze.',
      'Steam the green beans and serve alongside.',
    ],
  },
  {
    slug: 'filipino-pork-adobo',
    title: 'Pork Adobo',
    summary: 'Tangy, savory braised pork in a soy-vinegar sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 40,
    cuisine: 'Filipino',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pork_chop', qty: 700, unit: 'g', prepNote: 'cut into chunks' },
      { slug: 'soy_sauce', qty: 0.33, unit: 'cup' },
      { slug: 'rice_vinegar', qty: 0.25, unit: 'cup' },
      { slug: 'garlic', qty: 5, unit: 'clove' },
      { slug: 'bay_leaf', qty: 2, unit: 'each' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
      { slug: 'brown_sugar', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
    ],
    steps: [
      'Combine pork, soy sauce, vinegar, garlic, bay leaves, and black pepper in a pot. Marinate 10 minutes if time allows.',
      'Bring to a simmer, cover, and cook 25 minutes.',
      'Uncover, stir in brown sugar, and simmer 10-15 more minutes until the sauce reduces and thickens.',
      'Cook rice and serve the pork and sauce over it.',
    ],
  },
  {
    slug: 'vietnamese-pork-banh-mi-bowl',
    title: 'Vietnamese Pork Bánh Mì Bowl',
    summary: 'Caramelized pork over rice with quick-pickled vegetables.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    cuisine: 'Vietnamese',
    difficulty: 2,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'ground_pork', qty: 500, unit: 'g' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'fish_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'honey', qty: 2, unit: 'tbsp' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'julienned' },
      { slug: 'cucumber', qty: 0.5, unit: 'each', prepNote: 'julienned' },
      { slug: 'rice_vinegar', qty: 2, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'cilantro', qty: 0.25, unit: 'cup' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
    ],
    steps: [
      'Toss carrot and cucumber with rice vinegar; let sit while you cook (a quick pickle).',
      'Cook rice according to package directions.',
      'Heat oil; brown the pork with garlic, about 7 minutes.',
      'Stir in fish sauce and honey; cook 2-3 minutes until caramelized and sticky.',
      'Serve over rice with the quick-pickled vegetables and cilantro.',
    ],
  },
  {
    slug: 'german-pork-schnitzel',
    title: 'Pan-Fried Pork Schnitzel',
    summary: 'Crispy breaded pork cutlets with a squeeze of lemon.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    cuisine: 'German',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pork_chop', qty: 700, unit: 'g', prepNote: 'pounded thin' },
      { slug: 'all_purpose_flour', qty: 0.5, unit: 'cup' },
      { slug: 'egg', qty: 2, unit: 'each' },
      { slug: 'panko_breadcrumbs', qty: 1, unit: 'cup' },
      { slug: 'vegetable_oil', qty: 4, unit: 'tbsp' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'potato', qty: 4, unit: 'each' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Boil the potatoes until tender.',
      'Season pork with salt and pepper. Dredge in flour, then beaten egg, then breadcrumbs.',
      'Pan-fry in oil, 3-4 minutes per side, until golden and cooked through.',
      'Serve with the boiled potatoes and a squeeze of lemon.',
    ],
  },
  {
    slug: 'thai-basil-pork',
    title: 'Thai Basil Pork',
    summary: 'Spicy stir-fried ground pork with garlic and fresh basil.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Thai',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'ground_pork', qty: 500, unit: 'g' },
      { slug: 'garlic', qty: 4, unit: 'clove' },
      { slug: 'red_pepper_flakes', qty: 0.5, unit: 'tsp' },
      { slug: 'fish_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 1, unit: 'tbsp' },
      { slug: 'basil_fresh', qty: 1, unit: 'cup' },
      { slug: 'vegetable_oil', qty: 2, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'egg', qty: 4, unit: 'each', optional: true, prepNote: 'fried, to top' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Heat oil; fry garlic and red pepper flakes 30 seconds.',
      'Add ground pork and stir-fry until cooked through, about 7 minutes.',
      'Stir in fish sauce and soy sauce; cook 1 minute, then remove from heat and stir in basil.',
      'Serve over rice, topped with a fried egg if desired.',
    ],
  },
  {
    slug: 'pork-and-apple-skillet',
    title: 'Pork and Apple Skillet',
    summary: 'Pan-seared pork chops with sautéed apple and onion.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'American',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pork_chop', qty: 700, unit: 'g' },
      { slug: 'apple', qty: 2, unit: 'each', prepNote: 'sliced' },
      { slug: 'onion', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'butter', qty: 2, unit: 'tbsp' },
      { slug: 'cinnamon', qty: 0.25, unit: 'tsp' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Season pork with salt and pepper; sear in oil, 4-5 minutes per side; remove.',
      'Add butter, onion, and apple to the pan with cinnamon; cook 8-10 minutes until softened and lightly caramelized.',
      'Return the pork to the pan and warm through before serving.',
    ],
  },
  {
    slug: 'pork-ramen-bowl',
    title: 'Pork Ramen Bowl',
    summary: 'A savory noodle soup with tender pork and a soft egg.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Japanese',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pork_tenderloin', qty: 500, unit: 'g', prepNote: 'thinly sliced' },
      { slug: 'chicken_broth', qty: 2, unit: 'can' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'spaghetti', qty: 300, unit: 'g', prepNote: 'or ramen noodles if available' },
      { slug: 'egg', qty: 4, unit: 'each', prepNote: 'soft-boiled' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
    ],
    steps: [
      'Simmer broth with soy sauce, garlic, and ginger for 15 minutes.',
      'Sear the pork slices in oil, 2-3 minutes, until just cooked through.',
      'Cook the noodles according to package directions.',
      'Divide noodles among bowls, ladle over the broth, and top with pork, a halved soft-boiled egg, and green onion. Finish with sesame oil.',
    ],
  },
  {
    slug: 'pork-fried-rice',
    title: 'Pork Fried Rice',
    summary: 'Classic fried rice built around savory ground pork.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'Chinese',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'ground_pork', qty: 400, unit: 'g' },
      { slug: 'white_rice', qty: 3, unit: 'cup', prepNote: 'cooked and cooled' },
      { slug: 'egg', qty: 2, unit: 'each' },
      { slug: 'peas', qty: 0.5, unit: 'cup' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 2, unit: 'tbsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
    ],
    steps: [
      'Heat 1 tbsp oil; scramble the eggs softly and set aside.',
      'Add remaining oil, brown the pork with garlic, about 6 minutes.',
      'Add carrot and peas; cook 2-3 minutes.',
      'Add the rice, breaking up clumps, and stir-fry 3-4 minutes. Stir in soy sauce, sesame oil, and egg. Top with green onion.',
    ],
  },
  {
    slug: 'pork-souvlaki',
    title: 'Pork Souvlaki Skewers',
    summary: 'Greek-style grilled marinated pork skewers with pita.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 10,
    cuisine: 'Greek',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'pork_tenderloin', qty: 700, unit: 'g', prepNote: 'cubed' },
      { slug: 'lemon', qty: 2, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'oregano_dried', qty: 1.5, unit: 'tsp' },
      { slug: 'olive_oil', qty: 3, unit: 'tbsp' },
      { slug: 'pita_bread', qty: 4, unit: 'each' },
      { slug: 'greek_yogurt', qty: 0.5, unit: 'cup' },
      { slug: 'cucumber', qty: 0.5, unit: 'each', prepNote: 'diced' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Whisk lemon juice, garlic, oregano, oil, and salt. Marinate the pork at least 15 minutes.',
      'Thread onto skewers and grill or broil, turning occasionally, 8-10 minutes until cooked through.',
      'Mix yogurt with cucumber for a quick tzatziki-style sauce.',
      'Serve the skewers with warm pita and the yogurt sauce.',
    ],
  },
]
