// Shrimp family.

export const recipes = [
  {
    slug: 'garlic-shrimp-scampi',
    title: 'Garlic Shrimp Scampi',
    summary: 'Shrimp sautéed in garlic butter and white wine-style broth over pasta.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Italian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'shrimp', qty: 600, unit: 'g' },
      { slug: 'garlic', qty: 4, unit: 'clove' },
      { slug: 'butter', qty: 3, unit: 'tbsp' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'red_pepper_flakes', qty: 0.25, unit: 'tsp' },
      { slug: 'parsley', qty: 2, unit: 'tbsp' },
      { slug: 'spaghetti', qty: 300, unit: 'g' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook spaghetti according to package directions, reserving 0.5 cup of pasta water.',
      'Heat oil and half the butter in a large skillet. Sauté garlic and red pepper flakes 30 seconds.',
      'Add shrimp and cook 2-3 minutes per side until pink and opaque.',
      'Stir in lemon juice, remaining butter, and a splash of pasta water. Toss with the pasta and parsley.',
      'Season with salt and serve.',
    ],
  },
  {
    slug: 'shrimp-tacos',
    title: 'Chili-Lime Shrimp Tacos',
    summary: 'Spiced shrimp in warm tortillas with a bright slaw.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 8,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'shrimp', qty: 600, unit: 'g' },
      { slug: 'chili_powder', qty: 1, unit: 'tsp' },
      { slug: 'cumin', qty: 0.5, unit: 'tsp' },
      { slug: 'lime', qty: 2, unit: 'each' },
      { slug: 'cabbage', qty: 0.25, unit: 'each', prepNote: 'shredded' },
      { slug: 'mayonnaise', qty: 2, unit: 'tbsp' },
      { slug: 'tortilla_corn', qty: 8, unit: 'each' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Toss shrimp with chili powder, cumin, salt, and juice of one lime.',
      'Mix shredded cabbage with mayonnaise and remaining lime juice for the slaw.',
      'Sear the shrimp in oil over high heat, 2 minutes per side, until pink and opaque.',
      'Warm the tortillas and fill with shrimp and slaw. Top with cilantro.',
    ],
  },
  {
    slug: 'shrimp-fried-rice',
    title: 'Shrimp Fried Rice',
    summary: 'Classic fried rice with shrimp, egg, and vegetables.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'Chinese',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'shrimp', qty: 500, unit: 'g' },
      { slug: 'white_rice', qty: 2, unit: 'cup', prepNote: 'cooked and cooled' },
      { slug: 'egg', qty: 2, unit: 'each' },
      { slug: 'peas', qty: 0.5, unit: 'cup' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 2, unit: 'tbsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
    ],
    steps: [
      'Heat 1 tbsp oil in a wok; scramble the eggs and set aside.',
      'Add remaining oil, sauté garlic, carrot, and peas 2 minutes.',
      'Add shrimp and cook 2-3 minutes until pink.',
      'Add the cooked rice, breaking up clumps, and stir-fry 3-4 minutes.',
      'Stir in soy sauce, sesame oil, scrambled egg, and green onion. Toss to combine and serve.',
    ],
  },
  {
    slug: 'shrimp-and-grits',
    title: 'Shrimp and Grits',
    summary: 'Creamy grits topped with garlicky, spiced shrimp.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'American',
    difficulty: 2,
    mealSlots: ['dinner', 'breakfast'],
    ingredients: [
      { slug: 'shrimp', qty: 500, unit: 'g' },
      { slug: 'quinoa', qty: 1, unit: 'cup', prepNote: 'uncooked, as a grits substitute' },
      { slug: 'milk', qty: 1, unit: 'cup' },
      { slug: 'cheddar_cheese', qty: 0.5, unit: 'cup', prepNote: 'shredded' },
      { slug: 'butter', qty: 2, unit: 'tbsp' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'smoked_paprika', qty: 1, unit: 'tsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook quinoa in milk and 1 cup water until creamy, about 15 minutes; stir in cheddar and half the butter.',
      'Season shrimp with smoked paprika and salt.',
      'Heat oil and remaining butter; sauté garlic 30 seconds, add shrimp, and cook 2-3 minutes per side until pink.',
      'Spoon shrimp over the creamy quinoa and top with green onion.',
    ],
  },
  {
    slug: 'coconut-shrimp-curry',
    title: 'Coconut Shrimp Curry',
    summary: 'Quick shrimp curry in a fragrant coconut-curry sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'Thai',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'shrimp', qty: 600, unit: 'g' },
      { slug: 'curry_paste', qty: 2, unit: 'tbsp' },
      { slug: 'coconut_milk', qty: 1, unit: 'can' },
      { slug: 'fish_sauce', qty: 1, unit: 'tbsp' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'basil_fresh', qty: 0.25, unit: 'cup', optional: true },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Heat oil; fry the curry paste 1 minute until fragrant.',
      'Add coconut milk and fish sauce; simmer 5 minutes.',
      'Add bell pepper and shrimp; simmer 5-6 minutes until the shrimp are pink and opaque.',
      'Finish with lime juice and basil, and serve over rice.',
    ],
  },
  {
    slug: 'shrimp-and-veggie-skewers',
    title: 'Greek Shrimp and Vegetable Skewers',
    summary: 'Grilled lemon-herb shrimp and vegetable skewers.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 8,
    cuisine: 'Mediterranean',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'shrimp', qty: 600, unit: 'g' },
      { slug: 'zucchini', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'cherry_tomatoes', qty: 1, unit: 'cup' },
      { slug: 'red_onion', qty: 1, unit: 'each', prepNote: 'cubed' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'oregano_dried', qty: 1, unit: 'tsp' },
      { slug: 'feta_cheese', qty: 0.33, unit: 'cup', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Whisk olive oil, lemon juice, garlic, oregano, and salt. Toss with shrimp and vegetables.',
      'Thread onto skewers, alternating shrimp and vegetables.',
      'Grill or broil 3-4 minutes per side until the shrimp are pink and opaque.',
      'Sprinkle with feta if using and serve.',
    ],
  },
  {
    slug: 'cajun-shrimp-and-rice',
    title: 'Cajun Shrimp and Rice',
    summary: 'Blackened shrimp with peppers over rice.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'Cajun',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'shrimp', qty: 600, unit: 'g' },
      { slug: 'smoked_paprika', qty: 1.5, unit: 'tsp' },
      { slug: 'cayenne_pepper', qty: 0.5, unit: 'tsp' },
      { slug: 'garlic_powder', qty: 1, unit: 'tsp' },
      { slug: 'bell_pepper_green', qty: 1, unit: 'each' },
      { slug: 'celery', qty: 1, unit: 'each' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Toss shrimp with smoked paprika, cayenne, garlic powder, and salt.',
      'Heat oil; sauté bell pepper, celery, and onion, about 6 minutes.',
      'Add shrimp and cook 3-4 minutes until pink and opaque. Serve over rice.',
    ],
  },
  {
    slug: 'spanish-shrimp-and-rice',
    title: 'Spanish-Style Shrimp and Rice',
    summary: 'A simplified paella-inspired one-pot shrimp and rice.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    cuisine: 'Spanish',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'shrimp', qty: 500, unit: 'g' },
      { slug: 'white_rice', qty: 1.5, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each' },
      { slug: 'smoked_paprika', qty: 1, unit: 'tsp' },
      { slug: 'tomato_canned_diced', qty: 1, unit: 'can' },
      { slug: 'chicken_broth', qty: 2, unit: 'cup' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil in a wide pan; soften onion, garlic, and bell pepper, about 6 minutes.',
      'Stir in smoked paprika, rice, diced tomatoes, and broth.',
      'Bring to a simmer, cover, and cook 15 minutes.',
      'Nestle the shrimp into the rice and cook 5 more minutes until pink and the rice is tender. Serve with lemon.',
    ],
  },
  {
    slug: 'vietnamese-shrimp-summer-rolls',
    title: 'Vietnamese Shrimp Summer Rolls',
    summary: 'Fresh rice-paper rolls with shrimp, herbs, and peanut dip.',
    servings: 4,
    prepMinutes: 25,
    cookMinutes: 5,
    cuisine: 'Vietnamese',
    difficulty: 3,
    mealSlots: ['lunch'],
    ingredients: [
      { slug: 'shrimp', qty: 400, unit: 'g' },
      { slug: 'rice_noodles', qty: 100, unit: 'g' },
      { slug: 'lettuce_romaine', qty: 1, unit: 'cup', prepNote: 'shredded' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'julienned' },
      { slug: 'cucumber', qty: 0.5, unit: 'each', prepNote: 'julienned' },
      { slug: 'cilantro', qty: 0.25, unit: 'cup' },
      { slug: 'peanut_butter', qty: 2, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 1, unit: 'tbsp' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'honey', qty: 1, unit: 'tsp' },
      { slug: 'rice_paper_wrapper', qty: 8, unit: 'each' },
    ],
    steps: [
      'Boil the shrimp 2-3 minutes until pink; halve lengthwise once cool. Cook rice noodles according to package directions.',
      'Whisk peanut butter, soy sauce, lime juice, and honey with a splash of warm water for the dipping sauce.',
      'Dip rice paper wrappers briefly in warm water to soften.',
      'Layer shrimp, noodles, lettuce, carrot, cucumber, and cilantro on each wrapper and roll tightly.',
      'Serve with the peanut dipping sauce.',
    ],
  },
  {
    slug: 'shrimp-avocado-salad',
    title: 'Shrimp and Avocado Salad',
    summary: 'A light, refreshing lunch salad with lime dressing.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 5,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['lunch'],
    ingredients: [
      { slug: 'shrimp', qty: 300, unit: 'g' },
      { slug: 'avocado', qty: 1, unit: 'each' },
      { slug: 'lettuce_romaine', qty: 3, unit: 'cup', prepNote: 'chopped' },
      { slug: 'cherry_tomatoes', qty: 1, unit: 'cup' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'salt', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Boil or sear the shrimp until pink and opaque, about 3-4 minutes.',
      'Whisk olive oil, lime juice, and salt for the dressing.',
      'Toss lettuce and cherry tomatoes with the dressing.',
      'Top with shrimp and sliced avocado.',
    ],
  },
  {
    slug: 'shrimp-pad-see-ew',
    title: 'Shrimp Pad See Ew',
    summary: 'Wide rice noodles stir-fried with shrimp and Chinese broccoli in a sweet soy sauce.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 12,
    cuisine: 'Thai',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'shrimp', qty: 500, unit: 'g' },
      { slug: 'rice_noodles', qty: 300, unit: 'g' },
      { slug: 'broccoli', qty: 250, unit: 'g' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'egg', qty: 2, unit: 'each' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'oyster_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'vegetable_oil', qty: 2, unit: 'tbsp' },
    ],
    steps: [
      'Cook rice noodles according to package directions.',
      'Heat oil in a wok; scramble the eggs softly and push aside. Add garlic and shrimp; cook 2-3 minutes.',
      'Add broccoli and stir-fry 3 minutes.',
      'Add the noodles, soy sauce, oyster sauce, and honey; toss over high heat 2-3 minutes until well combined.',
    ],
  },
  {
    slug: 'shrimp-ceviche',
    title: 'Shrimp Ceviche',
    summary: 'Citrus-marinated shrimp with tomato, onion, and cilantro.',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 3,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['lunch'],
    ingredients: [
      { slug: 'shrimp', qty: 500, unit: 'g', prepNote: 'peeled and chopped' },
      { slug: 'lime', qty: 4, unit: 'each' },
      { slug: 'tomato', qty: 2, unit: 'each', prepNote: 'diced' },
      { slug: 'red_onion', qty: 0.5, unit: 'each', prepNote: 'diced' },
      { slug: 'jalapeno', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'cilantro', qty: 0.25, unit: 'cup' },
      { slug: 'avocado', qty: 1, unit: 'each' },
      { slug: 'tortilla_corn', qty: 8, unit: 'each', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Briefly boil the shrimp 2-3 minutes until pink; cool and chop.',
      'Toss with lime juice, tomato, red onion, jalapeño, cilantro, and salt.',
      'Chill 10 minutes to let the flavors meld.',
      'Top with avocado and serve with tortilla chips.',
    ],
  },
  {
    slug: 'shrimp-tacos-with-mango',
    title: 'Shrimp Tacos with Pineapple Salsa',
    summary: 'Sweet-savory shrimp tacos with a bright fruit salsa.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 8,
    cuisine: 'Caribbean',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'shrimp', qty: 600, unit: 'g' },
      { slug: 'chili_powder', qty: 1, unit: 'tsp' },
      { slug: 'lime', qty: 2, unit: 'each' },
      { slug: 'tomato', qty: 1, unit: 'each', prepNote: 'diced, or pineapple if available' },
      { slug: 'red_onion', qty: 0.25, unit: 'each', prepNote: 'diced' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp' },
      { slug: 'tortilla_corn', qty: 8, unit: 'each' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Toss shrimp with chili powder and salt.',
      'Mix diced tomato, red onion, cilantro, and juice of one lime for the salsa.',
      'Sear the shrimp in oil, 2 minutes per side, until pink and opaque.',
      'Warm the tortillas and fill with shrimp and salsa. Serve with remaining lime.',
    ],
  },
]
