// Shrimp family.

export const recipes = [
  {
    slug: 'garlic-shrimp-scampi',
    title: 'Garlic Shrimp Scampi',
    summary: 'Shrimp sautéed in garlic butter and white wine-style broth over pasta.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Italian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'shrimp', qty: 600, unit: 'g' },
      { slug: 'garlic', qty: 4, unit: 'clove' },
      { slug: 'butter', qty: 3, unit: 'tbsp' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'red_pepper_flakes', qty: 0.25, unit: 'tsp' },
      { slug: 'parsley', qty: 2, unit: 'tbsp' },
      { slug: 'spaghetti', qty: 300, unit: 'g' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook spaghetti according to package directions, reserving 0.5 cup of pasta water.',
      'Heat oil and half the butter in a large skillet. Sauté garlic and red pepper flakes 30 seconds.',
      'Add shrimp and cook 2-3 minutes per side until pink and opaque.',
      'Stir in lemon juice, remaining butter, and a splash of pasta water. Toss with the pasta and parsley.',
      'Season with salt and serve.',
    ],
  },
  {
    slug: 'shrimp-tacos',
    title: 'Chili-Lime Shrimp Tacos',
    summary: 'Spiced shrimp in warm tortillas with a bright slaw.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 8,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'shrimp', qty: 600, unit: 'g' },
      { slug: 'chili_powder', qty: 1, unit: 'tsp' },
      { slug: 'cumin', qty: 0.5, unit: 'tsp' },
      { slug: 'lime', qty: 2, unit: 'each' },
      { slug: 'cabbage', qty: 0.25, unit: 'each', prepNote: 'shredded' },
      { slug: 'mayonnaise', qty: 2, unit: 'tbsp' },
      { slug: 'tortilla_corn', qty: 8, unit: 'each' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Toss shrimp with chili powder, cumin, salt, and juice of one lime.',
      'Mix shredded cabbage with mayonnaise and remaining lime juice for the slaw.',
      'Sear the shrimp in oil over high heat, 2 minutes per side, until pink and opaque.',
      'Warm the tortillas and fill with shrimp and slaw. Top with cilantro.',
    ],
  },
  {
    slug: 'shrimp-fried-rice',
    title: 'Shrimp Fried Rice',
    summary: 'Classic fried rice with shrimp, egg, and vegetables.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'Chinese',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'shrimp', qty: 500, unit: 'g' },
      { slug: 'white_rice', qty: 2, unit: 'cup', prepNote: 'cooked and cooled' },
      { slug: 'egg', qty: 2, unit: 'each' },
      { slug: 'peas', qty: 0.5, unit: 'cup' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 2, unit: 'tbsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
    ],
    steps: [
      'Heat 1 tbsp oil in a wok; scramble the eggs and set aside.',
      'Add remaining oil, sauté garlic, carrot, and peas 2 minutes.',
      'Add shrimp and cook 2-3 minutes until pink.',
      'Add the cooked rice, breaking up clumps, and stir-fry 3-4 minutes.',
      'Stir in soy sauce, sesame oil, scrambled egg, and green onion. Toss to combine and serve.',
    ],
  },
  {
    slug: 'shrimp-and-grits',
    title: 'Shrimp and Grits',
    summary: 'Creamy grits topped with garlicky, spiced shrimp.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'American',
    difficulty: 2,
    mealSlots: ['dinner', 'breakfast'],
    ingredients: [
      { slug: 'shrimp', qty: 500, unit: 'g' },
      { slug: 'quinoa', qty: 1, unit: 'cup', prepNote: 'uncooked, as a grits substitute' },
      { slug: 'milk', qty: 1, unit: 'cup' },
      { slug: 'cheddar_cheese', qty: 0.5, unit: 'cup', prepNote: 'shredded' },
      { slug: 'butter', qty: 2, unit: 'tbsp' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'smoked_paprika', qty: 1, unit: 'tsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cook quinoa in milk and 1 cup water until creamy, about 15 minutes; stir in cheddar and half the butter.',
      'Season shrimp with smoked paprika and salt.',
      'Heat oil and remaining butter; sauté garlic 30 seconds, add shrimp, and cook 2-3 minutes per side until pink.',
      'Spoon shrimp over the creamy quinoa and top with green onion.',
    ],
  },
  {
    slug: 'coconut-shrimp-curry',
    title: 'Coconut Shrimp Curry',
    summary: 'Quick shrimp curry in a fragrant coconut-curry sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'Thai',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'shrimp', qty: 600, unit: 'g' },
      { slug: 'curry_paste', qty: 2, unit: 'tbsp' },
      { slug: 'coconut_milk', qty: 1, unit: 'can' },
      { slug: 'fish_sauce', qty: 1, unit: 'tbsp' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'basil_fresh', qty: 0.25, unit: 'cup', optional: true },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Heat oil; fry the curry paste 1 minute until fragrant.',
      'Add coconut milk and fish sauce; simmer 5 minutes.',
      'Add bell pepper and shrimp; simmer 5-6 minutes until the shrimp are pink and opaque.',
      'Finish with lime juice and basil, and serve over rice.',
    ],
  },
  {
    slug: 'shrimp-and-veggie-skewers',
    title: 'Greek Shrimp and Vegetable Skewers',
    summary: 'Grilled lemon-herb shrimp and vegetable skewers.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 8,
    cuisine: 'Mediterranean',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'shrimp', qty: 600, unit: 'g' },
      { slug: 'zucchini', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'cherry_tomatoes', qty: 1, unit: 'cup' },
      { slug: 'red_onion', qty: 1, unit: 'each', prepNote: 'cubed' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'oregano_dried', qty: 1, unit: 'tsp' },
      { slug: 'feta_cheese', qty: 0.33, unit: 'cup', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Whisk olive oil, lemon juice, garlic, oregano, and salt. Toss with shrimp and vegetables.',
      'Thread onto skewers, alternating shrimp and vegetables.',
      'Grill or broil 3-4 minutes per side until the shrimp are pink and opaque.',
      'Sprinkle with feta if using and serve.',
    ],
  },
]
