// Tofu & tempeh family — the vegan/vegetarian protein anchor.

export const recipes = [
  {
    slug: 'crispy-sesame-tofu',
    title: 'Crispy Sesame Tofu',
    summary: 'Pan-crisped tofu tossed in a sweet-savory sesame glaze.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    cuisine: 'Chinese',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'tofu_firm', qty: 450, unit: 'g', prepNote: 'pressed and cubed' },
      { slug: 'cornstarch', qty: 3, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'honey', qty: 2, unit: 'tbsp' },
      { slug: 'rice_vinegar', qty: 1, unit: 'tbsp' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 3, unit: 'tbsp' },
      { slug: 'sesame_seeds', qty: 1, unit: 'tsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'broccoli', qty: 250, unit: 'g' },
    ],
    steps: [
      'Toss the pressed tofu cubes in cornstarch until evenly coated.',
      'Heat vegetable oil in a large skillet; fry the tofu until crisp and golden on all sides, about 8 minutes. Remove.',
      'Whisk soy sauce, honey, rice vinegar, garlic, and ginger; pour into the pan and simmer 1-2 minutes until thickened.',
      'Return the tofu to the pan and toss to coat. Finish with sesame oil and sesame seeds.',
      'Cook rice and steam broccoli; serve alongside.',
    ],
  },
  {
    slug: 'tofu-tikka-masala',
    title: 'Tofu Tikka Masala',
    summary: 'The classic creamy tomato curry, made with crispy tofu.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 25,
    cuisine: 'Indian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'tofu_firm', qty: 450, unit: 'g', prepNote: 'pressed and cubed' },
      { slug: 'onion', qty: 1, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'garam_masala', qty: 2, unit: 'tsp' },
      { slug: 'turmeric', qty: 1, unit: 'tsp' },
      { slug: 'tomato_paste', qty: 3, unit: 'tbsp' },
      { slug: 'coconut_milk', qty: 1, unit: 'cup' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Sear the pressed tofu cubes in oil until golden on most sides, about 6 minutes; set aside.',
      'In the same pan, soften the onion, then add garlic, ginger, garam masala, and turmeric; cook 1 minute.',
      'Stir in tomato paste and coconut milk; simmer 10 minutes.',
      'Return the tofu to the sauce and simmer 5 more minutes.',
      'Cook rice, garnish the curry with cilantro, and serve over rice.',
    ],
  },
  {
    slug: 'tempeh-stir-fry',
    title: 'Tempeh and Vegetable Stir-Fry',
    summary: 'Nutty tempeh stir-fried with crisp vegetables in a soy glaze.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Indonesian',
    difficulty: 1,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'tempeh', qty: 400, unit: 'g', prepNote: 'cubed' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'peanut_butter', qty: 1, unit: 'tbsp' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'vegetable_oil', qty: 2, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Heat oil in a wok; fry the tempeh until golden on most sides, about 6 minutes.',
      'Add bell pepper, carrot, and garlic; stir-fry 3-4 minutes.',
      'Whisk soy sauce, peanut butter, and honey; add to the pan and toss until everything is coated.',
      'Serve over rice.',
    ],
  },
  {
    slug: 'tofu-scramble-breakfast-tacos',
    title: 'Tofu Scramble Breakfast Tacos',
    summary: 'Turmeric-spiced tofu scramble in warm tortillas.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Mexican',
    difficulty: 1,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'tofu_firm', qty: 400, unit: 'g', prepNote: 'crumbled' },
      { slug: 'turmeric', qty: 0.5, unit: 'tsp' },
      { slug: 'cumin', qty: 0.5, unit: 'tsp' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'bell_pepper_green', qty: 0.5, unit: 'each' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'tortilla_flour', qty: 8, unit: 'each' },
      { slug: 'avocado', qty: 1, unit: 'each' },
      { slug: 'salsa', qty: 0.25, unit: 'cup', optional: true },
      { slug: 'salt', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Heat oil and sauté onion and bell pepper until softened, about 4 minutes.',
      'Add crumbled tofu, turmeric, cumin, and salt; cook 6-8 minutes, stirring occasionally, until lightly golden.',
      'Warm the tortillas and fill with the scramble, avocado, and salsa.',
    ],
  },
  {
    slug: 'tempeh-buddha-bowl',
    title: 'Tempeh Buddha Bowl',
    summary: 'Roasted tempeh and sweet potato over greens with tahini dressing.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 25,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['lunch', 'dinner'],
    ingredients: [
      { slug: 'tempeh', qty: 400, unit: 'g', prepNote: 'cubed' },
      { slug: 'sweet_potato', qty: 2, unit: 'each', prepNote: 'cubed' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'smoked_paprika', qty: 1, unit: 'tsp' },
      { slug: 'kale', qty: 3, unit: 'cup', prepNote: 'chopped' },
      { slug: 'tahini', qty: 2, unit: 'tbsp' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'quinoa', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 400°F (200°C). Toss tempeh and sweet potato with olive oil, smoked paprika, and half the salt.',
      'Roast 20-25 minutes, turning once, until golden.',
      'Cook quinoa according to package directions.',
      'Whisk tahini, lemon juice, remaining salt, and a splash of water for the dressing.',
      'Massage the kale briefly, then build bowls with quinoa, kale, roasted tempeh and sweet potato, and dressing.',
    ],
  },
  {
    slug: 'mapo-tofu',
    title: 'Mapo Tofu',
    summary: 'Silky tofu in a spicy, savory Sichuan-style sauce.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 15,
    cuisine: 'Chinese',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'tofu_firm', qty: 500, unit: 'g', prepNote: 'cubed' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'ginger', qty: 1, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'red_pepper_flakes', qty: 0.5, unit: 'tsp' },
      { slug: 'cornstarch', qty: 1, unit: 'tbsp' },
      { slug: 'vegetable_broth', qty: 0.5, unit: 'cup' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Heat oil; fry garlic, ginger, and red pepper flakes 30 seconds.',
      'Add broth and soy sauce; bring to a simmer.',
      'Gently add the tofu, simmer 5 minutes, then stir in cornstarch slurry (mixed with a little water) to thicken.',
      'Finish with sesame oil and green onion; serve over rice.',
    ],
  },
  {
    slug: 'thai-tofu-satay',
    title: 'Tofu Satay Skewers',
    summary: 'Grilled marinated tofu skewers with a peanut dipping sauce.',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 10,
    cuisine: 'Thai',
    difficulty: 2,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'tofu_firm', qty: 450, unit: 'g', prepNote: 'pressed and cubed' },
      { slug: 'curry_powder', qty: 1, unit: 'tsp' },
      { slug: 'soy_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
      { slug: 'peanut_butter', qty: 3, unit: 'tbsp' },
      { slug: 'coconut_milk', qty: 0.33, unit: 'cup' },
      { slug: 'lime', qty: 1, unit: 'each' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
    ],
    steps: [
      'Toss the tofu with curry powder, soy sauce, and oil; thread onto skewers.',
      'Whisk peanut butter, coconut milk, lime juice, and honey for the dipping sauce.',
      'Grill or broil the skewers 8-10 minutes, turning occasionally, until lightly charred.',
      'Cook rice and serve the skewers with the peanut sauce.',
    ],
  },
  {
    slug: 'korean-tofu-stew',
    title: 'Korean-Style Soft Tofu Stew',
    summary: 'A spicy, comforting stew built around silky tofu.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'Korean',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'tofu_firm', qty: 450, unit: 'g', prepNote: 'cubed' },
      { slug: 'onion', qty: 0.5, unit: 'each' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'red_pepper_flakes', qty: 1, unit: 'tbsp' },
      { slug: 'soy_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'sesame_oil', qty: 1, unit: 'tsp' },
      { slug: 'vegetable_broth', qty: 2, unit: 'cup' },
      { slug: 'egg', qty: 1, unit: 'each', optional: true },
      { slug: 'green_onion', qty: 2, unit: 'each' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'vegetable_oil', qty: 1, unit: 'tbsp' },
    ],
    steps: [
      'Heat oil; soften onion and garlic, about 4 minutes.',
      'Stir in red pepper flakes, then add broth and soy sauce; simmer 5 minutes.',
      'Gently add the tofu and simmer 8-10 minutes.',
      'Crack in the egg if using and simmer 1-2 minutes until just set. Finish with sesame oil and green onion; serve over rice.',
    ],
  },
  {
    slug: 'vietnamese-tofu-and-lemongrass',
    title: 'Vietnamese-Style Lemon Tofu',
    summary: 'Crispy tofu tossed in a bright lemon-garlic sauce.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    cuisine: 'Vietnamese',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'tofu_firm', qty: 450, unit: 'g', prepNote: 'pressed and cubed' },
      { slug: 'cornstarch', qty: 3, unit: 'tbsp' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'fish_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'honey', qty: 2, unit: 'tbsp' },
      { slug: 'vegetable_oil', qty: 3, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp', optional: true },
    ],
    steps: [
      'Toss the tofu in cornstarch. Fry in oil until golden and crisp on all sides, about 8 minutes.',
      'Whisk garlic, lemon juice, fish sauce, and honey.',
      'Pour the sauce over the crispy tofu and toss to coat.',
      'Cook rice, garnish with cilantro, and serve.',
    ],
  },
  {
    slug: 'middle-eastern-tofu-shawarma',
    title: 'Tofu Shawarma Wrap',
    summary: 'Spiced roasted tofu wrapped with vegetables and tahini sauce.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 20,
    cuisine: 'Middle Eastern',
    difficulty: 1,
    mealSlots: ['lunch', 'dinner'],
    ingredients: [
      { slug: 'tofu_firm', qty: 450, unit: 'g', prepNote: 'sliced' },
      { slug: 'cumin', qty: 1, unit: 'tsp' },
      { slug: 'coriander_ground', qty: 1, unit: 'tsp' },
      { slug: 'turmeric', qty: 0.5, unit: 'tsp' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'tahini', qty: 2, unit: 'tbsp' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'pita_bread', qty: 4, unit: 'each' },
      { slug: 'lettuce_romaine', qty: 1, unit: 'cup', prepNote: 'shredded' },
      { slug: 'tomato', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 400°F (220°C). Toss tofu with cumin, coriander, turmeric, oil, and salt.',
      'Roast 20 minutes, turning once, until crisped at the edges.',
      'Whisk tahini and lemon juice with a splash of water for the sauce.',
      'Warm the pita and fill with tofu, lettuce, tomato, and tahini sauce.',
    ],
  },
  {
    slug: 'american-tofu-bowl',
    title: 'BBQ Tofu Bowl',
    summary: 'Sticky BBQ-glazed tofu over rice with corn and greens.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'tofu_firm', qty: 450, unit: 'g', prepNote: 'cubed' },
      { slug: 'cornstarch', qty: 2, unit: 'tbsp' },
      { slug: 'bbq_sauce', qty: 0.33, unit: 'cup' },
      { slug: 'vegetable_oil', qty: 2, unit: 'tbsp' },
      { slug: 'corn', qty: 1, unit: 'cup' },
      { slug: 'kale', qty: 2, unit: 'cup', prepNote: 'chopped' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'salt', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Toss the tofu in cornstarch and fry in oil until golden and crisp, about 8 minutes.',
      'Toss the crisped tofu in BBQ sauce.',
      'Cook rice; sauté the kale briefly until wilted.',
      'Build bowls with rice, kale, corn, and the BBQ tofu.',
    ],
  },
  {
    slug: 'tofu-pad-see-ew',
    title: 'Tofu Pad See Ew',
    summary: 'Wide noodles stir-fried with crispy tofu and broccoli.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    cuisine: 'Thai',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'tofu_firm', qty: 400, unit: 'g', prepNote: 'cubed' },
      { slug: 'rice_noodles', qty: 300, unit: 'g' },
      { slug: 'broccoli', qty: 250, unit: 'g' },
      { slug: 'garlic', qty: 3, unit: 'clove' },
      { slug: 'egg', qty: 2, unit: 'each' },
      { slug: 'soy_sauce', qty: 3, unit: 'tbsp' },
      { slug: 'oyster_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'vegetable_oil', qty: 3, unit: 'tbsp' },
    ],
    steps: [
      'Cook rice noodles according to package directions.',
      'Fry the tofu in oil until golden on most sides, about 6 minutes; remove.',
      'Scramble the eggs softly in the same pan, push aside, then add garlic and broccoli; stir-fry 3 minutes.',
      'Add the noodles, tofu, soy sauce, and oyster sauce; toss over high heat 2-3 minutes.',
    ],
  },
  {
    slug: 'tofu-banh-mi',
    title: 'Tofu Bánh Mì',
    summary: 'Crispy marinated tofu on a baguette with pickled vegetables.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 12,
    cuisine: 'Vietnamese',
    difficulty: 2,
    mealSlots: ['lunch'],
    ingredients: [
      { slug: 'tofu_firm', qty: 400, unit: 'g', prepNote: 'sliced' },
      { slug: 'soy_sauce', qty: 2, unit: 'tbsp' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'carrot', qty: 1, unit: 'each', prepNote: 'julienned' },
      { slug: 'cucumber', qty: 0.5, unit: 'each', prepNote: 'julienned' },
      { slug: 'rice_vinegar', qty: 2, unit: 'tbsp' },
      { slug: 'mayonnaise', qty: 2, unit: 'tbsp' },
      { slug: 'bread_sandwich', qty: 4, unit: 'slice', prepNote: 'or a baguette if available' },
      { slug: 'cilantro', qty: 0.25, unit: 'cup' },
      { slug: 'vegetable_oil', qty: 2, unit: 'tbsp' },
    ],
    steps: [
      'Toss carrot and cucumber with rice vinegar; set aside to quick-pickle.',
      'Toss tofu with soy sauce and honey; pan-fry in oil until golden and crisped, about 8 minutes.',
      'Spread mayonnaise on the bread, layer with tofu, pickled vegetables, and cilantro.',
    ],
  },
]
