// Greek yogurt & cottage cheese family — breakfast and snack anchor.

export const recipes = [
  {
    slug: 'greek-yogurt-parfait',
    title: 'Greek Yogurt Parfait',
    summary: 'Layered yogurt, honey, and berries with crunchy walnuts.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 0,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['breakfast', 'snack'],
    ingredients: [
      { slug: 'greek_yogurt', qty: 1, unit: 'cup' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'walnuts', qty: 2, unit: 'tbsp' },
      { slug: 'cinnamon', qty: 0.25, unit: 'tsp', optional: true },
    ],
    steps: [
      'Spoon half the yogurt into a glass or bowl.',
      'Drizzle with half the honey and scatter half the walnuts.',
      'Repeat with the remaining yogurt, honey, and walnuts. Dust with cinnamon if using.',
    ],
  },
  {
    slug: 'tzatziki-chicken-wrap',
    title: 'Cucumber Yogurt Wrap',
    summary: 'A cool yogurt-cucumber sauce wrapped with fresh vegetables.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 0,
    cuisine: 'Mediterranean',
    difficulty: 1,
    mealSlots: ['lunch'],
    ingredients: [
      { slug: 'greek_yogurt', qty: 0.75, unit: 'cup' },
      { slug: 'cucumber', qty: 0.5, unit: 'each', prepNote: 'diced' },
      { slug: 'garlic', qty: 1, unit: 'clove' },
      { slug: 'lemon', qty: 0.5, unit: 'each' },
      { slug: 'tortilla_flour', qty: 2, unit: 'each' },
      { slug: 'lettuce_romaine', qty: 1, unit: 'cup', prepNote: 'shredded' },
      { slug: 'tomato', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'feta_cheese', qty: 0.25, unit: 'cup', optional: true },
      { slug: 'salt', qty: 0.25, unit: 'tsp' },
    ],
    steps: [
      'Mix yogurt, cucumber, minced garlic, lemon juice, and salt for the tzatziki.',
      'Spread onto tortillas and top with lettuce, tomato, and feta.',
      'Roll up tightly and slice in half to serve.',
    ],
  },
  {
    slug: 'overnight-yogurt-oats',
    title: 'Yogurt Overnight Oats',
    summary: 'No-cook oats soaked overnight in yogurt and milk.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 0,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'rolled_oats', qty: 0.5, unit: 'cup' },
      { slug: 'greek_yogurt', qty: 0.5, unit: 'cup' },
      { slug: 'milk', qty: 0.33, unit: 'cup' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'chia_seeds', qty: 1, unit: 'tbsp', optional: true },
    ],
    steps: [
      'Combine oats, yogurt, milk, honey, and chia seeds in a jar.',
      'Stir well, cover, and refrigerate overnight.',
      'Stir again before eating; add fruit or nuts if desired.',
    ],
  },
  {
    slug: 'cottage-cheese-bowl',
    title: 'Savory Cottage Cheese Bowl',
    summary: 'High-protein cottage cheese with fresh vegetables and olive oil.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 0,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['lunch', 'snack'],
    ingredients: [
      { slug: 'cottage_cheese', qty: 1, unit: 'cup' },
      { slug: 'cherry_tomatoes', qty: 0.5, unit: 'cup' },
      { slug: 'cucumber', qty: 0.25, unit: 'each', prepNote: 'diced' },
      { slug: 'olive_oil', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.25, unit: 'tsp' },
      { slug: 'everything_bagel_seasoning', qty: 0.5, unit: 'tsp', optional: true },
    ],
    steps: [
      'Spoon the cottage cheese into a bowl.',
      'Top with cherry tomatoes and cucumber.',
      'Drizzle with olive oil, and finish with black pepper and everything bagel seasoning.',
    ],
  },
  {
    slug: 'yogurt-marinated-chicken-skewers',
    title: 'Yogurt-Marinated Grilled Vegetable Skewers',
    summary: 'Yogurt-marinated vegetables, grilled until charred and tender.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 10,
    cuisine: 'Indian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'greek_yogurt', qty: 0.5, unit: 'cup' },
      { slug: 'garam_masala', qty: 1, unit: 'tsp' },
      { slug: 'turmeric', qty: 0.5, unit: 'tsp' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'zucchini', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each', prepNote: 'cubed' },
      { slug: 'mushroom', qty: 150, unit: 'g' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Whisk yogurt, garam masala, turmeric, garlic, lemon juice, and salt. Toss with the vegetables and marinate 15 minutes.',
      'Thread onto skewers.',
      'Grill or broil, turning occasionally, 8-10 minutes until charred and tender.',
      'Cook rice and serve alongside.',
    ],
  },
  {
    slug: 'cottage-cheese-pancakes',
    title: 'Cottage Cheese Pancakes',
    summary: 'High-protein pancakes made with blended cottage cheese.',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 12,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'cottage_cheese', qty: 1, unit: 'cup' },
      { slug: 'egg', qty: 2, unit: 'each' },
      { slug: 'all_purpose_flour', qty: 0.5, unit: 'cup' },
      { slug: 'baking_powder', qty: 1, unit: 'tsp' },
      { slug: 'vanilla_extract', qty: 0.5, unit: 'tsp' },
      { slug: 'butter', qty: 1, unit: 'tbsp' },
      { slug: 'maple_syrup', qty: 2, unit: 'tbsp', optional: true },
    ],
    steps: [
      'Blend cottage cheese, eggs, flour, baking powder, and vanilla until mostly smooth.',
      'Melt butter in a nonstick pan over medium heat. Pour small rounds of batter and cook 2-3 minutes per side until golden.',
      'Serve with maple syrup.',
    ],
  },
]
