// Greek yogurt & cottage cheese family — breakfast and snack anchor.

export const recipes = [
  {
    slug: 'greek-yogurt-parfait',
    title: 'Greek Yogurt Parfait',
    summary: 'Layered yogurt, honey, and berries with crunchy walnuts.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 0,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['breakfast', 'snack'],
    ingredients: [
      { slug: 'greek_yogurt', qty: 1, unit: 'cup' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'walnuts', qty: 2, unit: 'tbsp' },
      { slug: 'cinnamon', qty: 0.25, unit: 'tsp', optional: true },
    ],
    steps: [
      'Spoon half the yogurt into a glass or bowl.',
      'Drizzle with half the honey and scatter half the walnuts.',
      'Repeat with the remaining yogurt, honey, and walnuts. Dust with cinnamon if using.',
    ],
  },
  {
    slug: 'tzatziki-chicken-wrap',
    title: 'Cucumber Yogurt Wrap',
    summary: 'A cool yogurt-cucumber sauce wrapped with fresh vegetables.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 0,
    cuisine: 'Mediterranean',
    difficulty: 1,
    mealSlots: ['lunch'],
    ingredients: [
      { slug: 'greek_yogurt', qty: 0.75, unit: 'cup' },
      { slug: 'cucumber', qty: 0.5, unit: 'each', prepNote: 'diced' },
      { slug: 'garlic', qty: 1, unit: 'clove' },
      { slug: 'lemon', qty: 0.5, unit: 'each' },
      { slug: 'tortilla_flour', qty: 2, unit: 'each' },
      { slug: 'lettuce_romaine', qty: 1, unit: 'cup', prepNote: 'shredded' },
      { slug: 'tomato', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'feta_cheese', qty: 0.25, unit: 'cup', optional: true },
      { slug: 'salt', qty: 0.25, unit: 'tsp' },
    ],
    steps: [
      'Mix yogurt, cucumber, minced garlic, lemon juice, and salt for the tzatziki.',
      'Spread onto tortillas and top with lettuce, tomato, and feta.',
      'Roll up tightly and slice in half to serve.',
    ],
  },
  {
    slug: 'overnight-yogurt-oats',
    title: 'Yogurt Overnight Oats',
    summary: 'No-cook oats soaked overnight in yogurt and milk.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 0,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'rolled_oats', qty: 0.5, unit: 'cup' },
      { slug: 'greek_yogurt', qty: 0.5, unit: 'cup' },
      { slug: 'milk', qty: 0.33, unit: 'cup' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'chia_seeds', qty: 1, unit: 'tbsp', optional: true },
    ],
    steps: [
      'Combine oats, yogurt, milk, honey, and chia seeds in a jar.',
      'Stir well, cover, and refrigerate overnight.',
      'Stir again before eating; add fruit or nuts if desired.',
    ],
  },
  {
    slug: 'cottage-cheese-bowl',
    title: 'Savory Cottage Cheese Bowl',
    summary: 'High-protein cottage cheese with fresh vegetables and olive oil.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 0,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['lunch', 'snack'],
    ingredients: [
      { slug: 'cottage_cheese', qty: 1, unit: 'cup' },
      { slug: 'cherry_tomatoes', qty: 0.5, unit: 'cup' },
      { slug: 'cucumber', qty: 0.25, unit: 'each', prepNote: 'diced' },
      { slug: 'olive_oil', qty: 1, unit: 'tsp' },
      { slug: 'black_pepper', qty: 0.25, unit: 'tsp' },
      { slug: 'everything_bagel_seasoning', qty: 0.5, unit: 'tsp', optional: true },
    ],
    steps: [
      'Spoon the cottage cheese into a bowl.',
      'Top with cherry tomatoes and cucumber.',
      'Drizzle with olive oil, and finish with black pepper and everything bagel seasoning.',
    ],
  },
  {
    slug: 'yogurt-marinated-chicken-skewers',
    title: 'Yogurt-Marinated Grilled Vegetable Skewers',
    summary: 'Yogurt-marinated vegetables, grilled until charred and tender.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 10,
    cuisine: 'Indian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'greek_yogurt', qty: 0.5, unit: 'cup' },
      { slug: 'garam_masala', qty: 1, unit: 'tsp' },
      { slug: 'turmeric', qty: 0.5, unit: 'tsp' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'zucchini', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'bell_pepper_red', qty: 1, unit: 'each', prepNote: 'cubed' },
      { slug: 'mushroom', qty: 150, unit: 'g' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Whisk yogurt, garam masala, turmeric, garlic, lemon juice, and salt. Toss with the vegetables and marinate 15 minutes.',
      'Thread onto skewers.',
      'Grill or broil, turning occasionally, 8-10 minutes until charred and tender.',
      'Cook rice and serve alongside.',
    ],
  },
  {
    slug: 'cottage-cheese-pancakes',
    title: 'Cottage Cheese Pancakes',
    summary: 'High-protein pancakes made with blended cottage cheese.',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 12,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'cottage_cheese', qty: 1, unit: 'cup' },
      { slug: 'egg', qty: 2, unit: 'each' },
      { slug: 'all_purpose_flour', qty: 0.5, unit: 'cup' },
      { slug: 'baking_powder', qty: 1, unit: 'tsp' },
      { slug: 'vanilla_extract', qty: 0.5, unit: 'tsp' },
      { slug: 'butter', qty: 1, unit: 'tbsp' },
      { slug: 'maple_syrup', qty: 2, unit: 'tbsp', optional: true },
    ],
    steps: [
      'Blend cottage cheese, eggs, flour, baking powder, and vanilla until mostly smooth.',
      'Melt butter in a nonstick pan over medium heat. Pour small rounds of batter and cook 2-3 minutes per side until golden.',
      'Serve with maple syrup.',
    ],
  },
  {
    slug: 'indian-cucumber-raita',
    title: 'Cucumber Raita Bowl',
    summary: 'A cooling yogurt and cucumber side, hearty enough as a light meal with rice.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 0,
    cuisine: 'Indian',
    difficulty: 1,
    mealSlots: ['lunch', 'snack'],
    ingredients: [
      { slug: 'greek_yogurt', qty: 1, unit: 'cup' },
      { slug: 'cucumber', qty: 1, unit: 'each', prepNote: 'grated' },
      { slug: 'cumin', qty: 0.5, unit: 'tsp' },
      { slug: 'cilantro', qty: 2, unit: 'tbsp' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'salt', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Cook rice according to package directions.',
      'Mix yogurt with grated cucumber, cumin, cilantro, and salt.',
      'Serve over or alongside warm rice.',
    ],
  },
  {
    slug: 'turkish-yogurt-soup',
    title: 'Turkish Yogurt and Rice Soup',
    summary: 'A gently tangy, warming yogurt-based soup.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cuisine: 'Turkish',
    difficulty: 2,
    mealSlots: ['lunch', 'dinner'],
    ingredients: [
      { slug: 'greek_yogurt', qty: 1, unit: 'cup' },
      { slug: 'white_rice', qty: 0.33, unit: 'cup' },
      { slug: 'vegetable_broth', qty: 4, unit: 'cup' },
      { slug: 'egg', qty: 1, unit: 'each' },
      { slug: 'all_purpose_flour', qty: 1, unit: 'tbsp' },
      { slug: 'butter', qty: 2, unit: 'tbsp' },
      { slug: 'red_pepper_flakes', qty: 0.25, unit: 'tsp', optional: true },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Simmer rice in broth until tender, about 15 minutes.',
      'Whisk yogurt, egg, and flour together, then gradually whisk in a ladle of the hot broth to temper it.',
      'Stir the tempered mixture back into the pot and warm gently (do not boil) until slightly thickened.',
      'Season with salt. Melt butter with red pepper flakes and drizzle over each bowl.',
    ],
  },
  {
    slug: 'persian-yogurt-dip-with-spinach',
    title: 'Persian Spinach Yogurt Dip',
    summary: 'A garlicky yogurt and sautéed spinach dip, served with warm bread.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 10,
    cuisine: 'Middle Eastern',
    difficulty: 1,
    mealSlots: ['snack', 'lunch'],
    ingredients: [
      { slug: 'greek_yogurt', qty: 1, unit: 'cup' },
      { slug: 'spinach', qty: 200, unit: 'g' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'walnuts', qty: 0.25, unit: 'cup', optional: true },
      { slug: 'pita_bread', qty: 4, unit: 'each' },
      { slug: 'salt', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Heat oil; sauté garlic and spinach until wilted, about 4 minutes. Cool slightly and chop finely.',
      'Mix the spinach into the yogurt with salt.',
      'Top with chopped walnuts and serve with warm pita.',
    ],
  },
  {
    slug: 'yogurt-berry-smoothie-bowl',
    title: 'Yogurt Smoothie Bowl',
    summary: 'A thick, spoonable yogurt smoothie bowl with toppings.',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 0,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['breakfast'],
    ingredients: [
      { slug: 'greek_yogurt', qty: 1, unit: 'cup' },
      { slug: 'banana', qty: 1, unit: 'each' },
      { slug: 'honey', qty: 1, unit: 'tbsp' },
      { slug: 'walnuts', qty: 2, unit: 'tbsp' },
      { slug: 'chia_seeds', qty: 1, unit: 'tsp', optional: true },
    ],
    steps: [
      'Blend yogurt with half the banana and honey until thick and smooth.',
      'Pour into a bowl and top with the remaining banana sliced, walnuts, and chia seeds.',
    ],
  },
  {
    slug: 'chicken-yogurt-marinade-bowl',
    title: 'Yogurt-Marinated Chicken Bowl',
    summary: 'Tender yogurt-marinated chicken over rice with cucumber salad.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    cuisine: 'Indian',
    difficulty: 2,
    mealSlots: ['dinner'],
    ingredients: [
      { slug: 'chicken_thigh', qty: 600, unit: 'g' },
      { slug: 'greek_yogurt', qty: 0.75, unit: 'cup' },
      { slug: 'garam_masala', qty: 1.5, unit: 'tsp' },
      { slug: 'turmeric', qty: 0.5, unit: 'tsp' },
      { slug: 'garlic', qty: 2, unit: 'clove' },
      { slug: 'lemon', qty: 1, unit: 'each' },
      { slug: 'cucumber', qty: 1, unit: 'each', prepNote: 'diced' },
      { slug: 'white_rice', qty: 1, unit: 'cup', prepNote: 'uncooked' },
      { slug: 'olive_oil', qty: 1, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Mix half the yogurt with garam masala, turmeric, garlic, and half the lemon juice. Marinate the chicken at least 15 minutes.',
      'Sear the chicken in oil, 6-7 minutes per side, until cooked through.',
      'Mix remaining yogurt with cucumber, remaining lemon juice, and salt for a quick side salad.',
      'Cook rice and serve with the sliced chicken and cucumber salad.',
    ],
  },
  {
    slug: 'yogurt-ranch-veggie-dip',
    title: 'Yogurt Ranch Veggie Dip',
    summary: 'A lighter, protein-rich take on ranch dip with fresh vegetables.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 0,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['snack'],
    ingredients: [
      { slug: 'greek_yogurt', qty: 1, unit: 'cup' },
      { slug: 'ranch_dressing', qty: 2, unit: 'tbsp' },
      { slug: 'garlic_powder', qty: 0.5, unit: 'tsp' },
      { slug: 'carrot', qty: 3, unit: 'each', prepNote: 'cut into sticks' },
      { slug: 'celery', qty: 3, unit: 'each', prepNote: 'cut into sticks' },
      { slug: 'cucumber', qty: 1, unit: 'each', prepNote: 'sliced' },
      { slug: 'salt', qty: 0.25, unit: 'tsp' },
    ],
    steps: [
      'Mix yogurt, ranch dressing, garlic powder, and salt.',
      'Serve with carrot, celery, and cucumber for dipping.',
    ],
  },
  {
    slug: 'baked-yogurt-chicken-tenders',
    title: 'Baked Yogurt Chicken Tenders',
    summary: 'Crispy baked chicken tenders with a yogurt-based marinade.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 20,
    cuisine: 'American',
    difficulty: 1,
    mealSlots: ['dinner', 'lunch'],
    ingredients: [
      { slug: 'chicken_breast', qty: 600, unit: 'g', prepNote: 'cut into strips' },
      { slug: 'greek_yogurt', qty: 0.5, unit: 'cup' },
      { slug: 'garlic_powder', qty: 1, unit: 'tsp' },
      { slug: 'paprika', qty: 1, unit: 'tsp' },
      { slug: 'panko_breadcrumbs', qty: 1, unit: 'cup' },
      { slug: 'parmesan_cheese', qty: 0.25, unit: 'cup', prepNote: 'grated' },
      { slug: 'olive_oil', qty: 2, unit: 'tbsp' },
      { slug: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Mix yogurt with garlic powder, paprika, and salt; coat the chicken strips and marinate at least 15 minutes.',
      'Preheat oven to 425°F (220°C). Mix breadcrumbs and parmesan.',
      'Dredge the marinated chicken in the breadcrumb mixture and place on a lined tray; drizzle with oil.',
      'Bake 18-20 minutes, flipping halfway, until golden and cooked through.',
    ],
  },
]
