-- Groundwork seed — recipes: beans
-- GENERATED by scripts/generate-recipes.mjs from scripts/recipe-data/beans.mjs — do not hand-edit.
-- Edit the source recipe definitions and re-run: npm run gen:recipes
--
-- kcal_per_serving/protein/carb/fat are COMPUTED from the ingredient list
-- below at generation time, not hand-typed — see this script's header.

-- Black Bean and Corn Quesadillas (Mexican)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('black-bean-and-corn-quesadillas', 'Black Bean and Corn Quesadillas', 'Crispy tortillas filled with black beans, corn, and melty cheese.', 4, 10, 15, 'Mexican', 1, 650.8, 28.7, 79.5, 24.9);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), (select id from ingredients where slug = 'black_beans_canned'), 1, (select id from units where slug = 'can'), null, false, 0),
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), (select id from ingredients where slug = 'corn'), 1, (select id from units where slug = 'cup'), null, false, 1),
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), (select id from ingredients where slug = 'cheddar_cheese'), 1.5, (select id from units where slug = 'cup'), 'shredded', false, 2),
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), (select id from ingredients where slug = 'tortilla_flour'), 8, (select id from units where slug = 'each'), null, false, 3),
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), (select id from ingredients where slug = 'cumin'), 1, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), (select id from ingredients where slug = 'chili_powder'), 0.5, (select id from units where slug = 'tsp'), null, false, 5),
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), (select id from ingredients where slug = 'olive_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 6),
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), (select id from ingredients where slug = 'salsa'), 0.5, (select id from units where slug = 'cup'), null, true, 7),
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), (select id from ingredients where slug = 'sour_cream'), 0.25, (select id from units where slug = 'cup'), null, true, 8);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), 1, 'Mash the black beans lightly with cumin and chili powder.'),
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), 2, 'Spread beans, corn, and cheese over half of each tortilla; fold over.'),
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), 3, 'Cook in a lightly oiled skillet, 2-3 minutes per side, until golden and the cheese melts.'),
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), 4, 'Cut into wedges and serve with salsa and sour cream.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), 'lunch'),
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'black-bean-and-corn-quesadillas'), (select id from diet_tags where slug = 'vegetarian'));

-- Pinto Bean and Rice Bowl (Mexican)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('pinto-bean-and-rice-bowl', 'Pinto Bean and Rice Bowl', 'A simple, filling bowl of seasoned pinto beans and rice.', 4, 5, 20, 'Mexican', 1, 496.8, 22.0, 78.3, 12.5);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), (select id from ingredients where slug = 'pinto_beans_canned'), 2, (select id from units where slug = 'can'), null, false, 0),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), (select id from ingredients where slug = 'onion'), 0.5, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), (select id from ingredients where slug = 'garlic'), 2, (select id from units where slug = 'clove'), null, false, 2),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), (select id from ingredients where slug = 'cumin'), 1, (select id from units where slug = 'tsp'), null, false, 3),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), (select id from ingredients where slug = 'chili_powder'), 0.5, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), (select id from ingredients where slug = 'white_rice'), 1, (select id from units where slug = 'cup'), 'uncooked', false, 5),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), (select id from ingredients where slug = 'avocado'), 1, (select id from units where slug = 'each'), null, false, 6),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), (select id from ingredients where slug = 'lime'), 1, (select id from units where slug = 'each'), null, false, 7),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), (select id from ingredients where slug = 'cheddar_cheese'), 0.5, (select id from units where slug = 'cup'), 'shredded', true, 8),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), (select id from ingredients where slug = 'olive_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 9),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 10);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), 1, 'Cook rice according to package directions.'),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), 2, 'Heat oil; soften onion and garlic, about 4 minutes.'),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), 3, 'Add pinto beans, cumin, chili powder, and salt; simmer 10 minutes, mashing some of the beans for a creamier texture.'),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), 4, 'Serve over rice topped with avocado, a squeeze of lime, and cheese if using.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), 'lunch'),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), (select id from diet_tags where slug = 'vegan')),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'pinto-bean-and-rice-bowl'), (select id from diet_tags where slug = 'dairy_free'));

-- Black Bean Burgers (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('black-bean-burgers', 'Black Bean Burgers', 'Hearty homemade black bean patties.', 4, 15, 15, 'American', 2, 471.8, 24.6, 72.7, 10.4);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'black-bean-burgers'), (select id from ingredients where slug = 'black_beans_canned'), 2, (select id from units where slug = 'can'), null, false, 0),
  ((select id from recipes where slug = 'black-bean-burgers'), (select id from ingredients where slug = 'panko_breadcrumbs'), 0.5, (select id from units where slug = 'cup'), null, false, 1),
  ((select id from recipes where slug = 'black-bean-burgers'), (select id from ingredients where slug = 'egg'), 1, (select id from units where slug = 'each'), null, false, 2),
  ((select id from recipes where slug = 'black-bean-burgers'), (select id from ingredients where slug = 'garlic_powder'), 1, (select id from units where slug = 'tsp'), null, false, 3),
  ((select id from recipes where slug = 'black-bean-burgers'), (select id from ingredients where slug = 'cumin'), 1, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'black-bean-burgers'), (select id from ingredients where slug = 'onion'), 0.25, (select id from units where slug = 'each'), 'finely diced', false, 5),
  ((select id from recipes where slug = 'black-bean-burgers'), (select id from ingredients where slug = 'olive_oil'), 2, (select id from units where slug = 'tbsp'), null, false, 6),
  ((select id from recipes where slug = 'black-bean-burgers'), (select id from ingredients where slug = 'bread_sandwich'), 4, (select id from units where slug = 'slice'), null, false, 7),
  ((select id from recipes where slug = 'black-bean-burgers'), (select id from ingredients where slug = 'lettuce_romaine'), 4, (select id from units where slug = 'each'), null, false, 8),
  ((select id from recipes where slug = 'black-bean-burgers'), (select id from ingredients where slug = 'tomato'), 1, (select id from units where slug = 'each'), 'sliced', false, 9),
  ((select id from recipes where slug = 'black-bean-burgers'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 10);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'black-bean-burgers'), 1, 'Mash the black beans, leaving some texture. Mix in breadcrumbs, egg, garlic powder, cumin, onion, and salt.'),
  ((select id from recipes where slug = 'black-bean-burgers'), 2, 'Shape into 4 patties and chill 10 minutes if time allows.'),
  ((select id from recipes where slug = 'black-bean-burgers'), 3, 'Pan-fry in oil, 4-5 minutes per side, until firm and browned.'),
  ((select id from recipes where slug = 'black-bean-burgers'), 4, 'Serve on bread with lettuce and tomato.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'black-bean-burgers'), 'dinner'),
  ((select id from recipes where slug = 'black-bean-burgers'), 'lunch');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'black-bean-burgers'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'black-bean-burgers'), (select id from diet_tags where slug = 'dairy_free'));

-- Vegetarian Pinto Bean Chili (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('pinto-bean-chili', 'Vegetarian Pinto Bean Chili', 'A hearty meatless chili loaded with pinto beans and vegetables.', 6, 10, 35, 'American', 1, 391.3, 22.2, 70.6, 4.5);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from ingredients where slug = 'pinto_beans_canned'), 2, (select id from units where slug = 'can'), null, false, 0),
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from ingredients where slug = 'black_beans_canned'), 1, (select id from units where slug = 'can'), null, false, 1),
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from ingredients where slug = 'onion'), 1, (select id from units where slug = 'each'), null, false, 2),
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from ingredients where slug = 'garlic'), 3, (select id from units where slug = 'clove'), null, false, 3),
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from ingredients where slug = 'bell_pepper_green'), 1, (select id from units where slug = 'each'), null, false, 4),
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from ingredients where slug = 'chili_powder'), 2, (select id from units where slug = 'tbsp'), null, false, 5),
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from ingredients where slug = 'cumin'), 1, (select id from units where slug = 'tsp'), null, false, 6),
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from ingredients where slug = 'smoked_paprika'), 1, (select id from units where slug = 'tsp'), null, false, 7),
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from ingredients where slug = 'tomato_canned_diced'), 2, (select id from units where slug = 'can'), null, false, 8),
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from ingredients where slug = 'corn'), 1, (select id from units where slug = 'cup'), null, false, 9),
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from ingredients where slug = 'olive_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 10),
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from ingredients where slug = 'salt'), 1.5, (select id from units where slug = 'tsp'), null, false, 11);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'pinto-bean-chili'), 1, 'Heat oil; soften onion, garlic, and bell pepper, about 5 minutes.'),
  ((select id from recipes where slug = 'pinto-bean-chili'), 2, 'Stir in chili powder, cumin, and smoked paprika; cook 1 minute.'),
  ((select id from recipes where slug = 'pinto-bean-chili'), 3, 'Add diced tomatoes and all the beans. Simmer uncovered 25 minutes.'),
  ((select id from recipes where slug = 'pinto-bean-chili'), 4, 'Stir in corn, season with salt, and simmer 5 more minutes.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'pinto-bean-chili'), 'dinner'),
  ((select id from recipes where slug = 'pinto-bean-chili'), 'lunch');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from diet_tags where slug = 'vegan')),
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'pinto-bean-chili'), (select id from diet_tags where slug = 'dairy_free'));

-- Cuban Black Beans and Rice (Cuban)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('cuban-black-beans-and-rice', 'Cuban Black Beans and Rice', 'Classic Cuban-style black beans simmered with peppers over rice.', 4, 10, 25, 'Cuban', 1, 472.0, 22.1, 80.3, 8.4);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), (select id from ingredients where slug = 'black_beans_canned'), 2, (select id from units where slug = 'can'), null, false, 0),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), (select id from ingredients where slug = 'onion'), 1, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), (select id from ingredients where slug = 'bell_pepper_green'), 1, (select id from units where slug = 'each'), null, false, 2),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), (select id from ingredients where slug = 'garlic'), 3, (select id from units where slug = 'clove'), null, false, 3),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), (select id from ingredients where slug = 'cumin'), 1, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), (select id from ingredients where slug = 'oregano_dried'), 1, (select id from units where slug = 'tsp'), null, false, 5),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), (select id from ingredients where slug = 'olive_oil'), 2, (select id from units where slug = 'tbsp'), null, false, 6),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), (select id from ingredients where slug = 'white_rice'), 1.5, (select id from units where slug = 'cup'), 'uncooked', false, 7),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), (select id from ingredients where slug = 'lime'), 1, (select id from units where slug = 'each'), null, false, 8),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 9);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), 1, 'Cook rice according to package directions.'),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), 2, 'Heat oil; soften onion, bell pepper, and garlic, about 6 minutes.'),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), 3, 'Add the black beans (with their liquid), cumin, and oregano. Simmer 15 minutes, mashing some beans for creaminess.'),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), 4, 'Season with salt and lime juice, and serve over rice.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), 'dinner'),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), 'lunch');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), (select id from diet_tags where slug = 'vegan')),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'cuban-black-beans-and-rice'), (select id from diet_tags where slug = 'dairy_free'));

-- Loaded Bean Nachos (Mexican)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('loaded-nachos', 'Loaded Bean Nachos', 'A sheet pan of tortilla chips loaded with beans, cheese, and toppings.', 4, 10, 12, 'Mexican', 1, 631.0, 34.3, 88.3, 17.5);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'loaded-nachos'), (select id from ingredients where slug = 'black_beans_canned'), 1, (select id from units where slug = 'can'), null, false, 0),
  ((select id from recipes where slug = 'loaded-nachos'), (select id from ingredients where slug = 'pinto_beans_canned'), 1, (select id from units where slug = 'can'), null, false, 1),
  ((select id from recipes where slug = 'loaded-nachos'), (select id from ingredients where slug = 'tortilla_corn'), 12, (select id from units where slug = 'each'), 'cut into chips and baked, or use store-bought chips', false, 2),
  ((select id from recipes where slug = 'loaded-nachos'), (select id from ingredients where slug = 'cheddar_cheese'), 1.5, (select id from units where slug = 'cup'), 'shredded', false, 3),
  ((select id from recipes where slug = 'loaded-nachos'), (select id from ingredients where slug = 'jalapeno'), 1, (select id from units where slug = 'each'), 'sliced', false, 4),
  ((select id from recipes where slug = 'loaded-nachos'), (select id from ingredients where slug = 'tomato'), 1, (select id from units where slug = 'each'), 'diced', false, 5),
  ((select id from recipes where slug = 'loaded-nachos'), (select id from ingredients where slug = 'green_onion'), 2, (select id from units where slug = 'each'), null, false, 6),
  ((select id from recipes where slug = 'loaded-nachos'), (select id from ingredients where slug = 'sour_cream'), 0.25, (select id from units where slug = 'cup'), null, true, 7),
  ((select id from recipes where slug = 'loaded-nachos'), (select id from ingredients where slug = 'avocado'), 1, (select id from units where slug = 'each'), null, true, 8),
  ((select id from recipes where slug = 'loaded-nachos'), (select id from ingredients where slug = 'cumin'), 1, (select id from units where slug = 'tsp'), null, false, 9);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'loaded-nachos'), 1, 'Preheat oven to 400°F (200°C). Warm the beans with cumin in a small pot.'),
  ((select id from recipes where slug = 'loaded-nachos'), 2, 'Spread tortilla chips on a sheet pan, top with beans, cheese, and jalapeño.'),
  ((select id from recipes where slug = 'loaded-nachos'), 3, 'Bake 8-10 minutes until the cheese melts.'),
  ((select id from recipes where slug = 'loaded-nachos'), 4, 'Top with tomato, green onion, sour cream, and avocado before serving.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'loaded-nachos'), 'dinner'),
  ((select id from recipes where slug = 'loaded-nachos'), 'lunch');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'loaded-nachos'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'loaded-nachos'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'loaded-nachos'), (select id from diet_tags where slug = 'high_protein'));

-- Rajma (Kidney Bean Curry) (Indian)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('indian-rajma', 'Rajma (Kidney Bean Curry)', 'North Indian spiced kidney beans, simmered until rich and thick.', 4, 10, 30, 'Indian', 1, 460.4, 21.6, 76.1, 8.5);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'indian-rajma'), (select id from ingredients where slug = 'pinto_beans_canned'), 2, (select id from units where slug = 'can'), 'or kidney beans if available', false, 0),
  ((select id from recipes where slug = 'indian-rajma'), (select id from ingredients where slug = 'onion'), 1, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'indian-rajma'), (select id from ingredients where slug = 'garlic'), 3, (select id from units where slug = 'clove'), null, false, 2),
  ((select id from recipes where slug = 'indian-rajma'), (select id from ingredients where slug = 'ginger'), 1, (select id from units where slug = 'tbsp'), null, false, 3),
  ((select id from recipes where slug = 'indian-rajma'), (select id from ingredients where slug = 'cumin'), 1, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'indian-rajma'), (select id from ingredients where slug = 'garam_masala'), 1, (select id from units where slug = 'tsp'), null, false, 5),
  ((select id from recipes where slug = 'indian-rajma'), (select id from ingredients where slug = 'turmeric'), 0.5, (select id from units where slug = 'tsp'), null, false, 6),
  ((select id from recipes where slug = 'indian-rajma'), (select id from ingredients where slug = 'tomato_paste'), 2, (select id from units where slug = 'tbsp'), null, false, 7),
  ((select id from recipes where slug = 'indian-rajma'), (select id from ingredients where slug = 'olive_oil'), 2, (select id from units where slug = 'tbsp'), null, false, 8),
  ((select id from recipes where slug = 'indian-rajma'), (select id from ingredients where slug = 'white_rice'), 1, (select id from units where slug = 'cup'), 'uncooked', false, 9),
  ((select id from recipes where slug = 'indian-rajma'), (select id from ingredients where slug = 'cilantro'), 2, (select id from units where slug = 'tbsp'), null, true, 10),
  ((select id from recipes where slug = 'indian-rajma'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 11);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'indian-rajma'), 1, 'Heat oil; soften onion, garlic, and ginger, about 6 minutes.'),
  ((select id from recipes where slug = 'indian-rajma'), 2, 'Add cumin, garam masala, and turmeric; cook 1 minute.'),
  ((select id from recipes where slug = 'indian-rajma'), 3, 'Stir in tomato paste and the beans (with some liquid). Simmer 20 minutes, mashing some beans for thickness.'),
  ((select id from recipes where slug = 'indian-rajma'), 4, 'Cook rice, season the beans with salt, garnish with cilantro, and serve over rice.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'indian-rajma'), 'dinner'),
  ((select id from recipes where slug = 'indian-rajma'), 'lunch');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'indian-rajma'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'indian-rajma'), (select id from diet_tags where slug = 'vegan')),
  ((select id from recipes where slug = 'indian-rajma'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'indian-rajma'), (select id from diet_tags where slug = 'dairy_free'));

-- Greek-Style Baked Beans (Greek)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('greek-gigantes-style-beans', 'Greek-Style Baked Beans', 'Large beans baked in a rich tomato and herb sauce.', 4, 10, 35, 'Greek', 1, 455.8, 21.7, 70.0, 11.7);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), (select id from ingredients where slug = 'pinto_beans_canned'), 2, (select id from units where slug = 'can'), null, false, 0),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), (select id from ingredients where slug = 'onion'), 1, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), (select id from ingredients where slug = 'garlic'), 3, (select id from units where slug = 'clove'), null, false, 2),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), (select id from ingredients where slug = 'carrot'), 1, (select id from units where slug = 'each'), 'diced', false, 3),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), (select id from ingredients where slug = 'tomato_canned_diced'), 2, (select id from units where slug = 'can'), null, false, 4),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), (select id from ingredients where slug = 'oregano_dried'), 1, (select id from units where slug = 'tsp'), null, false, 5),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), (select id from ingredients where slug = 'olive_oil'), 3, (select id from units where slug = 'tbsp'), null, false, 6),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), (select id from ingredients where slug = 'feta_cheese'), 0.33, (select id from units where slug = 'cup'), null, true, 7),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), (select id from ingredients where slug = 'parsley'), 2, (select id from units where slug = 'tbsp'), null, true, 8),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 9);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), 1, 'Preheat oven to 375°F (190°C). Heat 2 tbsp oil; soften onion, garlic, and carrot, about 6 minutes.'),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), 2, 'Stir in diced tomatoes, oregano, and salt; simmer 5 minutes.'),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), 3, 'Add beans, transfer to a baking dish, drizzle with remaining oil, and bake 25 minutes until bubbling.'),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), 4, 'Top with feta and parsley before serving.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), 'dinner'),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), 'lunch');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), (select id from diet_tags where slug = 'vegan')),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'greek-gigantes-style-beans'), (select id from diet_tags where slug = 'dairy_free'));

-- Caribbean Rice and Peas (Caribbean)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('caribbean-rice-and-peas', 'Caribbean Rice and Peas', 'Coconut rice simmered with pinto beans and warm spice.', 4, 10, 25, 'Caribbean', 1, 492.8, 14.4, 57.2, 24.9);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), (select id from ingredients where slug = 'pinto_beans_canned'), 1, (select id from units where slug = 'can'), null, false, 0),
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), (select id from ingredients where slug = 'white_rice'), 1.5, (select id from units where slug = 'cup'), 'uncooked', false, 1),
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), (select id from ingredients where slug = 'coconut_milk'), 1, (select id from units where slug = 'can'), null, false, 2),
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), (select id from ingredients where slug = 'onion'), 0.5, (select id from units where slug = 'each'), null, false, 3),
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), (select id from ingredients where slug = 'garlic'), 2, (select id from units where slug = 'clove'), null, false, 4),
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), (select id from ingredients where slug = 'thyme_dried'), 1, (select id from units where slug = 'tsp'), null, false, 5),
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), (select id from ingredients where slug = 'green_onion'), 2, (select id from units where slug = 'each'), null, false, 6),
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 7);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), 1, 'Combine rice, coconut milk, 1 cup water, onion, garlic, thyme, and salt in a pot.'),
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), 2, 'Bring to a boil, then reduce heat, cover, and simmer 15-18 minutes until the rice is tender.'),
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), 3, 'Stir in the beans and warm through. Top with green onion.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), 'dinner'),
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), 'lunch');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), (select id from diet_tags where slug = 'vegan')),
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'caribbean-rice-and-peas'), (select id from diet_tags where slug = 'dairy_free'));

-- White Bean and Kale Soup (Italian)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('white-bean-and-kale-soup', 'White Bean and Kale Soup', 'A simple, hearty Tuscan-style bean and greens soup.', 4, 10, 25, 'Italian', 1, 403.4, 21.0, 63.9, 8.3);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), (select id from ingredients where slug = 'pinto_beans_canned'), 2, (select id from units where slug = 'can'), 'or cannellini beans if available', false, 0),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), (select id from ingredients where slug = 'onion'), 1, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), (select id from ingredients where slug = 'garlic'), 3, (select id from units where slug = 'clove'), null, false, 2),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), (select id from ingredients where slug = 'carrot'), 1, (select id from units where slug = 'each'), 'diced', false, 3),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), (select id from ingredients where slug = 'kale'), 3, (select id from units where slug = 'cup'), 'chopped', false, 4),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), (select id from ingredients where slug = 'vegetable_broth'), 4, (select id from units where slug = 'cup'), null, false, 5),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), (select id from ingredients where slug = 'italian_seasoning'), 1, (select id from units where slug = 'tsp'), null, false, 6),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), (select id from ingredients where slug = 'olive_oil'), 2, (select id from units where slug = 'tbsp'), null, false, 7),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), (select id from ingredients where slug = 'parmesan_cheese'), 0.33, (select id from units where slug = 'cup'), null, true, 8),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 9);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), 1, 'Heat oil; soften onion, garlic, and carrot, about 6 minutes.'),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), 2, 'Add broth, beans, and italian seasoning. Simmer 15 minutes, mashing some beans for body.'),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), 3, 'Stir in kale and cook 3-4 minutes until wilted.'),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), 4, 'Season with salt and top with parmesan.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), 'lunch'),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), (select id from diet_tags where slug = 'vegan')),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'white-bean-and-kale-soup'), (select id from diet_tags where slug = 'dairy_free'));

-- Refried Bean Tostadas (Mexican)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('refried-bean-tostadas', 'Refried Bean Tostadas', 'Crispy tostadas piled with refried-style beans and fresh toppings.', 4, 10, 15, 'Mexican', 1, 537.2, 26.0, 79.4, 14.3);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'refried-bean-tostadas'), (select id from ingredients where slug = 'pinto_beans_canned'), 2, (select id from units where slug = 'can'), null, false, 0),
  ((select id from recipes where slug = 'refried-bean-tostadas'), (select id from ingredients where slug = 'garlic'), 2, (select id from units where slug = 'clove'), null, false, 1),
  ((select id from recipes where slug = 'refried-bean-tostadas'), (select id from ingredients where slug = 'cumin'), 1, (select id from units where slug = 'tsp'), null, false, 2),
  ((select id from recipes where slug = 'refried-bean-tostadas'), (select id from ingredients where slug = 'tortilla_corn'), 8, (select id from units where slug = 'each'), null, false, 3),
  ((select id from recipes where slug = 'refried-bean-tostadas'), (select id from ingredients where slug = 'olive_oil'), 2, (select id from units where slug = 'tbsp'), null, false, 4),
  ((select id from recipes where slug = 'refried-bean-tostadas'), (select id from ingredients where slug = 'lettuce_romaine'), 1, (select id from units where slug = 'cup'), 'shredded', false, 5),
  ((select id from recipes where slug = 'refried-bean-tostadas'), (select id from ingredients where slug = 'tomato'), 1, (select id from units where slug = 'each'), 'diced', false, 6),
  ((select id from recipes where slug = 'refried-bean-tostadas'), (select id from ingredients where slug = 'cheddar_cheese'), 0.5, (select id from units where slug = 'cup'), 'shredded', false, 7),
  ((select id from recipes where slug = 'refried-bean-tostadas'), (select id from ingredients where slug = 'sour_cream'), 0.25, (select id from units where slug = 'cup'), null, true, 8),
  ((select id from recipes where slug = 'refried-bean-tostadas'), (select id from ingredients where slug = 'salt'), 0.5, (select id from units where slug = 'tsp'), null, false, 9);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'refried-bean-tostadas'), 1, 'Crisp the tortillas in a dry pan or oven until golden and crunchy.'),
  ((select id from recipes where slug = 'refried-bean-tostadas'), 2, 'Heat 1 tbsp oil; sauté garlic, then add beans, cumin, and salt. Mash to a chunky paste, adding a splash of water if needed.'),
  ((select id from recipes where slug = 'refried-bean-tostadas'), 3, 'Spread beans on the tostadas and top with lettuce, tomato, cheese, and sour cream.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'refried-bean-tostadas'), 'lunch'),
  ((select id from recipes where slug = 'refried-bean-tostadas'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'refried-bean-tostadas'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'refried-bean-tostadas'), (select id from diet_tags where slug = 'gluten_free'));

