-- Groundwork seed — recipes: pork
-- GENERATED by scripts/generate-recipes.mjs from scripts/recipe-data/pork.mjs — do not hand-edit.
-- Edit the source recipe definitions and re-run: npm run gen:recipes
--
-- kcal_per_serving/protein/carb/fat are COMPUTED from the ingredient list
-- below at generation time, not hand-typed — see this script's header.

-- Cuban-Style Pork Tenderloin (Cuban)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('cuban-style-pork-tenderloin', 'Cuban-Style Pork Tenderloin', 'Citrus-garlic marinated pork tenderloin, roasted until juicy.', 4, 15, 25, 'Cuban', 2, 533.0, 56.9, 44.7, 13.8);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), (select id from ingredients where slug = 'pork_tenderloin'), 700, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), (select id from ingredients where slug = 'lime'), 2, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), (select id from ingredients where slug = 'garlic'), 4, (select id from units where slug = 'clove'), null, false, 2),
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), (select id from ingredients where slug = 'cumin'), 1, (select id from units where slug = 'tsp'), null, false, 3),
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), (select id from ingredients where slug = 'oregano_dried'), 1, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), (select id from ingredients where slug = 'olive_oil'), 2, (select id from units where slug = 'tbsp'), null, false, 5),
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), (select id from ingredients where slug = 'white_rice'), 1, (select id from units where slug = 'cup'), 'uncooked', false, 6),
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), (select id from ingredients where slug = 'black_beans_canned'), 1, (select id from units where slug = 'can'), null, false, 7),
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), (select id from ingredients where slug = 'salt'), 1.5, (select id from units where slug = 'tsp'), null, false, 8);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), 1, 'Whisk lime juice, minced garlic, cumin, oregano, olive oil, and salt. Marinate the pork at least 15 minutes.'),
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), 2, 'Preheat oven to 400°F (200°C). Sear the pork in an oven-safe pan on all sides, about 5 minutes total.'),
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), 3, 'Transfer to the oven and roast 15-18 minutes until internal temperature reaches 145°F (63°C). Rest 5 minutes before slicing.'),
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), 4, 'Cook rice according to package directions and warm the black beans.'),
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), 5, 'Serve sliced pork over rice and beans.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), (select id from diet_tags where slug = 'dairy_free')),
  ((select id from recipes where slug = 'cuban-style-pork-tenderloin'), (select id from diet_tags where slug = 'high_protein'));

-- Skillet Pork Chops with Apple (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('pork-chops-with-apple', 'Skillet Pork Chops with Apple', 'Seared pork chops with a quick apple and onion pan sauce.', 4, 10, 20, 'American', 2, 500.0, 44.5, 3.9, 33.4);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'pork-chops-with-apple'), (select id from ingredients where slug = 'pork_chop'), 700, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'pork-chops-with-apple'), (select id from ingredients where slug = 'onion'), 1, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'pork-chops-with-apple'), (select id from ingredients where slug = 'butter'), 2, (select id from units where slug = 'tbsp'), null, false, 2),
  ((select id from recipes where slug = 'pork-chops-with-apple'), (select id from ingredients where slug = 'thyme_dried'), 1, (select id from units where slug = 'tsp'), null, false, 3),
  ((select id from recipes where slug = 'pork-chops-with-apple'), (select id from ingredients where slug = 'chicken_broth'), 0.5, (select id from units where slug = 'cup'), null, false, 4),
  ((select id from recipes where slug = 'pork-chops-with-apple'), (select id from ingredients where slug = 'olive_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 5),
  ((select id from recipes where slug = 'pork-chops-with-apple'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 6),
  ((select id from recipes where slug = 'pork-chops-with-apple'), (select id from ingredients where slug = 'black_pepper'), 0.5, (select id from units where slug = 'tsp'), null, false, 7);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'pork-chops-with-apple'), 1, 'Season pork chops with salt and pepper. Sear in olive oil over medium-high heat, 4-5 minutes per side; remove.'),
  ((select id from recipes where slug = 'pork-chops-with-apple'), 2, 'Add butter, onion, and thyme to the pan; cook 5 minutes until softened.'),
  ((select id from recipes where slug = 'pork-chops-with-apple'), 3, 'Pour in broth, scraping up browned bits, and simmer 3 minutes.'),
  ((select id from recipes where slug = 'pork-chops-with-apple'), 4, 'Return the chops to the pan, spoon the sauce over, and warm through.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'pork-chops-with-apple'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'pork-chops-with-apple'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'pork-chops-with-apple'), (select id from diet_tags where slug = 'high_protein'));

-- Char Siu-Style Pork Tenderloin (Chinese)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('char-siu-style-pork', 'Char Siu-Style Pork Tenderloin', 'Sweet and savory glazed roasted pork, Chinese barbecue style.', 4, 10, 25, 'Chinese', 2, 385.2, 48.1, 29.9, 6.8);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'char-siu-style-pork'), (select id from ingredients where slug = 'pork_tenderloin'), 700, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'char-siu-style-pork'), (select id from ingredients where slug = 'hoisin_sauce'), 3, (select id from units where slug = 'tbsp'), null, false, 1),
  ((select id from recipes where slug = 'char-siu-style-pork'), (select id from ingredients where slug = 'soy_sauce'), 2, (select id from units where slug = 'tbsp'), null, false, 2),
  ((select id from recipes where slug = 'char-siu-style-pork'), (select id from ingredients where slug = 'honey'), 2, (select id from units where slug = 'tbsp'), null, false, 3),
  ((select id from recipes where slug = 'char-siu-style-pork'), (select id from ingredients where slug = 'five_spice'), 0.5, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'char-siu-style-pork'), (select id from ingredients where slug = 'garlic'), 2, (select id from units where slug = 'clove'), null, false, 5),
  ((select id from recipes where slug = 'char-siu-style-pork'), (select id from ingredients where slug = 'white_rice'), 1, (select id from units where slug = 'cup'), 'uncooked', false, 6),
  ((select id from recipes where slug = 'char-siu-style-pork'), (select id from ingredients where slug = 'green_onion'), 2, (select id from units where slug = 'each'), null, false, 7);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'char-siu-style-pork'), 1, 'Whisk hoisin, soy sauce, honey, five spice, and minced garlic. Marinate the pork at least 15 minutes.'),
  ((select id from recipes where slug = 'char-siu-style-pork'), 2, 'Preheat oven to 400°F (200°C). Roast the pork on a lined tray for 20-25 minutes, basting with marinade twice, until internal temp reaches 145°F (63°C).'),
  ((select id from recipes where slug = 'char-siu-style-pork'), 3, 'Rest 5 minutes, then slice.'),
  ((select id from recipes where slug = 'char-siu-style-pork'), 4, 'Cook rice according to package directions and serve the pork over rice, topped with green onion.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'char-siu-style-pork'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'char-siu-style-pork'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'char-siu-style-pork'), (select id from diet_tags where slug = 'dairy_free')),
  ((select id from recipes where slug = 'char-siu-style-pork'), (select id from diet_tags where slug = 'high_protein'));

-- Pork Carnitas Bowl (Mexican)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('pork-carnitas-bowl', 'Pork Carnitas Bowl', 'Slow-braised, crisped pork with rice, beans, and lime.', 4, 15, 90, 'Mexican', 2, 541.2, 63.7, 44.8, 11.3);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'pork-carnitas-bowl'), (select id from ingredients where slug = 'pork_tenderloin'), 800, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'pork-carnitas-bowl'), (select id from ingredients where slug = 'lime'), 2, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'pork-carnitas-bowl'), (select id from ingredients where slug = 'garlic'), 4, (select id from units where slug = 'clove'), null, false, 2),
  ((select id from recipes where slug = 'pork-carnitas-bowl'), (select id from ingredients where slug = 'cumin'), 1, (select id from units where slug = 'tsp'), null, false, 3),
  ((select id from recipes where slug = 'pork-carnitas-bowl'), (select id from ingredients where slug = 'oregano_dried'), 1, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'pork-carnitas-bowl'), (select id from ingredients where slug = 'chicken_broth'), 1, (select id from units where slug = 'cup'), null, false, 5),
  ((select id from recipes where slug = 'pork-carnitas-bowl'), (select id from ingredients where slug = 'white_rice'), 1, (select id from units where slug = 'cup'), 'uncooked', false, 6),
  ((select id from recipes where slug = 'pork-carnitas-bowl'), (select id from ingredients where slug = 'black_beans_canned'), 1, (select id from units where slug = 'can'), null, false, 7),
  ((select id from recipes where slug = 'pork-carnitas-bowl'), (select id from ingredients where slug = 'olive_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 8),
  ((select id from recipes where slug = 'pork-carnitas-bowl'), (select id from ingredients where slug = 'salt'), 1.5, (select id from units where slug = 'tsp'), null, false, 9);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'pork-carnitas-bowl'), 1, 'Season the pork with cumin, oregano, and salt. Sear in oil on all sides, about 6 minutes.'),
  ((select id from recipes where slug = 'pork-carnitas-bowl'), 2, 'Add garlic, lime juice, and broth. Cover and simmer on low 75-90 minutes until the pork shreds easily.'),
  ((select id from recipes where slug = 'pork-carnitas-bowl'), 3, 'Shred the pork and crisp it under a broiler for 3-4 minutes, or in a hot pan.'),
  ((select id from recipes where slug = 'pork-carnitas-bowl'), 4, 'Cook rice according to package directions and warm the beans.'),
  ((select id from recipes where slug = 'pork-carnitas-bowl'), 5, 'Serve the pork over rice and beans with extra lime.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'pork-carnitas-bowl'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'pork-carnitas-bowl'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'pork-carnitas-bowl'), (select id from diet_tags where slug = 'dairy_free')),
  ((select id from recipes where slug = 'pork-carnitas-bowl'), (select id from diet_tags where slug = 'high_protein'));

-- Pork and Cabbage Stir-Fry (Chinese)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('pork-and-vegetable-dumplings-skillet', 'Pork and Cabbage Stir-Fry', 'Ground pork stir-fried with cabbage in a garlicky soy sauce.', 4, 10, 15, 'Chinese', 1, 473.6, 25.2, 22.2, 31.1);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), (select id from ingredients where slug = 'ground_pork'), 500, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), (select id from ingredients where slug = 'cabbage'), 0.5, (select id from units where slug = 'each'), 'shredded', false, 1),
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), (select id from ingredients where slug = 'garlic'), 3, (select id from units where slug = 'clove'), null, false, 2),
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), (select id from ingredients where slug = 'ginger'), 1, (select id from units where slug = 'tbsp'), null, false, 3),
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), (select id from ingredients where slug = 'soy_sauce'), 3, (select id from units where slug = 'tbsp'), null, false, 4),
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), (select id from ingredients where slug = 'rice_vinegar'), 1, (select id from units where slug = 'tbsp'), null, false, 5),
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), (select id from ingredients where slug = 'sesame_oil'), 1, (select id from units where slug = 'tsp'), null, false, 6),
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), (select id from ingredients where slug = 'vegetable_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 7),
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), (select id from ingredients where slug = 'white_rice'), 1, (select id from units where slug = 'cup'), 'uncooked', false, 8);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), 1, 'Cook rice according to package directions.'),
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), 2, 'Heat oil in a wok; brown the ground pork with garlic and ginger, about 6 minutes.'),
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), 3, 'Add shredded cabbage and stir-fry 4-5 minutes until wilted but still with some crunch.'),
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), 4, 'Stir in soy sauce, rice vinegar, and sesame oil. Serve over rice.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'pork-and-vegetable-dumplings-skillet'), (select id from diet_tags where slug = 'dairy_free'));

-- Italian-Style Pork and Peppers Skillet (Italian)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('italian-sausage-and-peppers-skillet', 'Italian-Style Pork and Peppers Skillet', 'Ground pork seasoned Italian-style with peppers and onions.', 4, 10, 20, 'Italian', 1, 530.0, 29.4, 27.3, 33.1);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), (select id from ingredients where slug = 'ground_pork'), 500, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), (select id from ingredients where slug = 'bell_pepper_red'), 1, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), (select id from ingredients where slug = 'bell_pepper_green'), 1, (select id from units where slug = 'each'), null, false, 2),
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), (select id from ingredients where slug = 'onion'), 1, (select id from units where slug = 'each'), null, false, 3),
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), (select id from ingredients where slug = 'italian_seasoning'), 1.5, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), (select id from ingredients where slug = 'red_pepper_flakes'), 0.25, (select id from units where slug = 'tsp'), null, false, 5),
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), (select id from ingredients where slug = 'garlic'), 2, (select id from units where slug = 'clove'), null, false, 6),
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), (select id from ingredients where slug = 'olive_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 7),
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), (select id from ingredients where slug = 'pasta_penne'), 300, (select id from units where slug = 'g'), null, false, 8),
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), (select id from ingredients where slug = 'parmesan_cheese'), 0.33, (select id from units where slug = 'cup'), 'grated', false, 9),
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 10);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), 1, 'Cook pasta according to package directions.'),
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), 2, 'Heat oil in a large skillet; brown the ground pork with italian seasoning and red pepper flakes, about 7 minutes.'),
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), 3, 'Add peppers, onion, and garlic; cook 6-7 minutes until softened.'),
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), 4, 'Toss with the cooked pasta, season with salt, and top with parmesan.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'italian-sausage-and-peppers-skillet'), 'dinner');

-- Honey Garlic Pork Chops (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('honey-garlic-pork-chops', 'Honey Garlic Pork Chops', 'Pan-seared pork chops glazed with a sticky honey-garlic sauce.', 4, 10, 15, 'American', 1, 513.4, 45.9, 19.5, 28.1);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), (select id from ingredients where slug = 'pork_chop'), 700, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), (select id from ingredients where slug = 'garlic'), 3, (select id from units where slug = 'clove'), null, false, 1),
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), (select id from ingredients where slug = 'honey'), 3, (select id from units where slug = 'tbsp'), null, false, 2),
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), (select id from ingredients where slug = 'soy_sauce'), 2, (select id from units where slug = 'tbsp'), null, false, 3),
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), (select id from ingredients where slug = 'olive_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 4),
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), (select id from ingredients where slug = 'green_beans'), 300, (select id from units where slug = 'g'), null, false, 5),
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 6),
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), (select id from ingredients where slug = 'black_pepper'), 0.5, (select id from units where slug = 'tsp'), null, false, 7);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), 1, 'Season pork chops with salt and pepper. Sear in oil over medium-high heat, 4-5 minutes per side; remove.'),
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), 2, 'Add garlic to the pan, then honey and soy sauce; simmer 1-2 minutes until slightly thickened.'),
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), 3, 'Return the chops to the pan and coat in the glaze.'),
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), 4, 'Steam the green beans and serve alongside.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), (select id from diet_tags where slug = 'dairy_free')),
  ((select id from recipes where slug = 'honey-garlic-pork-chops'), (select id from diet_tags where slug = 'high_protein'));

