-- Groundwork seed — recipes: ground-beef
-- GENERATED by scripts/generate-recipes.mjs from scripts/recipe-data/ground-beef.mjs — do not hand-edit.
-- Edit the source recipe definitions and re-run: npm run gen:recipes
--
-- kcal_per_serving/protein/carb/fat are COMPUTED from the ingredient list
-- below at generation time, not hand-typed — see this script's header.

-- Classic Beef Tacos (Mexican)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('classic-beef-tacos', 'Classic Beef Tacos', 'Seasoned ground beef in warm tortillas with fresh toppings.', 4, 10, 15, 'Mexican', 1, 410.7, 32.3, 28.9, 18.8);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'classic-beef-tacos'), (select id from ingredients where slug = 'ground_beef'), 500, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'classic-beef-tacos'), (select id from ingredients where slug = 'onion'), 0.5, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'classic-beef-tacos'), (select id from ingredients where slug = 'taco_seasoning'), 2, (select id from units where slug = 'tbsp'), null, false, 2),
  ((select id from recipes where slug = 'classic-beef-tacos'), (select id from ingredients where slug = 'tortilla_corn'), 8, (select id from units where slug = 'each'), null, false, 3),
  ((select id from recipes where slug = 'classic-beef-tacos'), (select id from ingredients where slug = 'lettuce_romaine'), 1, (select id from units where slug = 'cup'), 'shredded', false, 4),
  ((select id from recipes where slug = 'classic-beef-tacos'), (select id from ingredients where slug = 'tomato'), 1, (select id from units where slug = 'each'), 'diced', false, 5),
  ((select id from recipes where slug = 'classic-beef-tacos'), (select id from ingredients where slug = 'cheddar_cheese'), 0.5, (select id from units where slug = 'cup'), 'shredded', false, 6),
  ((select id from recipes where slug = 'classic-beef-tacos'), (select id from ingredients where slug = 'sour_cream'), 0.25, (select id from units where slug = 'cup'), null, true, 7),
  ((select id from recipes where slug = 'classic-beef-tacos'), (select id from ingredients where slug = 'lime'), 1, (select id from units where slug = 'each'), null, false, 8);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'classic-beef-tacos'), 1, 'Cook ground beef and diced onion in a skillet over medium-high heat until browned, about 7 minutes.'),
  ((select id from recipes where slug = 'classic-beef-tacos'), 2, 'Drain excess fat, add taco seasoning and a splash of water, and simmer 2 minutes.'),
  ((select id from recipes where slug = 'classic-beef-tacos'), 3, 'Warm the tortillas in a dry pan or microwave.'),
  ((select id from recipes where slug = 'classic-beef-tacos'), 4, 'Fill tortillas with beef, lettuce, tomato, and cheddar. Serve with sour cream and lime.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'classic-beef-tacos'), 'dinner'),
  ((select id from recipes where slug = 'classic-beef-tacos'), 'lunch');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'classic-beef-tacos'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'classic-beef-tacos'), (select id from diet_tags where slug = 'high_protein'));

-- Spaghetti Bolognese (Italian)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('spaghetti-bolognese', 'Spaghetti Bolognese', 'Rich tomato and ground beef sauce over spaghetti.', 4, 10, 35, 'Italian', 2, 485.4, 37.0, 38.3, 20.8);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'spaghetti-bolognese'), (select id from ingredients where slug = 'ground_beef'), 500, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'spaghetti-bolognese'), (select id from ingredients where slug = 'onion'), 1, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'spaghetti-bolognese'), (select id from ingredients where slug = 'garlic'), 3, (select id from units where slug = 'clove'), null, false, 2),
  ((select id from recipes where slug = 'spaghetti-bolognese'), (select id from ingredients where slug = 'carrot'), 1, (select id from units where slug = 'each'), 'diced', false, 3),
  ((select id from recipes where slug = 'spaghetti-bolognese'), (select id from ingredients where slug = 'celery'), 1, (select id from units where slug = 'each'), 'diced', false, 4),
  ((select id from recipes where slug = 'spaghetti-bolognese'), (select id from ingredients where slug = 'tomato_canned_diced'), 2, (select id from units where slug = 'can'), null, false, 5),
  ((select id from recipes where slug = 'spaghetti-bolognese'), (select id from ingredients where slug = 'tomato_paste'), 2, (select id from units where slug = 'tbsp'), null, false, 6),
  ((select id from recipes where slug = 'spaghetti-bolognese'), (select id from ingredients where slug = 'italian_seasoning'), 1, (select id from units where slug = 'tsp'), null, false, 7),
  ((select id from recipes where slug = 'spaghetti-bolognese'), (select id from ingredients where slug = 'olive_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 8),
  ((select id from recipes where slug = 'spaghetti-bolognese'), (select id from ingredients where slug = 'spaghetti'), 340, (select id from units where slug = 'g'), null, false, 9),
  ((select id from recipes where slug = 'spaghetti-bolognese'), (select id from ingredients where slug = 'parmesan_cheese'), 0.5, (select id from units where slug = 'cup'), 'grated', false, 10),
  ((select id from recipes where slug = 'spaghetti-bolognese'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 11);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'spaghetti-bolognese'), 1, 'Heat oil in a large pot; soften onion, garlic, carrot, and celery, about 6 minutes.'),
  ((select id from recipes where slug = 'spaghetti-bolognese'), 2, 'Add ground beef and cook until browned, breaking it up as it cooks.'),
  ((select id from recipes where slug = 'spaghetti-bolognese'), 3, 'Stir in tomato paste, diced tomatoes, italian seasoning, and salt. Simmer uncovered 20-25 minutes, stirring occasionally.'),
  ((select id from recipes where slug = 'spaghetti-bolognese'), 4, 'Cook spaghetti according to package directions.'),
  ((select id from recipes where slug = 'spaghetti-bolognese'), 5, 'Toss the pasta with the sauce and serve topped with parmesan.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'spaghetti-bolognese'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'spaghetti-bolognese'), (select id from diet_tags where slug = 'high_protein'));

-- Beef and Broccoli Stir-Fry (Chinese)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('beef-and-broccoli-stir-fry', 'Beef and Broccoli Stir-Fry', 'Quick stir-fried beef and broccoli in a savory garlic sauce.', 4, 15, 12, 'Chinese', 2, 376.0, 30.3, 23.6, 17.7);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), (select id from ingredients where slug = 'ground_beef'), 500, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), (select id from ingredients where slug = 'broccoli'), 400, (select id from units where slug = 'g'), 'cut into florets', false, 1),
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), (select id from ingredients where slug = 'garlic'), 2, (select id from units where slug = 'clove'), null, false, 2),
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), (select id from ingredients where slug = 'ginger'), 1, (select id from units where slug = 'tbsp'), null, false, 3),
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), (select id from ingredients where slug = 'soy_sauce'), 3, (select id from units where slug = 'tbsp'), null, false, 4),
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), (select id from ingredients where slug = 'oyster_sauce'), 2, (select id from units where slug = 'tbsp'), null, false, 5),
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), (select id from ingredients where slug = 'cornstarch'), 1, (select id from units where slug = 'tsp'), null, false, 6),
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), (select id from ingredients where slug = 'sesame_oil'), 1, (select id from units where slug = 'tsp'), null, false, 7),
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), (select id from ingredients where slug = 'vegetable_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 8),
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), (select id from ingredients where slug = 'white_rice'), 1, (select id from units where slug = 'cup'), 'uncooked', false, 9);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), 1, 'Cook rice according to package directions.'),
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), 2, 'Steam or blanch the broccoli 3 minutes until bright green and just tender; set aside.'),
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), 3, 'Whisk soy sauce, oyster sauce, and cornstarch in a small bowl.'),
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), 4, 'Heat oil in a wok over high heat. Brown the ground beef with garlic and ginger, about 5 minutes.'),
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), 5, 'Add the broccoli and sauce; toss until the sauce thickens and coats everything, about 2 minutes. Finish with sesame oil and serve over rice.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), (select id from diet_tags where slug = 'dairy_free')),
  ((select id from recipes where slug = 'beef-and-broccoli-stir-fry'), (select id from diet_tags where slug = 'high_protein'));

-- Stuffed Bell Peppers (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('stuffed-bell-peppers', 'Stuffed Bell Peppers', 'Bell peppers filled with seasoned beef, rice, and tomato.', 4, 15, 40, 'American', 2, 406.3, 31.9, 21.9, 21.1);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'stuffed-bell-peppers'), (select id from ingredients where slug = 'ground_beef'), 500, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'stuffed-bell-peppers'), (select id from ingredients where slug = 'bell_pepper_red'), 2, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'stuffed-bell-peppers'), (select id from ingredients where slug = 'bell_pepper_green'), 2, (select id from units where slug = 'each'), null, false, 2),
  ((select id from recipes where slug = 'stuffed-bell-peppers'), (select id from ingredients where slug = 'onion'), 0.5, (select id from units where slug = 'each'), null, false, 3),
  ((select id from recipes where slug = 'stuffed-bell-peppers'), (select id from ingredients where slug = 'white_rice'), 0.5, (select id from units where slug = 'cup'), 'uncooked', false, 4),
  ((select id from recipes where slug = 'stuffed-bell-peppers'), (select id from ingredients where slug = 'tomato_canned_diced'), 1, (select id from units where slug = 'can'), null, false, 5),
  ((select id from recipes where slug = 'stuffed-bell-peppers'), (select id from ingredients where slug = 'cheddar_cheese'), 0.5, (select id from units where slug = 'cup'), 'shredded', false, 6),
  ((select id from recipes where slug = 'stuffed-bell-peppers'), (select id from ingredients where slug = 'garlic_powder'), 1, (select id from units where slug = 'tsp'), null, false, 7),
  ((select id from recipes where slug = 'stuffed-bell-peppers'), (select id from ingredients where slug = 'oregano_dried'), 1, (select id from units where slug = 'tsp'), null, false, 8),
  ((select id from recipes where slug = 'stuffed-bell-peppers'), (select id from ingredients where slug = 'olive_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 9),
  ((select id from recipes where slug = 'stuffed-bell-peppers'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 10);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'stuffed-bell-peppers'), 1, 'Preheat oven to 375°F (190°C). Cook rice according to package directions.'),
  ((select id from recipes where slug = 'stuffed-bell-peppers'), 2, 'Halve the bell peppers lengthwise and remove seeds. Arrange in a baking dish.'),
  ((select id from recipes where slug = 'stuffed-bell-peppers'), 3, 'Cook ground beef and onion in a skillet until browned. Stir in cooked rice, half the tomatoes, garlic powder, oregano, and salt.'),
  ((select id from recipes where slug = 'stuffed-bell-peppers'), 4, 'Fill each pepper half with the beef mixture, top with remaining tomatoes, and cover with foil.'),
  ((select id from recipes where slug = 'stuffed-bell-peppers'), 5, 'Bake 25 minutes, uncover, top with cheddar, and bake 10 more minutes until the cheese melts and peppers are tender.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'stuffed-bell-peppers'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'stuffed-bell-peppers'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'stuffed-bell-peppers'), (select id from diet_tags where slug = 'high_protein'));

-- Beef Chili (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('beef-chili', 'Beef Chili', 'Hearty chili with ground beef, beans, and warm spices.', 6, 10, 40, 'American', 1, 475.0, 38.5, 47.8, 15.4);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'beef-chili'), (select id from ingredients where slug = 'ground_beef'), 700, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'beef-chili'), (select id from ingredients where slug = 'onion'), 1, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'beef-chili'), (select id from ingredients where slug = 'garlic'), 3, (select id from units where slug = 'clove'), null, false, 2),
  ((select id from recipes where slug = 'beef-chili'), (select id from ingredients where slug = 'bell_pepper_green'), 1, (select id from units where slug = 'each'), null, false, 3),
  ((select id from recipes where slug = 'beef-chili'), (select id from ingredients where slug = 'chili_powder'), 2, (select id from units where slug = 'tbsp'), null, false, 4),
  ((select id from recipes where slug = 'beef-chili'), (select id from ingredients where slug = 'cumin'), 1, (select id from units where slug = 'tsp'), null, false, 5),
  ((select id from recipes where slug = 'beef-chili'), (select id from ingredients where slug = 'smoked_paprika'), 1, (select id from units where slug = 'tsp'), null, false, 6),
  ((select id from recipes where slug = 'beef-chili'), (select id from ingredients where slug = 'tomato_canned_diced'), 2, (select id from units where slug = 'can'), null, false, 7),
  ((select id from recipes where slug = 'beef-chili'), (select id from ingredients where slug = 'tomato_paste'), 2, (select id from units where slug = 'tbsp'), null, false, 8),
  ((select id from recipes where slug = 'beef-chili'), (select id from ingredients where slug = 'black_beans_canned'), 1, (select id from units where slug = 'can'), null, false, 9),
  ((select id from recipes where slug = 'beef-chili'), (select id from ingredients where slug = 'pinto_beans_canned'), 1, (select id from units where slug = 'can'), null, false, 10),
  ((select id from recipes where slug = 'beef-chili'), (select id from ingredients where slug = 'olive_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 11),
  ((select id from recipes where slug = 'beef-chili'), (select id from ingredients where slug = 'salt'), 1.5, (select id from units where slug = 'tsp'), null, false, 12);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'beef-chili'), 1, 'Heat oil in a large pot; soften onion, garlic, and bell pepper, about 5 minutes.'),
  ((select id from recipes where slug = 'beef-chili'), 2, 'Add ground beef and cook until browned.'),
  ((select id from recipes where slug = 'beef-chili'), 3, 'Stir in chili powder, cumin, and smoked paprika; cook 1 minute.'),
  ((select id from recipes where slug = 'beef-chili'), 4, 'Add diced tomatoes, tomato paste, black beans, and pinto beans. Simmer uncovered 30 minutes, stirring occasionally.'),
  ((select id from recipes where slug = 'beef-chili'), 5, 'Season with salt and serve.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'beef-chili'), 'dinner'),
  ((select id from recipes where slug = 'beef-chili'), 'lunch');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'beef-chili'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'beef-chili'), (select id from diet_tags where slug = 'dairy_free')),
  ((select id from recipes where slug = 'beef-chili'), (select id from diet_tags where slug = 'high_protein'));

-- Beef Koftas with Yogurt Sauce (Middle Eastern)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('beef-koftas-with-yogurt-sauce', 'Beef Koftas with Yogurt Sauce', 'Spiced grilled beef kofta skewers with a cool yogurt dip.', 4, 15, 12, 'Middle Eastern', 2, 419.4, 34.1, 38.1, 13.6);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), (select id from ingredients where slug = 'ground_beef'), 500, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), (select id from ingredients where slug = 'onion'), 0.25, (select id from units where slug = 'each'), 'grated', false, 1),
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), (select id from ingredients where slug = 'garlic'), 2, (select id from units where slug = 'clove'), null, false, 2),
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), (select id from ingredients where slug = 'cumin'), 1, (select id from units where slug = 'tsp'), null, false, 3),
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), (select id from ingredients where slug = 'coriander_ground'), 1, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), (select id from ingredients where slug = 'cinnamon'), 0.25, (select id from units where slug = 'tsp'), null, false, 5),
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), (select id from ingredients where slug = 'parsley'), 2, (select id from units where slug = 'tbsp'), 'chopped', false, 6),
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), (select id from ingredients where slug = 'greek_yogurt'), 0.5, (select id from units where slug = 'cup'), null, false, 7),
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), (select id from ingredients where slug = 'lemon'), 1, (select id from units where slug = 'each'), null, false, 8),
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), (select id from ingredients where slug = 'pita_bread'), 4, (select id from units where slug = 'each'), null, false, 9),
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 10);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), 1, 'Mix ground beef with grated onion, garlic, cumin, coriander, cinnamon, parsley, and salt. Shape into small logs on skewers.'),
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), 2, 'Whisk yogurt with lemon juice and a pinch of salt for the sauce.'),
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), 3, 'Grill or pan-sear the koftas 10-12 minutes, turning occasionally, until cooked through.'),
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), 4, 'Warm the pita and serve with the koftas and yogurt sauce.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'beef-koftas-with-yogurt-sauce'), (select id from diet_tags where slug = 'high_protein'));

-- Beef and Rice Skillet (Mexican)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('beef-empanadas-skillet', 'Beef and Rice Skillet', 'One-pan spiced beef and rice with peppers and corn.', 4, 10, 25, 'Mexican', 1, 375.2, 30.2, 33.1, 13.8);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'beef-empanadas-skillet'), (select id from ingredients where slug = 'ground_beef'), 500, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'beef-empanadas-skillet'), (select id from ingredients where slug = 'onion'), 1, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'beef-empanadas-skillet'), (select id from ingredients where slug = 'bell_pepper_red'), 1, (select id from units where slug = 'each'), null, false, 2),
  ((select id from recipes where slug = 'beef-empanadas-skillet'), (select id from ingredients where slug = 'white_rice'), 1, (select id from units where slug = 'cup'), 'uncooked', false, 3),
  ((select id from recipes where slug = 'beef-empanadas-skillet'), (select id from ingredients where slug = 'chicken_broth'), 1, (select id from units where slug = 'can'), null, false, 4),
  ((select id from recipes where slug = 'beef-empanadas-skillet'), (select id from ingredients where slug = 'tomato_canned_diced'), 1, (select id from units where slug = 'can'), null, false, 5),
  ((select id from recipes where slug = 'beef-empanadas-skillet'), (select id from ingredients where slug = 'corn'), 1, (select id from units where slug = 'cup'), null, false, 6),
  ((select id from recipes where slug = 'beef-empanadas-skillet'), (select id from ingredients where slug = 'chili_powder'), 1, (select id from units where slug = 'tsp'), null, false, 7),
  ((select id from recipes where slug = 'beef-empanadas-skillet'), (select id from ingredients where slug = 'cumin'), 1, (select id from units where slug = 'tsp'), null, false, 8),
  ((select id from recipes where slug = 'beef-empanadas-skillet'), (select id from ingredients where slug = 'cheddar_cheese'), 0.5, (select id from units where slug = 'cup'), 'shredded', true, 9),
  ((select id from recipes where slug = 'beef-empanadas-skillet'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 10);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'beef-empanadas-skillet'), 1, 'Brown ground beef with onion and bell pepper in a large skillet, about 6 minutes.'),
  ((select id from recipes where slug = 'beef-empanadas-skillet'), 2, 'Stir in rice, broth, diced tomatoes, chili powder, and cumin.'),
  ((select id from recipes where slug = 'beef-empanadas-skillet'), 3, 'Bring to a simmer, cover, and cook 18-20 minutes until the rice is tender.'),
  ((select id from recipes where slug = 'beef-empanadas-skillet'), 4, 'Stir in corn, season with salt, top with cheddar if using, and let it melt before serving.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'beef-empanadas-skillet'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'beef-empanadas-skillet'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'beef-empanadas-skillet'), (select id from diet_tags where slug = 'dairy_free')),
  ((select id from recipes where slug = 'beef-empanadas-skillet'), (select id from diet_tags where slug = 'high_protein'));

-- Juicy Beef Burgers (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('juicy-beef-burgers', 'Juicy Beef Burgers', 'Classic grilled beef burgers with all the fixings.', 4, 10, 10, 'American', 1, 433.0, 38.3, 16.2, 23.0);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'juicy-beef-burgers'), (select id from ingredients where slug = 'ground_beef'), 600, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'juicy-beef-burgers'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 1),
  ((select id from recipes where slug = 'juicy-beef-burgers'), (select id from ingredients where slug = 'black_pepper'), 0.5, (select id from units where slug = 'tsp'), null, false, 2),
  ((select id from recipes where slug = 'juicy-beef-burgers'), (select id from ingredients where slug = 'garlic_powder'), 1, (select id from units where slug = 'tsp'), null, false, 3),
  ((select id from recipes where slug = 'juicy-beef-burgers'), (select id from ingredients where slug = 'bread_sandwich'), 4, (select id from units where slug = 'slice'), 'or 4 burger buns', false, 4),
  ((select id from recipes where slug = 'juicy-beef-burgers'), (select id from ingredients where slug = 'cheddar_cheese'), 4, (select id from units where slug = 'slice'), null, false, 5),
  ((select id from recipes where slug = 'juicy-beef-burgers'), (select id from ingredients where slug = 'lettuce_romaine'), 1, (select id from units where slug = 'cup'), 'shredded', false, 6),
  ((select id from recipes where slug = 'juicy-beef-burgers'), (select id from ingredients where slug = 'tomato'), 1, (select id from units where slug = 'each'), 'sliced', false, 7),
  ((select id from recipes where slug = 'juicy-beef-burgers'), (select id from ingredients where slug = 'mayonnaise'), 2, (select id from units where slug = 'tbsp'), null, true, 8);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'juicy-beef-burgers'), 1, 'Mix ground beef with salt, pepper, and garlic powder; shape into 4 patties.'),
  ((select id from recipes where slug = 'juicy-beef-burgers'), 2, 'Grill or pan-sear over medium-high heat, about 4 minutes per side, adding cheese in the last minute to melt.'),
  ((select id from recipes where slug = 'juicy-beef-burgers'), 3, 'Toast the bread or buns lightly.'),
  ((select id from recipes where slug = 'juicy-beef-burgers'), 4, 'Build the burgers with lettuce, tomato, and mayonnaise.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'juicy-beef-burgers'), 'dinner'),
  ((select id from recipes where slug = 'juicy-beef-burgers'), 'lunch');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'juicy-beef-burgers'), (select id from diet_tags where slug = 'high_protein'));

-- Asian Beef Lettuce Wraps (Chinese)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('beef-lettuce-wraps', 'Asian Beef Lettuce Wraps', 'Savory ground beef with a sweet-salty glaze, served in lettuce cups.', 4, 10, 12, 'Chinese', 1, 271.5, 26.8, 7.9, 14.1);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'beef-lettuce-wraps'), (select id from ingredients where slug = 'ground_beef'), 500, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'beef-lettuce-wraps'), (select id from ingredients where slug = 'garlic'), 2, (select id from units where slug = 'clove'), null, false, 1),
  ((select id from recipes where slug = 'beef-lettuce-wraps'), (select id from ingredients where slug = 'ginger'), 1, (select id from units where slug = 'tbsp'), null, false, 2),
  ((select id from recipes where slug = 'beef-lettuce-wraps'), (select id from ingredients where slug = 'soy_sauce'), 3, (select id from units where slug = 'tbsp'), null, false, 3),
  ((select id from recipes where slug = 'beef-lettuce-wraps'), (select id from ingredients where slug = 'hoisin_sauce'), 2, (select id from units where slug = 'tbsp'), null, false, 4),
  ((select id from recipes where slug = 'beef-lettuce-wraps'), (select id from ingredients where slug = 'rice_vinegar'), 1, (select id from units where slug = 'tbsp'), null, false, 5),
  ((select id from recipes where slug = 'beef-lettuce-wraps'), (select id from ingredients where slug = 'sesame_oil'), 1, (select id from units where slug = 'tsp'), null, false, 6),
  ((select id from recipes where slug = 'beef-lettuce-wraps'), (select id from ingredients where slug = 'carrot'), 1, (select id from units where slug = 'each'), 'shredded', false, 7),
  ((select id from recipes where slug = 'beef-lettuce-wraps'), (select id from ingredients where slug = 'green_onion'), 2, (select id from units where slug = 'each'), 'sliced', false, 8),
  ((select id from recipes where slug = 'beef-lettuce-wraps'), (select id from ingredients where slug = 'lettuce_romaine'), 8, (select id from units where slug = 'each'), 'whole leaves, for wrapping', false, 9);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'beef-lettuce-wraps'), 1, 'Brown ground beef with garlic and ginger in a skillet, about 6 minutes.'),
  ((select id from recipes where slug = 'beef-lettuce-wraps'), 2, 'Stir in soy sauce, hoisin, and rice vinegar; simmer 3 minutes until slightly thickened.'),
  ((select id from recipes where slug = 'beef-lettuce-wraps'), 3, 'Finish with sesame oil and stir in shredded carrot.'),
  ((select id from recipes where slug = 'beef-lettuce-wraps'), 4, 'Spoon the beef into lettuce leaves, top with green onion, and serve.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'beef-lettuce-wraps'), 'dinner'),
  ((select id from recipes where slug = 'beef-lettuce-wraps'), 'lunch');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'beef-lettuce-wraps'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'beef-lettuce-wraps'), (select id from diet_tags where slug = 'dairy_free'));

-- Beef and Potato Hash (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('beef-and-potato-hash', 'Beef and Potato Hash', 'A hearty skillet of ground beef, potatoes, and peppers.', 4, 10, 25, 'American', 1, 373.3, 25.7, 25.6, 18.3);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'beef-and-potato-hash'), (select id from ingredients where slug = 'ground_beef'), 450, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'beef-and-potato-hash'), (select id from ingredients where slug = 'potato'), 3, (select id from units where slug = 'each'), 'diced', false, 1),
  ((select id from recipes where slug = 'beef-and-potato-hash'), (select id from ingredients where slug = 'onion'), 0.5, (select id from units where slug = 'each'), null, false, 2),
  ((select id from recipes where slug = 'beef-and-potato-hash'), (select id from ingredients where slug = 'bell_pepper_green'), 1, (select id from units where slug = 'each'), null, false, 3),
  ((select id from recipes where slug = 'beef-and-potato-hash'), (select id from ingredients where slug = 'smoked_paprika'), 1, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'beef-and-potato-hash'), (select id from ingredients where slug = 'olive_oil'), 2, (select id from units where slug = 'tbsp'), null, false, 5),
  ((select id from recipes where slug = 'beef-and-potato-hash'), (select id from ingredients where slug = 'egg'), 4, (select id from units where slug = 'each'), 'fried, to top', true, 6),
  ((select id from recipes where slug = 'beef-and-potato-hash'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 7),
  ((select id from recipes where slug = 'beef-and-potato-hash'), (select id from ingredients where slug = 'black_pepper'), 0.5, (select id from units where slug = 'tsp'), null, false, 8);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'beef-and-potato-hash'), 1, 'Heat oil in a large skillet. Cook diced potato 10-12 minutes, stirring occasionally, until browned and nearly tender.'),
  ((select id from recipes where slug = 'beef-and-potato-hash'), 2, 'Push potatoes aside, add ground beef, and brown, breaking it up as it cooks.'),
  ((select id from recipes where slug = 'beef-and-potato-hash'), 3, 'Add onion, bell pepper, smoked paprika, salt, and pepper; cook 5 more minutes until vegetables soften.'),
  ((select id from recipes where slug = 'beef-and-potato-hash'), 4, 'Top with a fried egg per serving if desired.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'beef-and-potato-hash'), 'breakfast'),
  ((select id from recipes where slug = 'beef-and-potato-hash'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'beef-and-potato-hash'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'beef-and-potato-hash'), (select id from diet_tags where slug = 'dairy_free'));

-- Greek-Style Beef and Orzo Skillet (Greek)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('greek-beef-and-orzo', 'Greek-Style Beef and Orzo Skillet', 'One-pan spiced beef simmered with orzo, tomato, and feta.', 4, 10, 25, 'Greek', 1, 384.9, 30.8, 19.4, 20.1);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'greek-beef-and-orzo'), (select id from ingredients where slug = 'ground_beef'), 500, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'greek-beef-and-orzo'), (select id from ingredients where slug = 'onion'), 1, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'greek-beef-and-orzo'), (select id from ingredients where slug = 'garlic'), 2, (select id from units where slug = 'clove'), null, false, 2),
  ((select id from recipes where slug = 'greek-beef-and-orzo'), (select id from ingredients where slug = 'couscous'), 1, (select id from units where slug = 'cup'), 'uncooked', false, 3),
  ((select id from recipes where slug = 'greek-beef-and-orzo'), (select id from ingredients where slug = 'tomato_canned_diced'), 1, (select id from units where slug = 'can'), null, false, 4),
  ((select id from recipes where slug = 'greek-beef-and-orzo'), (select id from ingredients where slug = 'vegetable_broth'), 1.5, (select id from units where slug = 'cup'), null, false, 5),
  ((select id from recipes where slug = 'greek-beef-and-orzo'), (select id from ingredients where slug = 'oregano_dried'), 1, (select id from units where slug = 'tsp'), null, false, 6),
  ((select id from recipes where slug = 'greek-beef-and-orzo'), (select id from ingredients where slug = 'feta_cheese'), 0.5, (select id from units where slug = 'cup'), 'crumbled', false, 7),
  ((select id from recipes where slug = 'greek-beef-and-orzo'), (select id from ingredients where slug = 'olive_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 8),
  ((select id from recipes where slug = 'greek-beef-and-orzo'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 9);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'greek-beef-and-orzo'), 1, 'Heat oil; brown the ground beef with onion and garlic, about 7 minutes.'),
  ((select id from recipes where slug = 'greek-beef-and-orzo'), 2, 'Stir in couscous, diced tomatoes, broth, oregano, and salt.'),
  ((select id from recipes where slug = 'greek-beef-and-orzo'), 3, 'Bring to a simmer, cover, and cook 10 minutes until the couscous absorbs the liquid.'),
  ((select id from recipes where slug = 'greek-beef-and-orzo'), 4, 'Top with feta before serving.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'greek-beef-and-orzo'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'greek-beef-and-orzo'), (select id from diet_tags where slug = 'high_protein'));

-- Vietnamese-Style Ground Beef Noodle Bowl (Vietnamese)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('vietnamese-beef-noodle-bowl', 'Vietnamese-Style Ground Beef Noodle Bowl', 'Savory beef over rice noodles with fresh herbs and lime.', 4, 15, 12, 'Vietnamese', 2, 372.4, 27.1, 29.4, 16.2);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), (select id from ingredients where slug = 'ground_beef'), 500, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), (select id from ingredients where slug = 'garlic'), 3, (select id from units where slug = 'clove'), null, false, 1),
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), (select id from ingredients where slug = 'fish_sauce'), 2, (select id from units where slug = 'tbsp'), null, false, 2),
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), (select id from ingredients where slug = 'soy_sauce'), 1, (select id from units where slug = 'tbsp'), null, false, 3),
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), (select id from ingredients where slug = 'lime'), 2, (select id from units where slug = 'each'), null, false, 4),
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), (select id from ingredients where slug = 'honey'), 1, (select id from units where slug = 'tbsp'), null, false, 5),
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), (select id from ingredients where slug = 'rice_noodles'), 300, (select id from units where slug = 'g'), null, false, 6),
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), (select id from ingredients where slug = 'cucumber'), 0.5, (select id from units where slug = 'each'), 'julienned', false, 7),
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), (select id from ingredients where slug = 'cilantro'), 0.25, (select id from units where slug = 'cup'), null, false, 8),
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), (select id from ingredients where slug = 'bean_sprouts'), 1, (select id from units where slug = 'cup'), null, true, 9),
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), (select id from ingredients where slug = 'vegetable_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 10);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), 1, 'Cook rice noodles according to package directions; rinse and drain.'),
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), 2, 'Heat oil; brown the ground beef with garlic, about 6-7 minutes.'),
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), 3, 'Whisk fish sauce, soy sauce, lime juice, and honey for the dressing.'),
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), 4, 'Divide noodles into bowls, top with beef, cucumber, bean sprouts, and cilantro, and drizzle with dressing.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'vietnamese-beef-noodle-bowl'), (select id from diet_tags where slug = 'dairy_free'));

-- Brazilian-Style Beef and Rice (Brazilian)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('brazilian-beef-and-rice', 'Brazilian-Style Beef and Rice', 'Garlicky seasoned ground beef over rice with black beans.', 4, 10, 25, 'Brazilian', 1, 538.7, 38.5, 59.1, 16.9);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), (select id from ingredients where slug = 'ground_beef'), 500, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), (select id from ingredients where slug = 'onion'), 1, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), (select id from ingredients where slug = 'garlic'), 4, (select id from units where slug = 'clove'), null, false, 2),
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), (select id from ingredients where slug = 'bell_pepper_green'), 1, (select id from units where slug = 'each'), null, false, 3),
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), (select id from ingredients where slug = 'tomato_canned_diced'), 1, (select id from units where slug = 'can'), null, false, 4),
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), (select id from ingredients where slug = 'black_beans_canned'), 1, (select id from units where slug = 'can'), null, false, 5),
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), (select id from ingredients where slug = 'white_rice'), 1.5, (select id from units where slug = 'cup'), 'uncooked', false, 6),
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), (select id from ingredients where slug = 'olive_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 7),
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), (select id from ingredients where slug = 'lime'), 1, (select id from units where slug = 'each'), null, false, 8),
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 9);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), 1, 'Cook rice according to package directions.'),
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), 2, 'Heat oil; brown the beef with onion, garlic, and bell pepper, about 8 minutes.'),
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), 3, 'Stir in diced tomatoes and simmer 10 minutes.'),
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), 4, 'Warm the black beans separately and serve alongside the beef and rice with a squeeze of lime.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), (select id from diet_tags where slug = 'gluten_free')),
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), (select id from diet_tags where slug = 'dairy_free')),
  ((select id from recipes where slug = 'brazilian-beef-and-rice'), (select id from diet_tags where slug = 'high_protein'));

-- Beef Keema (Indian)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('indian-beef-keema', 'Beef Keema', 'Spiced ground beef simmered with peas, Indian-style.', 4, 10, 25, 'Indian', 2, 590.6, 36.2, 57.0, 22.7);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'indian-beef-keema'), (select id from ingredients where slug = 'ground_beef'), 500, (select id from units where slug = 'g'), null, false, 0),
  ((select id from recipes where slug = 'indian-beef-keema'), (select id from ingredients where slug = 'onion'), 1, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'indian-beef-keema'), (select id from ingredients where slug = 'garlic'), 3, (select id from units where slug = 'clove'), null, false, 2),
  ((select id from recipes where slug = 'indian-beef-keema'), (select id from ingredients where slug = 'ginger'), 1, (select id from units where slug = 'tbsp'), null, false, 3),
  ((select id from recipes where slug = 'indian-beef-keema'), (select id from ingredients where slug = 'garam_masala'), 1.5, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'indian-beef-keema'), (select id from ingredients where slug = 'turmeric'), 0.5, (select id from units where slug = 'tsp'), null, false, 5),
  ((select id from recipes where slug = 'indian-beef-keema'), (select id from ingredients where slug = 'cumin'), 1, (select id from units where slug = 'tsp'), null, false, 6),
  ((select id from recipes where slug = 'indian-beef-keema'), (select id from ingredients where slug = 'tomato_paste'), 2, (select id from units where slug = 'tbsp'), null, false, 7),
  ((select id from recipes where slug = 'indian-beef-keema'), (select id from ingredients where slug = 'peas'), 1, (select id from units where slug = 'cup'), null, false, 8),
  ((select id from recipes where slug = 'indian-beef-keema'), (select id from ingredients where slug = 'olive_oil'), 1, (select id from units where slug = 'tbsp'), null, false, 9),
  ((select id from recipes where slug = 'indian-beef-keema'), (select id from ingredients where slug = 'naan'), 4, (select id from units where slug = 'each'), null, false, 10),
  ((select id from recipes where slug = 'indian-beef-keema'), (select id from ingredients where slug = 'cilantro'), 2, (select id from units where slug = 'tbsp'), null, true, 11),
  ((select id from recipes where slug = 'indian-beef-keema'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 12);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'indian-beef-keema'), 1, 'Heat oil; soften onion, garlic, and ginger, about 5 minutes.'),
  ((select id from recipes where slug = 'indian-beef-keema'), 2, 'Add garam masala, turmeric, and cumin; cook 1 minute.'),
  ((select id from recipes where slug = 'indian-beef-keema'), 3, 'Add ground beef and cook until browned, breaking it up as it cooks.'),
  ((select id from recipes where slug = 'indian-beef-keema'), 4, 'Stir in tomato paste and peas; simmer 10 minutes. Season with salt.'),
  ((select id from recipes where slug = 'indian-beef-keema'), 5, 'Garnish with cilantro and serve with warm naan.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'indian-beef-keema'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'indian-beef-keema'), (select id from diet_tags where slug = 'dairy_free')),
  ((select id from recipes where slug = 'indian-beef-keema'), (select id from diet_tags where slug = 'high_protein'));

