-- Groundwork seed — recipes: oats
-- GENERATED by scripts/generate-recipes.mjs from scripts/recipe-data/oats.mjs — do not hand-edit.
-- Edit the source recipe definitions and re-run: npm run gen:recipes
--
-- kcal_per_serving/protein/carb/fat are COMPUTED from the ingredient list
-- below at generation time, not hand-typed — see this script's header.

-- Classic Oatmeal with Banana and Walnuts (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('classic-oatmeal-with-banana', 'Classic Oatmeal with Banana and Walnuts', 'Warm stovetop oatmeal with banana, walnuts, and cinnamon.', 1, 2, 8, 'American', 1, 531.5, 16.9, 85.6, 16.5);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'classic-oatmeal-with-banana'), (select id from ingredients where slug = 'rolled_oats'), 0.5, (select id from units where slug = 'cup'), null, false, 0),
  ((select id from recipes where slug = 'classic-oatmeal-with-banana'), (select id from ingredients where slug = 'milk'), 1, (select id from units where slug = 'cup'), null, false, 1),
  ((select id from recipes where slug = 'classic-oatmeal-with-banana'), (select id from ingredients where slug = 'cinnamon'), 0.25, (select id from units where slug = 'tsp'), null, false, 2),
  ((select id from recipes where slug = 'classic-oatmeal-with-banana'), (select id from ingredients where slug = 'honey'), 1, (select id from units where slug = 'tbsp'), null, false, 3),
  ((select id from recipes where slug = 'classic-oatmeal-with-banana'), (select id from ingredients where slug = 'walnuts'), 2, (select id from units where slug = 'tbsp'), null, false, 4),
  ((select id from recipes where slug = 'classic-oatmeal-with-banana'), (select id from ingredients where slug = 'banana'), 1, (select id from units where slug = 'each'), 'sliced', false, 5);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'classic-oatmeal-with-banana'), 1, 'Bring milk to a simmer in a small pot.'),
  ((select id from recipes where slug = 'classic-oatmeal-with-banana'), 2, 'Stir in oats and cinnamon; cook 5-6 minutes, stirring occasionally, until thickened.'),
  ((select id from recipes where slug = 'classic-oatmeal-with-banana'), 3, 'Top with sliced banana, walnuts, and a drizzle of honey.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'classic-oatmeal-with-banana'), 'breakfast');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'classic-oatmeal-with-banana'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'classic-oatmeal-with-banana'), (select id from diet_tags where slug = 'gluten_free'));

-- Peanut Butter Banana Overnight Oats (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('peanut-butter-banana-overnight-oats', 'Peanut Butter Banana Overnight Oats', 'No-cook oats soaked overnight with peanut butter and banana.', 1, 5, 0, 'American', 1, 470.6, 20.8, 71.2, 13.7);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'peanut-butter-banana-overnight-oats'), (select id from ingredients where slug = 'rolled_oats'), 0.5, (select id from units where slug = 'cup'), null, false, 0),
  ((select id from recipes where slug = 'peanut-butter-banana-overnight-oats'), (select id from ingredients where slug = 'milk'), 0.5, (select id from units where slug = 'cup'), null, false, 1),
  ((select id from recipes where slug = 'peanut-butter-banana-overnight-oats'), (select id from ingredients where slug = 'greek_yogurt'), 0.25, (select id from units where slug = 'cup'), null, false, 2),
  ((select id from recipes where slug = 'peanut-butter-banana-overnight-oats'), (select id from ingredients where slug = 'peanut_butter'), 1, (select id from units where slug = 'tbsp'), null, false, 3),
  ((select id from recipes where slug = 'peanut-butter-banana-overnight-oats'), (select id from ingredients where slug = 'honey'), 1, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'peanut-butter-banana-overnight-oats'), (select id from ingredients where slug = 'chia_seeds'), 1, (select id from units where slug = 'tsp'), null, true, 5),
  ((select id from recipes where slug = 'peanut-butter-banana-overnight-oats'), (select id from ingredients where slug = 'banana'), 1, (select id from units where slug = 'each'), 'sliced', false, 6);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'peanut-butter-banana-overnight-oats'), 1, 'Combine oats, milk, yogurt, peanut butter, honey, and chia seeds in a jar.'),
  ((select id from recipes where slug = 'peanut-butter-banana-overnight-oats'), 2, 'Stir well, cover, and refrigerate overnight.'),
  ((select id from recipes where slug = 'peanut-butter-banana-overnight-oats'), 3, 'Top with sliced banana before eating.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'peanut-butter-banana-overnight-oats'), 'breakfast');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'peanut-butter-banana-overnight-oats'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'peanut-butter-banana-overnight-oats'), (select id from diet_tags where slug = 'gluten_free'));

-- Savory Oatmeal with Fried Egg (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('savory-oatmeal-with-egg', 'Savory Oatmeal with Fried Egg', 'A savory twist on oatmeal, topped with a fried egg and greens.', 1, 5, 10, 'American', 1, 318.9, 16.5, 30.0, 14.9);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'savory-oatmeal-with-egg'), (select id from ingredients where slug = 'rolled_oats'), 0.5, (select id from units where slug = 'cup'), null, false, 0),
  ((select id from recipes where slug = 'savory-oatmeal-with-egg'), (select id from ingredients where slug = 'vegetable_broth'), 1, (select id from units where slug = 'cup'), null, false, 1),
  ((select id from recipes where slug = 'savory-oatmeal-with-egg'), (select id from ingredients where slug = 'egg'), 1, (select id from units where slug = 'each'), null, false, 2),
  ((select id from recipes where slug = 'savory-oatmeal-with-egg'), (select id from ingredients where slug = 'spinach'), 0.5, (select id from units where slug = 'cup'), null, false, 3),
  ((select id from recipes where slug = 'savory-oatmeal-with-egg'), (select id from ingredients where slug = 'parmesan_cheese'), 2, (select id from units where slug = 'tbsp'), 'grated', false, 4),
  ((select id from recipes where slug = 'savory-oatmeal-with-egg'), (select id from ingredients where slug = 'olive_oil'), 1, (select id from units where slug = 'tsp'), null, false, 5),
  ((select id from recipes where slug = 'savory-oatmeal-with-egg'), (select id from ingredients where slug = 'black_pepper'), 0.25, (select id from units where slug = 'tsp'), null, false, 6),
  ((select id from recipes where slug = 'savory-oatmeal-with-egg'), (select id from ingredients where slug = 'salt'), 0.25, (select id from units where slug = 'tsp'), null, false, 7);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'savory-oatmeal-with-egg'), 1, 'Simmer oats in vegetable broth 5-6 minutes until thickened; stir in spinach until wilted.'),
  ((select id from recipes where slug = 'savory-oatmeal-with-egg'), 2, 'Fry the egg in olive oil to your liking.'),
  ((select id from recipes where slug = 'savory-oatmeal-with-egg'), 3, 'Top the oatmeal with parmesan, the fried egg, salt, and pepper.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'savory-oatmeal-with-egg'), 'breakfast');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'savory-oatmeal-with-egg'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'savory-oatmeal-with-egg'), (select id from diet_tags where slug = 'gluten_free'));

-- Baked Oatmeal Cups (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('baked-oatmeal-cups', 'Baked Oatmeal Cups', 'Make-ahead oatmeal muffin cups with banana and cinnamon.', 6, 10, 20, 'American', 2, 181.1, 7.1, 29.3, 4.1);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'baked-oatmeal-cups'), (select id from ingredients where slug = 'rolled_oats'), 2, (select id from units where slug = 'cup'), null, false, 0),
  ((select id from recipes where slug = 'baked-oatmeal-cups'), (select id from ingredients where slug = 'egg'), 2, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'baked-oatmeal-cups'), (select id from ingredients where slug = 'milk'), 1, (select id from units where slug = 'cup'), null, false, 2),
  ((select id from recipes where slug = 'baked-oatmeal-cups'), (select id from ingredients where slug = 'honey'), 3, (select id from units where slug = 'tbsp'), null, false, 3),
  ((select id from recipes where slug = 'baked-oatmeal-cups'), (select id from ingredients where slug = 'baking_powder'), 1, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'baked-oatmeal-cups'), (select id from ingredients where slug = 'cinnamon'), 1, (select id from units where slug = 'tsp'), null, false, 5),
  ((select id from recipes where slug = 'baked-oatmeal-cups'), (select id from ingredients where slug = 'vanilla_extract'), 1, (select id from units where slug = 'tsp'), null, false, 6),
  ((select id from recipes where slug = 'baked-oatmeal-cups'), (select id from ingredients where slug = 'walnuts'), 0.33, (select id from units where slug = 'cup'), null, true, 7);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'baked-oatmeal-cups'), 1, 'Preheat oven to 375°F (190°C) and grease a muffin tin.'),
  ((select id from recipes where slug = 'baked-oatmeal-cups'), 2, 'Mix all ingredients together in a bowl.'),
  ((select id from recipes where slug = 'baked-oatmeal-cups'), 3, 'Divide among muffin cups and bake 18-20 minutes until set and golden.'),
  ((select id from recipes where slug = 'baked-oatmeal-cups'), 4, 'Cool slightly before removing; store extras in the fridge.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'baked-oatmeal-cups'), 'breakfast'),
  ((select id from recipes where slug = 'baked-oatmeal-cups'), 'snack');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'baked-oatmeal-cups'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'baked-oatmeal-cups'), (select id from diet_tags where slug = 'gluten_free'));

-- Apple Cinnamon Oatmeal (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('apple-cinnamon-oatmeal', 'Apple Cinnamon Oatmeal', 'Warm oatmeal simmered with diced apple and cinnamon.', 2, 5, 10, 'American', 1, 344.8, 11.7, 62.6, 6.5);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'apple-cinnamon-oatmeal'), (select id from ingredients where slug = 'rolled_oats'), 1, (select id from units where slug = 'cup'), null, false, 0),
  ((select id from recipes where slug = 'apple-cinnamon-oatmeal'), (select id from ingredients where slug = 'milk'), 1.5, (select id from units where slug = 'cup'), null, false, 1),
  ((select id from recipes where slug = 'apple-cinnamon-oatmeal'), (select id from ingredients where slug = 'apple'), 1, (select id from units where slug = 'each'), 'diced', false, 2),
  ((select id from recipes where slug = 'apple-cinnamon-oatmeal'), (select id from ingredients where slug = 'cinnamon'), 0.5, (select id from units where slug = 'tsp'), null, false, 3),
  ((select id from recipes where slug = 'apple-cinnamon-oatmeal'), (select id from ingredients where slug = 'brown_sugar'), 2, (select id from units where slug = 'tbsp'), null, false, 4),
  ((select id from recipes where slug = 'apple-cinnamon-oatmeal'), (select id from ingredients where slug = 'walnuts'), 0.25, (select id from units where slug = 'cup'), null, true, 5);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'apple-cinnamon-oatmeal'), 1, 'Combine oats, milk, and cinnamon in a pot; bring to a simmer.'),
  ((select id from recipes where slug = 'apple-cinnamon-oatmeal'), 2, 'Add diced apple and cook 6-8 minutes, stirring occasionally, until the oats are creamy and the apple softens.'),
  ((select id from recipes where slug = 'apple-cinnamon-oatmeal'), 3, 'Stir in brown sugar and top with walnuts.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'apple-cinnamon-oatmeal'), 'breakfast');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'apple-cinnamon-oatmeal'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'apple-cinnamon-oatmeal'), (select id from diet_tags where slug = 'gluten_free'));

