-- Groundwork seed — recipes: yogurt
-- GENERATED by scripts/generate-recipes.mjs from scripts/recipe-data/yogurt.mjs — do not hand-edit.
-- Edit the source recipe definitions and re-run: npm run gen:recipes
--
-- kcal_per_serving/protein/carb/fat are COMPUTED from the ingredient list
-- below at generation time, not hand-typed — see this script's header.

-- Greek Yogurt Parfait (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('greek-yogurt-parfait', 'Greek Yogurt Parfait', 'Layered yogurt, honey, and berries with crunchy walnuts.', 1, 5, 0, 'American', 1, 295.4, 26.6, 27.9, 9.6);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'greek-yogurt-parfait'), (select id from ingredients where slug = 'greek_yogurt'), 1, (select id from units where slug = 'cup'), null, false, 0),
  ((select id from recipes where slug = 'greek-yogurt-parfait'), (select id from ingredients where slug = 'honey'), 1, (select id from units where slug = 'tbsp'), null, false, 1),
  ((select id from recipes where slug = 'greek-yogurt-parfait'), (select id from ingredients where slug = 'walnuts'), 2, (select id from units where slug = 'tbsp'), null, false, 2),
  ((select id from recipes where slug = 'greek-yogurt-parfait'), (select id from ingredients where slug = 'cinnamon'), 0.25, (select id from units where slug = 'tsp'), null, true, 3);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'greek-yogurt-parfait'), 1, 'Spoon half the yogurt into a glass or bowl.'),
  ((select id from recipes where slug = 'greek-yogurt-parfait'), 2, 'Drizzle with half the honey and scatter half the walnuts.'),
  ((select id from recipes where slug = 'greek-yogurt-parfait'), 3, 'Repeat with the remaining yogurt, honey, and walnuts. Dust with cinnamon if using.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'greek-yogurt-parfait'), 'breakfast'),
  ((select id from recipes where slug = 'greek-yogurt-parfait'), 'snack');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'greek-yogurt-parfait'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'greek-yogurt-parfait'), (select id from diet_tags where slug = 'gluten_free'));

-- Cucumber Yogurt Wrap (Mediterranean)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('tzatziki-chicken-wrap', 'Cucumber Yogurt Wrap', 'A cool yogurt-cucumber sauce wrapped with fresh vegetables.', 2, 10, 0, 'Mediterranean', 1, 224.8, 14.5, 34.2, 3.9);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'tzatziki-chicken-wrap'), (select id from ingredients where slug = 'greek_yogurt'), 0.75, (select id from units where slug = 'cup'), null, false, 0),
  ((select id from recipes where slug = 'tzatziki-chicken-wrap'), (select id from ingredients where slug = 'cucumber'), 0.5, (select id from units where slug = 'each'), 'diced', false, 1),
  ((select id from recipes where slug = 'tzatziki-chicken-wrap'), (select id from ingredients where slug = 'garlic'), 1, (select id from units where slug = 'clove'), null, false, 2),
  ((select id from recipes where slug = 'tzatziki-chicken-wrap'), (select id from ingredients where slug = 'lemon'), 0.5, (select id from units where slug = 'each'), null, false, 3),
  ((select id from recipes where slug = 'tzatziki-chicken-wrap'), (select id from ingredients where slug = 'tortilla_flour'), 2, (select id from units where slug = 'each'), null, false, 4),
  ((select id from recipes where slug = 'tzatziki-chicken-wrap'), (select id from ingredients where slug = 'lettuce_romaine'), 1, (select id from units where slug = 'cup'), 'shredded', false, 5),
  ((select id from recipes where slug = 'tzatziki-chicken-wrap'), (select id from ingredients where slug = 'tomato'), 1, (select id from units where slug = 'each'), 'diced', false, 6),
  ((select id from recipes where slug = 'tzatziki-chicken-wrap'), (select id from ingredients where slug = 'feta_cheese'), 0.25, (select id from units where slug = 'cup'), null, true, 7),
  ((select id from recipes where slug = 'tzatziki-chicken-wrap'), (select id from ingredients where slug = 'salt'), 0.25, (select id from units where slug = 'tsp'), null, false, 8);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'tzatziki-chicken-wrap'), 1, 'Mix yogurt, cucumber, minced garlic, lemon juice, and salt for the tzatziki.'),
  ((select id from recipes where slug = 'tzatziki-chicken-wrap'), 2, 'Spread onto tortillas and top with lettuce, tomato, and feta.'),
  ((select id from recipes where slug = 'tzatziki-chicken-wrap'), 3, 'Roll up tightly and slice in half to serve.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'tzatziki-chicken-wrap'), 'lunch');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'tzatziki-chicken-wrap'), (select id from diet_tags where slug = 'vegetarian'));

-- Yogurt Overnight Oats (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('overnight-yogurt-oats', 'Yogurt Overnight Oats', 'No-cook oats soaked overnight in yogurt and milk.', 1, 5, 0, 'American', 1, 328.7, 20.3, 52.5, 4.7);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'overnight-yogurt-oats'), (select id from ingredients where slug = 'rolled_oats'), 0.5, (select id from units where slug = 'cup'), null, false, 0),
  ((select id from recipes where slug = 'overnight-yogurt-oats'), (select id from ingredients where slug = 'greek_yogurt'), 0.5, (select id from units where slug = 'cup'), null, false, 1),
  ((select id from recipes where slug = 'overnight-yogurt-oats'), (select id from ingredients where slug = 'milk'), 0.33, (select id from units where slug = 'cup'), null, false, 2),
  ((select id from recipes where slug = 'overnight-yogurt-oats'), (select id from ingredients where slug = 'honey'), 1, (select id from units where slug = 'tbsp'), null, false, 3),
  ((select id from recipes where slug = 'overnight-yogurt-oats'), (select id from ingredients where slug = 'chia_seeds'), 1, (select id from units where slug = 'tbsp'), null, true, 4);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'overnight-yogurt-oats'), 1, 'Combine oats, yogurt, milk, honey, and chia seeds in a jar.'),
  ((select id from recipes where slug = 'overnight-yogurt-oats'), 2, 'Stir well, cover, and refrigerate overnight.'),
  ((select id from recipes where slug = 'overnight-yogurt-oats'), 3, 'Stir again before eating; add fruit or nuts if desired.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'overnight-yogurt-oats'), 'breakfast');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'overnight-yogurt-oats'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'overnight-yogurt-oats'), (select id from diet_tags where slug = 'gluten_free'));

-- Savory Cottage Cheese Bowl (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('cottage-cheese-bowl', 'Savory Cottage Cheese Bowl', 'High-protein cottage cheese with fresh vegetables and olive oil.', 1, 5, 0, 'American', 1, 288.3, 26.1, 13.7, 14.5);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'cottage-cheese-bowl'), (select id from ingredients where slug = 'cottage_cheese'), 1, (select id from units where slug = 'cup'), null, false, 0),
  ((select id from recipes where slug = 'cottage-cheese-bowl'), (select id from ingredients where slug = 'cherry_tomatoes'), 0.5, (select id from units where slug = 'cup'), null, false, 1),
  ((select id from recipes where slug = 'cottage-cheese-bowl'), (select id from ingredients where slug = 'cucumber'), 0.25, (select id from units where slug = 'each'), 'diced', false, 2),
  ((select id from recipes where slug = 'cottage-cheese-bowl'), (select id from ingredients where slug = 'olive_oil'), 1, (select id from units where slug = 'tsp'), null, false, 3),
  ((select id from recipes where slug = 'cottage-cheese-bowl'), (select id from ingredients where slug = 'black_pepper'), 0.25, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'cottage-cheese-bowl'), (select id from ingredients where slug = 'everything_bagel_seasoning'), 0.5, (select id from units where slug = 'tsp'), null, true, 5);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'cottage-cheese-bowl'), 1, 'Spoon the cottage cheese into a bowl.'),
  ((select id from recipes where slug = 'cottage-cheese-bowl'), 2, 'Top with cherry tomatoes and cucumber.'),
  ((select id from recipes where slug = 'cottage-cheese-bowl'), 3, 'Drizzle with olive oil, and finish with black pepper and everything bagel seasoning.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'cottage-cheese-bowl'), 'lunch'),
  ((select id from recipes where slug = 'cottage-cheese-bowl'), 'snack');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'cottage-cheese-bowl'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'cottage-cheese-bowl'), (select id from diet_tags where slug = 'gluten_free'));

-- Yogurt-Marinated Grilled Vegetable Skewers (Indian)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('yogurt-marinated-chicken-skewers', 'Yogurt-Marinated Grilled Vegetable Skewers', 'Yogurt-marinated vegetables, grilled until charred and tender.', 4, 15, 10, 'Indian', 2, 123.2, 7.0, 23.2, 0.8);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), (select id from ingredients where slug = 'greek_yogurt'), 0.5, (select id from units where slug = 'cup'), null, false, 0),
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), (select id from ingredients where slug = 'garam_masala'), 1, (select id from units where slug = 'tsp'), null, false, 1),
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), (select id from ingredients where slug = 'turmeric'), 0.5, (select id from units where slug = 'tsp'), null, false, 2),
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), (select id from ingredients where slug = 'garlic'), 2, (select id from units where slug = 'clove'), null, false, 3),
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), (select id from ingredients where slug = 'lemon'), 1, (select id from units where slug = 'each'), null, false, 4),
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), (select id from ingredients where slug = 'zucchini'), 1, (select id from units where slug = 'each'), 'sliced', false, 5),
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), (select id from ingredients where slug = 'bell_pepper_red'), 1, (select id from units where slug = 'each'), 'cubed', false, 6),
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), (select id from ingredients where slug = 'mushroom'), 150, (select id from units where slug = 'g'), null, false, 7),
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), (select id from ingredients where slug = 'white_rice'), 1, (select id from units where slug = 'cup'), 'uncooked', false, 8),
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), (select id from ingredients where slug = 'salt'), 1, (select id from units where slug = 'tsp'), null, false, 9);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), 1, 'Whisk yogurt, garam masala, turmeric, garlic, lemon juice, and salt. Toss with the vegetables and marinate 15 minutes.'),
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), 2, 'Thread onto skewers.'),
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), 3, 'Grill or broil, turning occasionally, 8-10 minutes until charred and tender.'),
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), 4, 'Cook rice and serve alongside.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), 'dinner');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), (select id from diet_tags where slug = 'vegetarian')),
  ((select id from recipes where slug = 'yogurt-marinated-chicken-skewers'), (select id from diet_tags where slug = 'gluten_free'));

-- Cottage Cheese Pancakes (American)
insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)
values ('cottage-cheese-pancakes', 'Cottage Cheese Pancakes', 'High-protein pancakes made with blended cottage cheese.', 2, 5, 12, 'American', 1, 348.7, 22.1, 28.7, 15.4);
insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values
  ((select id from recipes where slug = 'cottage-cheese-pancakes'), (select id from ingredients where slug = 'cottage_cheese'), 1, (select id from units where slug = 'cup'), null, false, 0),
  ((select id from recipes where slug = 'cottage-cheese-pancakes'), (select id from ingredients where slug = 'egg'), 2, (select id from units where slug = 'each'), null, false, 1),
  ((select id from recipes where slug = 'cottage-cheese-pancakes'), (select id from ingredients where slug = 'all_purpose_flour'), 0.5, (select id from units where slug = 'cup'), null, false, 2),
  ((select id from recipes where slug = 'cottage-cheese-pancakes'), (select id from ingredients where slug = 'baking_powder'), 1, (select id from units where slug = 'tsp'), null, false, 3),
  ((select id from recipes where slug = 'cottage-cheese-pancakes'), (select id from ingredients where slug = 'vanilla_extract'), 0.5, (select id from units where slug = 'tsp'), null, false, 4),
  ((select id from recipes where slug = 'cottage-cheese-pancakes'), (select id from ingredients where slug = 'butter'), 1, (select id from units where slug = 'tbsp'), null, false, 5),
  ((select id from recipes where slug = 'cottage-cheese-pancakes'), (select id from ingredients where slug = 'maple_syrup'), 2, (select id from units where slug = 'tbsp'), null, true, 6);
insert into recipe_steps (recipe_id, step_number, instruction) values
  ((select id from recipes where slug = 'cottage-cheese-pancakes'), 1, 'Blend cottage cheese, eggs, flour, baking powder, and vanilla until mostly smooth.'),
  ((select id from recipes where slug = 'cottage-cheese-pancakes'), 2, 'Melt butter in a nonstick pan over medium heat. Pour small rounds of batter and cook 2-3 minutes per side until golden.'),
  ((select id from recipes where slug = 'cottage-cheese-pancakes'), 3, 'Serve with maple syrup.');
insert into recipe_meal_slots (recipe_id, slot) values
  ((select id from recipes where slug = 'cottage-cheese-pancakes'), 'breakfast');
insert into recipe_diet_tags (recipe_id, diet_tag_id) values
  ((select id from recipes where slug = 'cottage-cheese-pancakes'), (select id from diet_tags where slug = 'vegetarian'));

