#!/usr/bin/env node
// Generates supabase/seed/00X_recipes_<family>.sql files from the recipe
// definitions under scripts/recipe-data/*.mjs.
//
// WHY GENERATE RATHER THAN HAND-WRITE THE SQL: recipes.kcal_per_serving
// etc. are a denormalised cache of what recipe_ingredients actually sums
// to (docs/schema.md: "recompute on save, treat the stored value as a
// single-writer cache"). Hand-typing both the ingredient list AND its
// derived macro totals for 200+ recipes would inevitably drift — this
// script IS the "recompute on save" step, run once at author time instead
// of by a database trigger, since there's no live database yet. Recipe
// definitions (scripts/recipe-data/*.mjs) are the actual source of truth
// to edit; the .sql output is a build artifact, same relationship as
// docs/*.md are to the design artifacts, or db.ts is to the Postgres schema.
//
// Diet tags are DERIVED here from the structured ingredient list, not
// hand-assigned per recipe. docs/schema.md's guidance to hand-tag diet
// tags is about free-text or loosely-tagged data ("did this use chicken
// stock?") where inference genuinely gets it wrong; every ingredient here
// is fully structured, so "no ingredient tagged as meat/poultry/fish is
// present" is not an inference, it's a direct read of the data — the
// scenario that guidance warns about doesn't apply to a corpus built this way.

import { readdirSync, writeFileSync, unlinkSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { buildIngredientIndex, computeRecipeTotals, resolveGrams } from './lib/ingredientIndex.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const index = buildIngredientIndex(root)

// ── ingredient category tags, for deriving diet_tags ───────────────────
const MEAT = new Set(['ground_beef', 'beef_sirloin', 'beef_flank_steak', 'pork_chop', 'pork_tenderloin', 'ground_pork'])
const POULTRY = new Set(['chicken_thigh', 'chicken_breast', 'ground_turkey', 'turkey_breast'])
const FISH_SHELLFISH = new Set(['salmon_fillet', 'cod_fillet', 'tilapia_fillet', 'shrimp', 'fish_sauce', 'oyster_sauce'])
const DAIRY_OR_EGG = new Set([
  'milk', 'butter', 'cheddar_cheese', 'parmesan_cheese', 'mozzarella_cheese', 'feta_cheese',
  'sour_cream', 'cream_cheese', 'heavy_cream', 'greek_yogurt', 'cottage_cheese', 'egg', 'honey',
])
const GLUTEN = new Set([
  'all_purpose_flour', 'panko_breadcrumbs', 'spaghetti', 'pasta_penne', 'couscous',
  'tortilla_flour', 'bread_sandwich', 'naan', 'pita_bread',
])

function deriveDietTags(ingredientLines, proteinPerServing) {
  const slugs = new Set(ingredientLines.filter((l) => !l.optional).map((l) => l.slug))
  const has = (set) => [...slugs].some((s) => set.has(s))
  const tags = []
  const isVegetarian = !has(MEAT) && !has(POULTRY) && !has(FISH_SHELLFISH)
  const isPescatarian = !has(MEAT) && !has(POULTRY)
  if (isVegetarian) tags.push('vegetarian')
  if (isVegetarian && !has(DAIRY_OR_EGG)) tags.push('vegan')
  if (isPescatarian && !isVegetarian) tags.push('pescatarian')
  if (!has(GLUTEN)) tags.push('gluten_free')
  const dairyAllergenSlugs = new Set(['milk', 'butter', 'cheddar_cheese', 'parmesan_cheese', 'mozzarella_cheese', 'feta_cheese', 'sour_cream', 'cream_cheese', 'heavy_cream', 'greek_yogurt', 'cottage_cheese'])
  if (!has(dairyAllergenSlugs)) tags.push('dairy_free')
  if (proteinPerServing >= 30) tags.push('high_protein')
  return tags
}

function sqlStr(s) {
  return `'${String(s).replace(/'/g, "''")}'`
}

function ingredientSubquery(slug) {
  return `(select id from ingredients where slug = ${sqlStr(slug)})`
}
function unitSubquery(slug) {
  return `(select id from units where slug = ${sqlStr(slug)})`
}
function dietTagSubquery(slug) {
  return `(select id from diet_tags where slug = ${sqlStr(slug)})`
}

function generateFamilySql(familyName, recipes) {
  const lines = []
  lines.push(`-- Groundwork seed — recipes: ${familyName}`)
  lines.push(`-- GENERATED by scripts/generate-recipes.mjs from scripts/recipe-data/${familyName}.mjs — do not hand-edit.`)
  lines.push(`-- Edit the source recipe definitions and re-run: npm run gen:recipes`)
  lines.push(`--`)
  lines.push(`-- kcal_per_serving/protein/carb/fat are COMPUTED from the ingredient list`)
  lines.push(`-- below at generation time, not hand-typed — see this script's header.`)
  lines.push('')

  const report = []

  for (const r of recipes) {
    const totals = computeRecipeTotals(index, r.ingredients)
    const perServing = {
      kcal: totals.kcal / r.servings,
      protein: totals.protein / r.servings,
      carb: totals.carb / r.servings,
      fat: totals.fat / r.servings,
    }
    const dietTags = deriveDietTags(r.ingredients, perServing.protein)
    report.push({ slug: r.slug, title: r.title, cuisine: r.cuisine, ...perServing, dietTags })

    lines.push(`-- ${r.title} (${r.cuisine})`)
    lines.push(`insert into recipes (slug, title, summary, servings, prep_minutes, cook_minutes, cuisine, difficulty, kcal_per_serving, protein_per_serving, carb_per_serving, fat_per_serving)`)
    lines.push(`values (${sqlStr(r.slug)}, ${sqlStr(r.title)}, ${sqlStr(r.summary)}, ${r.servings}, ${r.prepMinutes}, ${r.cookMinutes}, ${sqlStr(r.cuisine)}, ${r.difficulty}, ${perServing.kcal.toFixed(1)}, ${perServing.protein.toFixed(1)}, ${perServing.carb.toFixed(1)}, ${perServing.fat.toFixed(1)});`)

    lines.push(`insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit_id, prep_note, is_optional, order_index) values`)
    const ingRows = r.ingredients.map((line, i) => {
      const prepNote = line.prepNote ? sqlStr(line.prepNote) : 'null'
      return `  ((select id from recipes where slug = ${sqlStr(r.slug)}), ${ingredientSubquery(line.slug)}, ${line.qty}, ${unitSubquery(line.unit)}, ${prepNote}, ${line.optional ? 'true' : 'false'}, ${i})`
    })
    lines.push(ingRows.join(',\n') + ';')

    lines.push(`insert into recipe_steps (recipe_id, step_number, instruction) values`)
    const stepRows = r.steps.map((s, i) => `  ((select id from recipes where slug = ${sqlStr(r.slug)}), ${i + 1}, ${sqlStr(s)})`)
    lines.push(stepRows.join(',\n') + ';')

    lines.push(`insert into recipe_meal_slots (recipe_id, slot) values`)
    lines.push(r.mealSlots.map((slot) => `  ((select id from recipes where slug = ${sqlStr(r.slug)}), ${sqlStr(slot)})`).join(',\n') + ';')

    if (dietTags.length) {
      lines.push(`insert into recipe_diet_tags (recipe_id, diet_tag_id) values`)
      lines.push(dietTags.map((tag) => `  ((select id from recipes where slug = ${sqlStr(r.slug)}), ${dietTagSubquery(tag)})`).join(',\n') + ';')
    }
    lines.push('')
  }

  return { sql: lines.join('\n'), report }
}

// ── main ────────────────────────────────────────────────────────────────
// These are generated build artifacts (see header) — always regenerate
// from a clean slate. Without this, renumbering a family (e.g. adding a
// new .mjs file that sorts earlier alphabetically, shifting every later
// family's output number) leaves the OLD numbered file on disk as an
// orphaned duplicate of content that now lives under a new number. Caught
// exactly that way while building this out: verify-recipes.mjs flagged 9
// "duplicate recipe slug" errors that were really one stale file.
const seedDir = join(root, 'supabase', 'seed')
for (const f of readdirSync(seedDir)) {
  if (/_recipes_.*\.sql$/.test(f)) unlinkSync(join(seedDir, f))
}

const dataDir = join(root, 'scripts', 'recipe-data')
const files = readdirSync(dataDir).filter((f) => f.endsWith('.mjs')).sort()

let fileNum = 3 // 001 = movement library, 002 = food reference
const fullReport = []
const allSlugs = new Set()

for (const file of files) {
  const familyName = file.replace(/\.mjs$/, '')
  const mod = await import(pathToFileURL(join(dataDir, file)).href)
  const recipes = mod.recipes
  if (!Array.isArray(recipes)) throw new Error(`${file}: expected a named export "recipes" (array)`)

  for (const r of recipes) {
    if (allSlugs.has(r.slug)) throw new Error(`duplicate recipe slug across families: ${r.slug}`)
    allSlugs.add(r.slug)
  }

  let result
  try {
    result = generateFamilySql(familyName, recipes)
  } catch (err) {
    console.error(`FAILED generating ${familyName}: ${err.message}`)
    process.exit(1)
  }

  const outName = `${String(fileNum).padStart(3, '0')}_recipes_${familyName}.sql`
  writeFileSync(join(seedDir, outName), result.sql + '\n')
  console.log(`wrote supabase/seed/${outName} — ${recipes.length} recipes`)
  fullReport.push(...result.report)
  fileNum++
}

console.log(`\n${fullReport.length} recipes generated across ${files.length} families.`)
const cuisines = new Map()
for (const r of fullReport) cuisines.set(r.cuisine, (cuisines.get(r.cuisine) ?? 0) + 1)
console.log('\nCuisine distribution:')
for (const [c, n] of [...cuisines.entries()].sort((a, b) => b[1] - a[1])) console.log(`  ${c.padEnd(20)} ${n}`)
