import type { MealSlot, Recipe, RecipeDietTag, RecipeIngredient, RecipeMealSlot, RecipeStep } from '@/types/domain'

import { num, parseInsertRows, slugFromRef, stripComments, unquote } from './sqlParse'

/**
 * Pure string -> data parser for one `supabase/seed/0*_recipes_*.sql`
 * file's format (all 14 are GENERATED by scripts/generate-recipes.mjs
 * from the same template, so one parser handles all of them). Mirrors
 * parseFoodReferenceSeed.ts's approach and is used the same two places:
 * loadRealFoodSeed.ts (test-only) and src/lib/devContentSeed.ts (browser,
 * dev-mode only).
 *
 * Needs `unitIdBySlug`/`dietTagIdBySlug` from a prior
 * parseFoodReferenceSeed() call, and `knownIngredientSlugs` from that same
 * result's `ingredients` list — a recipe file's rows are meaningless
 * without the food-reference file already parsed, exactly mirroring the
 * real SQL's own load order (002 before 003+).
 */

export interface RecipeSeedData {
  recipes: Recipe[]
  recipeIngredients: RecipeIngredient[]
  recipeSteps: RecipeStep[]
  recipeMealSlots: RecipeMealSlot[]
  recipeDietTags: RecipeDietTag[]
}

export interface RecipeSeedRefs {
  unitIdBySlug: ReadonlyMap<string, number>
  dietTagIdBySlug: ReadonlyMap<string, number>
  knownIngredientSlugs: ReadonlySet<string>
}

const EMPTY_RECIPE_SEED: RecipeSeedData = { recipes: [], recipeIngredients: [], recipeSteps: [], recipeMealSlots: [], recipeDietTags: [] }

export function parseRecipeSeed(rawSql: string, refs: RecipeSeedRefs): RecipeSeedData {
  const sql = stripComments(rawSql)

  const recipes: Recipe[] = parseInsertRows(sql, 'recipes').map((row) => ({
    id: unquote(row.slug)!,
    slug: unquote(row.slug)!,
    title: unquote(row.title)!,
    summary: unquote(row.summary),
    servings: num(row.servings)!,
    prepMinutes: num(row.prep_minutes)!,
    cookMinutes: num(row.cook_minutes)!,
    cuisine: unquote(row.cuisine),
    imageUrl: unquote(row.image_url),
    difficulty: num(row.difficulty) as Recipe['difficulty'],
    kcalPerServing: num(row.kcal_per_serving)!,
    proteinPerServing: num(row.protein_per_serving)!,
    carbPerServing: num(row.carb_per_serving)!,
    fatPerServing: num(row.fat_per_serving)!,
    isActive: row.is_active !== undefined ? unquote(row.is_active) === 'true' : true,
    updatedAt: unquote(row.updated_at) ?? new Date(0).toISOString(),
  }))
  const recipeSlugs = new Set(recipes.map((r) => r.slug))

  function resolveRecipeSlug(cell: string | undefined, context: string): string {
    const slug = slugFromRef(cell)
    if (!slug || !recipeSlugs.has(slug)) throw new Error(`parseRecipeSeed: ${context} references unknown recipe slug "${slug}"`)
    return slug
  }

  let ingredientOrdinal = 0
  const recipeIngredients: RecipeIngredient[] = parseInsertRows(sql, 'recipe_ingredients').map((row) => {
    const recipeId = resolveRecipeSlug(row.recipe_id, 'recipe_ingredients')
    const ingredientId = slugFromRef(row.ingredient_id)
    if (!ingredientId || !refs.knownIngredientSlugs.has(ingredientId)) {
      throw new Error(`parseRecipeSeed: recipe "${recipeId}" references unknown ingredient "${ingredientId}"`)
    }
    const unitSlug = slugFromRef(row.unit_id)
    const unitId = unitSlug ? refs.unitIdBySlug.get(unitSlug) : undefined
    if (unitId === undefined) throw new Error(`parseRecipeSeed: recipe "${recipeId}" references unknown unit "${unitSlug}"`)

    return {
      id: `${recipeId}::ingredient::${ingredientOrdinal++}`,
      recipeId,
      ingredientId,
      quantity: num(row.quantity)!,
      unitId,
      prepNote: unquote(row.prep_note),
      isOptional: unquote(row.is_optional) === 'true',
      orderIndex: num(row.order_index)!,
    }
  })

  const recipeSteps: RecipeStep[] = parseInsertRows(sql, 'recipe_steps').map((row) => ({
    recipeId: resolveRecipeSlug(row.recipe_id, 'recipe_steps'),
    stepNumber: num(row.step_number)!,
    instruction: unquote(row.instruction)!,
  }))

  const recipeMealSlots: RecipeMealSlot[] = parseInsertRows(sql, 'recipe_meal_slots').map((row) => ({
    recipeId: resolveRecipeSlug(row.recipe_id, 'recipe_meal_slots'),
    slot: unquote(row.slot) as MealSlot,
  }))

  const recipeDietTags: RecipeDietTag[] = parseInsertRows(sql, 'recipe_diet_tags').map((row) => {
    const recipeId = resolveRecipeSlug(row.recipe_id, 'recipe_diet_tags')
    const dietTagSlug = slugFromRef(row.diet_tag_id)
    const dietTagId = dietTagSlug ? refs.dietTagIdBySlug.get(dietTagSlug) : undefined
    if (dietTagId === undefined) throw new Error(`parseRecipeSeed: recipe "${recipeId}" references unknown diet tag "${dietTagSlug}"`)
    return { recipeId, dietTagId }
  })

  return { recipes, recipeIngredients, recipeSteps, recipeMealSlots, recipeDietTags }
}

/** Parses and concatenates every recipe file's text in one call, checking
 *  for a recipe slug reused across two families (would silently merge two
 *  unrelated recipes' ingredients/steps if it ever happened). */
export function parseAllRecipeSeeds(rawSqlFiles: string[], refs: RecipeSeedRefs): RecipeSeedData {
  const combined: RecipeSeedData = {
    recipes: [...EMPTY_RECIPE_SEED.recipes],
    recipeIngredients: [...EMPTY_RECIPE_SEED.recipeIngredients],
    recipeSteps: [...EMPTY_RECIPE_SEED.recipeSteps],
    recipeMealSlots: [...EMPTY_RECIPE_SEED.recipeMealSlots],
    recipeDietTags: [...EMPTY_RECIPE_SEED.recipeDietTags],
  }
  const seenSlugs = new Set<string>()

  for (const rawSql of rawSqlFiles) {
    const parsed = parseRecipeSeed(rawSql, refs)
    for (const recipe of parsed.recipes) {
      if (seenSlugs.has(recipe.slug)) throw new Error(`parseAllRecipeSeeds: recipe slug "${recipe.slug}" appears in more than one file`)
      seenSlugs.add(recipe.slug)
    }
    combined.recipes.push(...parsed.recipes)
    combined.recipeIngredients.push(...parsed.recipeIngredients)
    combined.recipeSteps.push(...parsed.recipeSteps)
    combined.recipeMealSlots.push(...parsed.recipeMealSlots)
    combined.recipeDietTags.push(...parsed.recipeDietTags)
  }

  if (combined.recipes.length !== 200) {
    throw new Error(
      `parseAllRecipeSeeds: expected 200 recipes across all files (see scripts/verify-recipes.mjs), got ${combined.recipes.length} — ` +
        `either the corpus changed and this number needs updating, or a file failed to parse silently short.`,
    )
  }
  return combined
}
